<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="Course readings for XQMB 5311 – Statistics for Business – The University of Texas at El Paso.">

<title>4&nbsp; Interval Estimation and Hypothesis Testing – The Precision Advantage: Statistics for Business</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./chapter_04.html" rel="next">
<link href="./chapter_02.html" rel="prev">
<link href="./favicon.png" rel="icon" type="image/png">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-065a5179aebd64318d7ea99d77b64a9e.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-969ddfa49e00a70eb3423444dbc81f6c.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-065a5179aebd64318d7ea99d77b64a9e.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-224b48a91c0f626bf087add3423f4096.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark-8fba65ec5d79e9223d5579f32ee5f772.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="site_libs/bootstrap/bootstrap-224b48a91c0f626bf087add3423f4096.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="https://raw.github.com/ncachanosky/EO-styles/main/styles.css">
<meta property="og:title" content="The Precision Advantage: Statistics for Business">
<meta property="og:description" content="Course readings for XQMB 5311 – Quantitative Methods for Business – The University of Texas at El Paso. An institutions-first treatment of monetary and financial economics.">
<meta property="og:image" content="https://ncachanosky.github.io/XQMB-5311/assets/logo.png">
<meta property="og:site_name" content="The Precision Advantage: Statistics for Business">
<meta property="og:image:height" content="1687">
<meta property="og:image:width" content="1687">
<meta name="twitter:title" content="Money, The Precision Advantage: Statistics for Business">
<meta name="twitter:description" content="Course readings for ECON 3320 – Quantitative Methods for Business – The University of Texas at El Paso. An institutions-first treatment of monetary and financial economics.">
<meta name="twitter:image" content="https://ncachanosky.github.io/XQMB-5311/assets/logo.png">
<meta name="twitter:creator" content="@n_cachanosky">
<meta name="twitter:card" content="summary">
<meta name="twitter:image-height" content="1687">
<meta name="twitter:image-width" content="1687">
</head>

<body class="nav-sidebar docked quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./chapter_03.html"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Interval Estimation and Hypothesis Testing</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="./index.html" class="sidebar-logo-link">
      <img src="./assets/logo.png" alt="" class="sidebar-logo light-content py-0 d-lg-inline d-none">
      <img src="./assets/logo.png" alt="" class="sidebar-logo dark-content py-0 d-lg-inline d-none">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="./">The Precision Advantage: Statistics for Business</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/ncachanosky/XQMB-5311" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter_01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Descriptive Statistics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter_02.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Probability</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter_03.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Interval Estimation and Hypothesis Testing</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter_04.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">ANOVA: Analysis of Variance</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter_05.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Categorical Data Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter_06.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Statistical Foundations Review: From Description to Decision</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter_07.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Regression Analysis: Introduction to Econometrics</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#learning-objectives" id="toc-learning-objectives" class="nav-link active" data-scroll-target="#learning-objectives">Learning Objectives</a></li>
  <li><a href="#introduction-the-500-million-question" id="toc-introduction-the-500-million-question" class="nav-link" data-scroll-target="#introduction-the-500-million-question"><span class="header-section-number">4.1</span> Introduction: The $500 Million Question</a></li>
  <li><a href="#connecting-the-journey-from-description-to-inference" id="toc-connecting-the-journey-from-description-to-inference" class="nav-link" data-scroll-target="#connecting-the-journey-from-description-to-inference"><span class="header-section-number">4.2</span> Connecting the Journey: From Description to Inference</a>
  <ul class="collapse">
  <li><a href="#the-three-questions-of-statistics" id="toc-the-three-questions-of-statistics" class="nav-link" data-scroll-target="#the-three-questions-of-statistics">The Three Questions of Statistics</a></li>
  </ul></li>
  <li><a href="#the-first-error-confusing-statistics-with-parameters" id="toc-the-first-error-confusing-statistics-with-parameters" class="nav-link" data-scroll-target="#the-first-error-confusing-statistics-with-parameters"><span class="header-section-number">4.3</span> The First Error: Confusing Statistics with Parameters</a>
  <ul class="collapse">
  <li><a href="#why-this-distinction-matters" id="toc-why-this-distinction-matters" class="nav-link" data-scroll-target="#why-this-distinction-matters">Why This Distinction Matters</a></li>
  </ul></li>
  <li><a href="#the-second-error-missing-confidence-intervals" id="toc-the-second-error-missing-confidence-intervals" class="nav-link" data-scroll-target="#the-second-error-missing-confidence-intervals"><span class="header-section-number">4.4</span> The Second Error: Missing Confidence Intervals</a>
  <ul class="collapse">
  <li><a href="#calculating-the-confidence-interval" id="toc-calculating-the-confidence-interval" class="nav-link" data-scroll-target="#calculating-the-confidence-interval">Calculating the Confidence Interval</a></li>
  <li><a href="#why-confidence-intervals-matter-for-business-decisions" id="toc-why-confidence-intervals-matter-for-business-decisions" class="nav-link" data-scroll-target="#why-confidence-intervals-matter-for-business-decisions">Why Confidence Intervals Matter for Business Decisions</a></li>
  </ul></li>
  <li><a href="#the-third-error-misinterpreting-p-values" id="toc-the-third-error-misinterpreting-p-values" class="nav-link" data-scroll-target="#the-third-error-misinterpreting-p-values"><span class="header-section-number">4.5</span> The Third Error: Misinterpreting P-Values</a>
  <ul class="collapse">
  <li><a href="#what-p-values-actually-mean" id="toc-what-p-values-actually-mean" class="nav-link" data-scroll-target="#what-p-values-actually-mean">What P-Values Actually Mean</a></li>
  <li><a href="#the-prosecutors-fallacy" id="toc-the-prosecutors-fallacy" class="nav-link" data-scroll-target="#the-prosecutors-fallacy">The “Prosecutor’s Fallacy”</a></li>
  </ul></li>
  <li><a href="#the-fourth-error-accepting-the-null-hypothesis" id="toc-the-fourth-error-accepting-the-null-hypothesis" class="nav-link" data-scroll-target="#the-fourth-error-accepting-the-null-hypothesis"><span class="header-section-number">4.6</span> The Fourth Error: “Accepting” the Null Hypothesis</a>
  <ul class="collapse">
  <li><a href="#the-asymmetry-of-hypothesis-testing" id="toc-the-asymmetry-of-hypothesis-testing" class="nav-link" data-scroll-target="#the-asymmetry-of-hypothesis-testing">The Asymmetry of Hypothesis Testing</a></li>
  <li><a href="#the-specific-problem-with-bordermeds-safety-analysis" id="toc-the-specific-problem-with-bordermeds-safety-analysis" class="nav-link" data-scroll-target="#the-specific-problem-with-bordermeds-safety-analysis">The Specific Problem with BorderMed’s Safety Analysis</a></li>
  </ul></li>
  <li><a href="#the-fifth-error-ignoring-type-i-and-type-ii-errors" id="toc-the-fifth-error-ignoring-type-i-and-type-ii-errors" class="nav-link" data-scroll-target="#the-fifth-error-ignoring-type-i-and-type-ii-errors"><span class="header-section-number">4.7</span> The Fifth Error: Ignoring Type I and Type II Errors</a>
  <ul class="collapse">
  <li><a href="#type-i-error-the-false-positive" id="toc-type-i-error-the-false-positive" class="nav-link" data-scroll-target="#type-i-error-the-false-positive">Type I Error: The False Positive</a></li>
  <li><a href="#type-ii-error-the-false-negative" id="toc-type-ii-error-the-false-negative" class="nav-link" data-scroll-target="#type-ii-error-the-false-negative">Type II Error: The False Negative</a></li>
  <li><a href="#calculating-power-and-sample-size" id="toc-calculating-power-and-sample-size" class="nav-link" data-scroll-target="#calculating-power-and-sample-size">Calculating Power and Sample Size</a></li>
  </ul></li>
  <li><a href="#the-sixth-error-ignoring-small-sample-sizes" id="toc-the-sixth-error-ignoring-small-sample-sizes" class="nav-link" data-scroll-target="#the-sixth-error-ignoring-small-sample-sizes"><span class="header-section-number">4.8</span> The Sixth Error: Ignoring Small Sample Sizes</a></li>
  <li><a href="#creating-the-corrected-report" id="toc-creating-the-corrected-report" class="nav-link" data-scroll-target="#creating-the-corrected-report"><span class="header-section-number">4.9</span> Creating the Corrected Report</a>
  <ul class="collapse">
  <li><a href="#proper-confidence-intervals" id="toc-proper-confidence-intervals" class="nav-link" data-scroll-target="#proper-confidence-intervals">Proper Confidence Intervals</a></li>
  <li><a href="#proper-p-value-interpretation" id="toc-proper-p-value-interpretation" class="nav-link" data-scroll-target="#proper-p-value-interpretation">Proper P-Value Interpretation</a></li>
  <li><a href="#proper-treatment-of-fail-to-reject" id="toc-proper-treatment-of-fail-to-reject" class="nav-link" data-scroll-target="#proper-treatment-of-fail-to-reject">Proper Treatment of “Fail to Reject”</a></li>
  <li><a href="#sample-size-justification" id="toc-sample-size-justification" class="nav-link" data-scroll-target="#sample-size-justification">Sample Size Justification</a></li>
  <li><a href="#a-comprehensive-limitations-section" id="toc-a-comprehensive-limitations-section" class="nav-link" data-scroll-target="#a-comprehensive-limitations-section">A Comprehensive Limitations Section</a></li>
  <li><a href="#measured-recommendations" id="toc-measured-recommendations" class="nav-link" data-scroll-target="#measured-recommendations">Measured Recommendations</a></li>
  </ul></li>
  <li><a href="#the-board-presentation" id="toc-the-board-presentation" class="nav-link" data-scroll-target="#the-board-presentation"><span class="header-section-number">4.10</span> The Board Presentation</a></li>
  <li><a href="#connecting-the-statistical-journey" id="toc-connecting-the-statistical-journey" class="nav-link" data-scroll-target="#connecting-the-statistical-journey"><span class="header-section-number">4.11</span> Connecting the Statistical Journey</a></li>
  <li><a href="#chapter-summary-from-samples-to-populations" id="toc-chapter-summary-from-samples-to-populations" class="nav-link" data-scroll-target="#chapter-summary-from-samples-to-populations"><span class="header-section-number">4.12</span> Chapter Summary: From Samples to Populations</a></li>
  <li><a href="#looking-ahead" id="toc-looking-ahead" class="nav-link" data-scroll-target="#looking-ahead"><span class="header-section-number">4.13</span> Looking Ahead</a></li>
  <li><a href="#practice-problems" id="toc-practice-problems" class="nav-link" data-scroll-target="#practice-problems"><span class="header-section-number">4.14</span> Practice Problems</a>
  <ul class="collapse">
  <li><a href="#problem-set-1-confidence-intervals-30-points" id="toc-problem-set-1-confidence-intervals-30-points" class="nav-link" data-scroll-target="#problem-set-1-confidence-intervals-30-points">Problem Set 1: Confidence Intervals (30 points)</a></li>
  <li><a href="#problem-set-2-hypothesis-testing-35-points" id="toc-problem-set-2-hypothesis-testing-35-points" class="nav-link" data-scroll-target="#problem-set-2-hypothesis-testing-35-points">Problem Set 2: Hypothesis Testing (35 points)</a></li>
  <li><a href="#problem-set-3-sample-size-and-power-20-points" id="toc-problem-set-3-sample-size-and-power-20-points" class="nav-link" data-scroll-target="#problem-set-3-sample-size-and-power-20-points">Problem Set 3: Sample Size and Power (20 points)</a></li>
  <li><a href="#problem-set-4-site-specific-analysis-15-points" id="toc-problem-set-4-site-specific-analysis-15-points" class="nav-link" data-scroll-target="#problem-set-4-site-specific-analysis-15-points">Problem Set 4: Site-Specific Analysis (15 points)</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/ncachanosky/XQMB-5311/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Interval Estimation and Hypothesis Testing</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  
<div>
  <div class="abstract">
    <div class="block-title">Abstract</div>
    <p>Correct calculations with incorrect interpretation can be just as dangerous as wrong numbers. This chapter develops the logic of statistical inference — confidence intervals, hypothesis testing, and the proper meaning of p-values — through BorderMed Pharmaceuticals’ Phase II clinical trial, where a $500 million Phase III commitment hangs on whether the analysis team understands what their results actually say. Students learn to quantify uncertainty honestly, avoid common inference errors, and communicate statistical findings with appropriate precision.</p>
  </div>
</div>


</header>


<section id="learning-objectives" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="learning-objectives">Learning Objectives</h2>
<p>By the end of this chapter, you will be able to:</p>
<ol type="1">
<li>✅ Distinguish between sample statistics and population parameters</li>
<li>✅ Calculate and interpret confidence intervals for means and proportions</li>
<li>✅ Determine appropriate sample sizes for desired precision</li>
<li>✅ Conduct and interpret hypothesis tests properly</li>
<li>✅ Understand Type I and Type II errors and their business consequences</li>
<li>✅ Communicate statistical uncertainty appropriately in business contexts</li>
</ol>
</section>
<section id="introduction-the-500-million-question" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="introduction-the-500-million-question"><span class="header-section-number">4.1</span> Introduction: The $500 Million Question</h2>
<p>It’s 9:30 AM on July 18, 2025. Dr.&nbsp;Katherine Walsh, Chief Medical Officer of BorderMed Pharmaceuticals, sits in the boardroom reviewing a Phase II clinical trial report. The stakes couldn’t be higher: advancing to Phase III means committing <strong>$500 million</strong> over the next three years.</p>
<p>She reads the executive summary:</p>
<blockquote class="blockquote">
<p>VasoRelief reduced systolic blood pressure by 12.4 mmHg on average. This 12.4 mmHg reduction <strong>represents the true efficacy</strong> of the drug, as measured in our patient population… The <em>p</em>-value less than 0.001 <strong>proves</strong> that VasoRelief causes blood pressure reduction. We can say with <strong>over 99.9% certainty</strong> that VasoRelief works… We <strong>accept</strong> that VasoRelief’s headache rate is the same as placebo. <strong>There is no significant headache risk.</strong></p>
</blockquote>
<p>Dr.&nbsp;Walsh sets down the report and looks at her leadership team. “This is going to the FDA?”</p>
<p>Her VP of Regulatory Affairs shifts uncomfortably. “The statistics look solid. Strong <em>p</em>-values, clear efficacy—”</p>
<p>“The <em>language</em> doesn’t look solid,” Dr.&nbsp;Walsh interrupts. “‘Represents the true efficacy’? We tested 85 patients. ‘Proves the drug works’? That’s not how <em>p</em>-values work. ‘Accept the null hypothesis’? That’s a statistics 101 error.”</p>
<p>The room falls silent.</p>
<p>“This report will get us laughed out of the FDA,” she continues. “Or worse, we’ll invest half a billion dollars in Phase III only to discover our Phase II conclusions were overconfident. I need this analyzed by someone who understands statistical inference.”</p>
<p>Her Director of Clinical Operations speaks up. “There’s a success story I heard about from the Southwest. Two EMBA students at UTEP who transformed a manufacturing company’s quality control analysis. They’d worked with TechFlow and PrecisionCast Industries. Maybe they can help?”</p>
<p>Dr.&nbsp;Walsh nods. “Get them. We have one week before the board meeting.”</p>
<p>The clinical team realizes they lack the statistical expertise to distinguish between proper and improper inference. Following the success stories from TechFlow Solutions and PrecisionCast Industries, they reach out to the EMBA program at The University of Texas at El Paso.</p>
<p>Enter David Martinez and Maria Rodriguez, the same EMBA students who transformed vague marketing reports into statistical precision and converted “pretty good” probability estimates into quantified risks. But this time, the challenge is different. The calculations are correct. The errors are subtle. And the consequences of misinterpreting the results could cost lives.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>The Cost of Statistical Overconfidence
</div>
</div>
<div class="callout-body-container callout-body">
<p>When TechFlow said “around $767,000,” they couldn’t set budgets. That’s expensive.</p>
<p>When PrecisionCast said “tests are pretty good,” they risked shipping defective parts. That’s catastrophic.</p>
<p>When BorderMed says “proves the drug works” and “no significant risk,” they might:</p>
<ul>
<li>Commit $500M to a Phase III trial based on overconfident Phase II conclusions<br>
</li>
<li>Miss real safety signals by misinterpreting “failure to reject”<br>
</li>
<li>Harm patients by rushing an inadequately tested drug to market<br>
</li>
<li>Waste resources on a drug whose true effect might be smaller than estimated</li>
</ul>
<p>In clinical trials, improper statistical inference doesn’t just cost money. It costs lives.</p>
<p><strong>The fix</strong>: Acknowledge uncertainty. Report confidence intervals. Interpret hypothesis tests correctly. Understand Type I and Type II errors. Communicate what the data actually say, not what we wish they said.</p>
</div>
</div>
<p>This chapter is about that transformation. From point estimates to interval estimates. From “proves” to “provides evidence.” From treating sample statistics as truth to acknowledging uncertainty. From overconfidence to appropriate confidence.</p>
<p>Welcome to statistical inference. The art and science of learning about populations from samples—honestly.</p>
</section>
<section id="connecting-the-journey-from-description-to-inference" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="connecting-the-journey-from-description-to-inference"><span class="header-section-number">4.2</span> Connecting the Journey: From Description to Inference</h2>
<p>David and Maria sit in a conference room at BorderMed’s El Paso facility, reviewing the clinical trial report. It’s been six months since they started their EMBA program, and their statistical journey has followed a clear progression.</p>
<p>“Remember January?” Maria says, pulling up their TechFlow analysis. “Sarah Chen asked us: ‘What happened in Q4?’ We calculated means, medians, standard deviations. Everything was about describing the past.”</p>
<p>David nods. “TechFlow’s mean monthly revenue: $766,667. Product D z-score: -1.21. Those were <strong>descriptive statistics</strong>, precise measurements of what actually occurred in that specific dataset.”</p>
<p>“Then April,” Maria continues, opening the PrecisionCast report. “Robert Martinez asked: ‘What will happen next quarter?’ We moved from description to prediction. P(Defect) = 0.0203. Expected defects = 1,117. We used <strong>probability</strong> to look forward.”</p>
<p>“But now,” David says, tapping the BorderMed report, “Dr.&nbsp;Walsh is asking something different. She’s not asking what happened in the trial or what will happen next. She’s asking: ‘What can we <strong>conclude with confidence</strong> about this drug? How <strong>certain</strong> can we be? What does this sample of 85 patients tell us about the <strong>millions</strong> of future patients who might take this drug?’”</p>
<p>Maria leans forward. “That’s <strong>statistical inference</strong>. Moving from sample to population. From 85 patients to the entire hypertensive population. From what we observed to what we can conclude.”</p>
<p>“And that’s where this report goes off the rails,” David adds. “Look at this line: ‘This 12.4 mmHg reduction represents the <strong>true efficacy</strong> of the drug.’ They’re treating a sample statistic as if it’s a population parameter.”</p>
<section id="the-three-questions-of-statistics" class="level3">
<h3 class="anchored" data-anchor-id="the-three-questions-of-statistics">The Three Questions of Statistics</h3>
<p>Maria opens her laptop and creates a quick comparison:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 16%">
<col style="width: 31%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Lecture</strong></th>
<th style="text-align: left;"><strong>Company</strong></th>
<th style="text-align: left;"><strong>Question</strong></th>
<th style="text-align: left;"><strong>Statistical Approach</strong></th>
<th style="text-align: left;"><strong>Key Concept</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Lecture 1</td>
<td style="text-align: left;">TechFlow</td>
<td style="text-align: left;">“What happened in Q4?”</td>
<td style="text-align: left;">Descriptive Statistics</td>
<td style="text-align: left;">Mean, SD, z-scores describe the sample</td>
</tr>
<tr class="even">
<td style="text-align: left;">Lecture 2</td>
<td style="text-align: left;">PrecisionCast</td>
<td style="text-align: left;">“What will happen in Q2?”</td>
<td style="text-align: left;">Probability</td>
<td style="text-align: left;">P(Event), E(X) predict the future</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Lecture 3</td>
<td style="text-align: left;">BorderMed</td>
<td style="text-align: left;">“What can we conclude?”</td>
<td style="text-align: left;">Statistical Inference</td>
<td style="text-align: left;">Confidence intervals, hypothesis tests acknowledge uncertainty</td>
</tr>
</tbody>
</table>
<p>“Three different questions, three different statistical toolkits,” David observes. “But they build on each other. We can’t do inference without understanding variability from Lecture 1. We can’t do inference without probability distributions from Lecture 2.”</p>
<p>“And we can’t do Phase III planning without proper inference,” Maria adds. “Let’s show them how.”</p>
</section>
</section>
<section id="the-first-error-confusing-statistics-with-parameters" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="the-first-error-confusing-statistics-with-parameters"><span class="header-section-number">4.3</span> The First Error: Confusing Statistics with Parameters</h2>
<p>David opens the report to the executive summary and highlights the problematic statement.</p>
<p>“Look at this,” he says. “‘VasoRelief reduced systolic blood pressure by 12.4 mmHg on average. This 12.4 mmHg reduction <strong>represents the true efficacy</strong> of the drug.’”</p>
<p>Maria frowns. “What’s wrong with that? They measured the reduction. It was 12.4 mmHg.”</p>
<p>“In their <strong>sample</strong> of 85 patients, yes,” David explains. “But ‘<strong>true efficacy</strong>’ implies this is the exact effect for the <strong>entire population</strong>, every future patient who might take this drug. That’s the difference between a sample statistic and a population parameter.” The populatin parameteris the true number. Because we do not know this, we must to statistical analysis to produce an estimate, or guess, of what the true value might be.</p>
<p>He sketches on the whiteboard:</p>
<pre><code>Sample Statistic vs. Population Parameter

Sample (n = 85):                    Population (all future patients):
x̄ = 12.4 mmHg                       μ = ???
(what we observed)                  (true efficacy - unknown!)

The sample statistic ESTIMATES the population parameter.
But they're NOT the same thing!</code></pre>
<section id="why-this-distinction-matters" class="level3">
<h3 class="anchored" data-anchor-id="why-this-distinction-matters">Why This Distinction Matters</h3>
<p>“Think about it this way,” Maria says, understanding dawning. “If we tested a different random sample of 85 hypertensive patients, would we get <em>exactly</em> 12.4 mmHg again?”</p>
<p>“Almost certainly not,” David responds. “We might get 13.1 mmHg. Or 11.8 mmHg. Or 12.9 mmHg. That’s <strong>sampling variability</strong>. Every sample will give us a slightly different result, even if they’re all drawn from the same population.”</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Definition: Sampling Distributions
</div>
</div>
<div class="callout-body-container callout-body">
<p>When we repeatedly draw samples from a population and calculate a statistic (like the mean), those statistics form a <strong>sampling distribution</strong>.</p>
<p><strong>Key Insight</strong>: The sample mean <span class="math inline">\(\bar{x}\)</span> is itself a random variable. Different samples produce different sample means.</p>
<p><strong>Standard Error</strong>: The standard deviation of the sampling distribution. <span class="math display">\[SE = \frac{s}{\sqrt{n}}\]</span></p>
<p>For BorderMed’s trial: <span class="math inline">\(SE = \frac{8.6}{\sqrt{85}} = 0.93\)</span> mmHg</p>
<p>This tells us how much sample means typically vary from sample to sample.</p>
</div>
</div>
<p>“So when BorderMed says ‘12.4 mmHg represents the true efficacy,’” Maria continues, “they’re ignoring the fact that 12.4 is just <strong>one possible outcome</strong> from one sample. Other samples would give different results.”</p>
<p>“Exactly,” David confirms. “The <strong>true efficacy</strong> (the population mean μ) is some fixed number we don’t know. Our sample gave us 12.4 mmHg, which is our <strong>best estimate</strong>, but we need to acknowledge the uncertainty.”</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>The Danger of Treating Estimates as Truth
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>What BorderMed’s report implies:</strong></p>
<ul>
<li>We know <em>exactly</em> that VasoRelief reduces BP by 12.4 mmHg</li>
<li>This is the <em>true</em> effect for all patients</li>
<li>No uncertainty exists</li>
</ul>
<p><strong>The reality:</strong></p>
<ul>
<li>We <em>observed</em> 12.4 mmHg in <em>one sample</em> of 85 patients</li>
<li>The true population mean could be anywhere from ~10 to ~14 mmHg</li>
<li>Substantial uncertainty exists</li>
</ul>
<p><strong>Business consequence:</strong> If you plan Phase III dosing, sample size, and marketing claims assuming <em>exactly</em> 12.4 mmHg, you’re building on false precision.</p>
</div>
</div>
</section>
</section>
<section id="the-second-error-missing-confidence-intervals" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="the-second-error-missing-confidence-intervals"><span class="header-section-number">4.4</span> The Second Error: Missing Confidence Intervals</h2>
<p>“The bigger problem,” David continues, “is that nowhere in this entire report do they provide confidence intervals.”</p>
<p>He flips through the pages. “They give us the sample mean: 12.4 mmHg. They give us the standard deviation: 8.6 mmHg. They give us the sample size: 85. But they never calculate or report confidence intervals.”</p>
<p>“Why does that matter?” Maria asks.</p>
<p>“Because a confidence interval <strong>quantifies</strong> our uncertainty,” David explains. “It tells us: based on this sample, here’s a range of plausible values for the true population mean.”</p>
<section id="calculating-the-confidence-interval" class="level3">
<h3 class="anchored" data-anchor-id="calculating-the-confidence-interval">Calculating the Confidence Interval</h3>
<p>David pulls out his calculator. “Let’s fix their first error. They should be reporting:</p>
<p><strong>Sample Results:</strong></p>
<ul>
<li>Sample mean: <span class="math inline">\(\bar{x} = 12.4\)</span> mmHg<br>
</li>
<li>Sample standard deviation: <span class="math inline">\(s = 8.6\)</span> mmHg<br>
</li>
<li>Sample size: <span class="math inline">\(n = 85\)</span></li>
</ul>
<p><strong>Standard Error:</strong> <span class="math display">\[SE = \frac{s}{\sqrt{n}} = \frac{8.6}{\sqrt{85}} = 0.93 \text{ mmHg}\]</span></p>
<p><strong>95% Confidence Interval:</strong></p>
<p>For <span class="math inline">\(n = 85\)</span>, we use the t-distribution with <span class="math inline">\(df = 84\)</span>.</p>
<p>Critical value: <span class="math inline">\(t_{0.025, 84} \approx 1.99\)</span></p>
<p><span class="math display">\[\text{Margin of Error} = t \times SE = 1.99 \times 0.93 = 1.85 \text{ mmHg}\]</span></p>
<p><span class="math display">\[\text{95% CI} = 12.4 \pm 1.85 = (10.55, 14.25) \text{ mmHg}\]</span></p>
<p>Maria pauses. “Wait, you said ‘t-distribution.’ I remember from Lecture 2 we used the normal distribution with z-scores. Why are we using t instead of z now?”</p>
<p>“Great question,” David responds. “Remember when we calculated z = 1.96 for 95% confidence with the normal distribution? That was based on knowing the population standard deviation σ.”</p>
<p>He writes on the whiteboard:</p>
<pre><code>Normal (Z) vs. t-Distribution

Use NORMAL (Z):                Use t-DISTRIBUTION:
✓ Population SD (σ) known      ✓ Population SD (σ) unknown
✓ OR large sample (n ≥ 30)     ✓ Use sample SD (s) instead
                                ✓ Especially when n &lt; 30

BorderMed situation:
• We DON'T know population σ
• We only have sample s = 8.6
• n = 85 (could use z, but t is more accurate)
• Therefore: use t-distribution</code></pre>
<p>“In real business situations,” David explains, “we almost never know the population standard deviation. We only have our sample. So we estimate σ with s, but that introduces additional uncertainty.”</p>
<p>“The t-distribution accounts for that extra uncertainty,” Maria realizes.</p>
<p>“Exactly. The t-distribution is wider than the normal distribution, it has fatter tails. This gives us wider confidence intervals, which is appropriate when we’re estimating the standard deviation from the sample.”</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>The t-Distribution: When Uncertainty About Uncertainty Matters
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Why t instead of z?</strong></p>
<p>When we don’t know the population standard deviation σ, we:</p>
<ol type="1">
<li>Estimate it with sample standard deviation s<br>
</li>
<li>This adds uncertainty (we’re uncertain about the uncertainty!)<br>
</li>
<li>The t-distribution accounts for this extra uncertainty</li>
</ol>
<p><strong>Key differences from normal distribution:</strong></p>
<ul>
<li><strong>Fatter tails</strong>: More probability in the extremes<br>
</li>
<li><strong>Wider intervals</strong>: More conservative (appropriately so)<br>
</li>
<li><strong>Depends on degrees of freedom</strong>: df = n - 1<br>
</li>
<li><strong>Approaches normal as n increases</strong>: With large samples, t ≈ z</li>
</ul>
<p><strong>Degrees of freedom (df)</strong>: Number of independent pieces of information used to estimate the standard deviation. For one sample: df = n - 1.</p>
<p><strong>When sample size increases:</strong></p>
<ul>
<li>Small n: t-distribution much wider than normal<br>
</li>
<li>Large n (≥30): t-distribution very similar to normal<br>
</li>
<li>As n → ∞: t-distribution → normal distribution</li>
</ul>
<p><strong>Example (95% confidence):</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Sample Size</th>
<th style="text-align: left;">df</th>
<th style="text-align: left;">t-critical</th>
<th style="text-align: left;">z-critical</th>
<th style="text-align: left;">Difference</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">n = 5</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">2.776</td>
<td style="text-align: left;">1.96</td>
<td style="text-align: left;">+42% wider</td>
</tr>
<tr class="even">
<td style="text-align: left;">n = 15</td>
<td style="text-align: left;">14</td>
<td style="text-align: left;">2.145</td>
<td style="text-align: left;">1.96</td>
<td style="text-align: left;">+9% wider</td>
</tr>
<tr class="odd">
<td style="text-align: left;">n = 30</td>
<td style="text-align: left;">29</td>
<td style="text-align: left;">2.045</td>
<td style="text-align: left;">1.96</td>
<td style="text-align: left;">+4% wider</td>
</tr>
<tr class="even">
<td style="text-align: left;">n = 85</td>
<td style="text-align: left;">84</td>
<td style="text-align: left;">1.989</td>
<td style="text-align: left;">1.96</td>
<td style="text-align: left;">+1.5% wider</td>
</tr>
<tr class="odd">
<td style="text-align: left;">n = 1000</td>
<td style="text-align: left;">999</td>
<td style="text-align: left;">1.962</td>
<td style="text-align: left;">1.96</td>
<td style="text-align: left;">+0.1% wider</td>
</tr>
</tbody>
</table>
<p><strong>Excel</strong>:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="an">t-critical value:</span><span class="co"> =T.INV.2T(alpha, df)</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="an">z-critical value:</span><span class="co"> =NORM.S.INV(1-alpha/2)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
<p>“So for BorderMed with n = 85,” Maria works through it, “we use <span class="math inline">\(t_{0.025, 84} = 1.99\)</span> instead of <span class="math inline">\(z_{0.025} = 1.96\)</span>. The difference is small because our sample is reasonably large.”</p>
<p>“Right,” David confirms. “If they’d only had n = 15 patients, the t-critical value would be about 2.14, noticeably larger. The smaller the sample, the more the t-distribution penalizes us for not knowing σ.”</p>
<p>“This is actually a safety feature,” Maria observes. “When we have less data, the t-distribution forces us to be more conservative by giving wider confidence intervals.”</p>
<p>“Exactly. It’s statistics being appropriately humble about what we can conclude from limited data.”</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Definition: Confidence Interval
</div>
</div>
<div class="callout-body-container callout-body">
<p>A <strong>95% confidence interval</strong> for the population mean <span class="math inline">\(\mu\)</span> is: <span class="math display">\[\bar{x} \pm t_{\alpha/2, n-1} \times \frac{s}{\sqrt{n}}\]</span></p>
<p><strong>What it means:</strong></p>
<p>If we were to repeat this study many times, approximately 95% of the confidence intervals we calculate would contain the true population mean.</p>
<p><strong>What it does NOT mean:</strong></p>
<ul>
<li>“There’s a 95% probability μ is in this interval” (μ is fixed, not random!)<br>
</li>
<li>“95% of patients will have reductions in this range” (this is about the mean, not individuals!)</li>
</ul>
<p><strong>Excel:</strong></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>=CONFIDENCE.T(0.05, standard_dev, sample_size)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Returns the margin of error. Add/subtract from sample mean.</p>
</div>
</div>
<p>“So the correct statement would be?” Maria prompts.</p>
<p>David writes it out:</p>
<blockquote class="blockquote">
<p>“In our sample of 85 patients, we observed a mean blood pressure reduction of 12.4 mmHg (SD = 8.6). Based on this sample, we estimate that the true population mean reduction lies between <strong>10.6 and 14.2 mmHg</strong> (95% confidence interval). We are 95% confident that this interval contains the true population mean effect of VasoRelief.”</p>
</blockquote>
<p>“That’s <em>completely different</em> from saying ‘12.4 mmHg represents the true efficacy,’” Maria observes.</p>
</section>
<section id="why-confidence-intervals-matter-for-business-decisions" class="level3">
<h3 class="anchored" data-anchor-id="why-confidence-intervals-matter-for-business-decisions">Why Confidence Intervals Matter for Business Decisions</h3>
<p>“Look at what the confidence interval tells us,” David points to his calculation. “The <strong>lower bound</strong> is 10.6 mmHg. That’s still above the FDA’s 10 mmHg threshold for clinical significance. That’s good news.”</p>
<p>“But the <strong>upper bound</strong> is 14.2 mmHg,” Maria notes. “So the true effect could be as high as 14.2 or as low as 10.6. That’s a range of 3.6 mmHg.”</p>
<p>“Right. And that uncertainty matters for Phase III planning,” David explains. “If they design Phase III assuming the effect is exactly 12.4 mmHg, but it’s actually closer to 10.6 mmHg, their sample size calculations will be wrong.”</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Business Application: Confidence Intervals in Action
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Scenario 1: Narrow CI (high precision)</strong></p>
<ul>
<li>95% CI: (12.0, 12.8) mmHg<br>
</li>
<li>Range: 0.8 mmHg<br>
</li>
<li>Interpretation: Very precise estimate. High confidence about effect size.<br>
</li>
<li>Decision: Can design Phase III with confidence.</li>
</ul>
<p><strong>Scenario 2: Wide CI (low precision)</strong></p>
<ul>
<li>95% CI: (8.5, 16.3) mmHg<br>
</li>
<li>Range: 7.8 mmHg<br>
</li>
<li>Interpretation: Imprecise estimate. Effect could be weak or strong.<br>
</li>
<li>Decision: Need larger Phase II or acknowledge major uncertainty in Phase III planning.</li>
</ul>
<p><strong>BorderMed’s Actual CI: (10.6, 14.2) mmHg</strong></p>
<ul>
<li>Range: 3.6 mmHg<br>
</li>
<li>Interpretation: Moderate precision. Effect likely clinically significant, but considerable uncertainty about exact magnitude.<br>
</li>
<li>Decision: Proceed to Phase III but design for conservative estimate (~10-11 mmHg).</li>
</ul>
</div>
</div>
</section>
</section>
<section id="the-third-error-misinterpreting-p-values" class="level2" data-number="4.5">
<h2 data-number="4.5" class="anchored" data-anchor-id="the-third-error-misinterpreting-p-values"><span class="header-section-number">4.5</span> The Third Error: Misinterpreting P-Values</h2>
<p>Maria flips to the hypothesis testing section of the report and reads aloud:</p>
<blockquote class="blockquote">
<p>“The <em>p</em>-value less than 0.001 <strong>proves</strong> that VasoRelief causes blood pressure reduction. This means there is less than 0.1% probability that the <strong>drug is ineffective</strong>. We can say with <strong>over 99.9% certainty</strong> that VasoRelief works.”</p>
</blockquote>
<p>She looks up. “This sounds impressive. What’s wrong with it?”</p>
<p>David sighs. “Almost everything. This is one of the most common statistical misinterpretations in all of science. Let’s break down what’s wrong.”</p>
<section id="what-p-values-actually-mean" class="level3">
<h3 class="anchored" data-anchor-id="what-p-values-actually-mean">What P-Values Actually Mean</h3>
<p>“A <em>p</em>-value is the probability of observing data this extreme <strong>if the null hypothesis were true</strong>,” David explains. “It’s P(data|H₀), not P(H₀|data).”</p>
<p>He writes on the whiteboard:</p>
<pre><code>BorderMed's Hypothesis Test:

* H₀: μ = 0 (drug has no effect)
* Hₐ: μ &gt; 0 (drug reduces blood pressure)

Test statistic: t = 13.29
p-value &lt; 0.001

CORRECT interpretation:
"If the drug had NO effect (H₀ true), there's &lt; 0.1% chance we'd observe 
a mean reduction of 12.4 mmHg or more just by random chance."

INCORRECT interpretation (what BorderMed wrote):
"There's &lt; 0.1% probability the drug is ineffective."
"We can say with 99.9% certainty the drug works."</code></pre>
<p>“See the difference?” David asks. “The p-value tells us P(seeing 12.4 mmHg | drug doesn’t work). But BorderMed is claiming it tells us P(drug doesn’t work | seeing 12.4 mmHg). Those are <em>completely different</em> probabilities.”</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Definition: P-Value
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Formal definition</strong>: The p-value is the probability of obtaining test results at least as extreme as the observed results, <strong>assuming the null hypothesis is true</strong>.</p>
<p><strong>What it measures</strong>: How surprising our data would be if H₀ were true.</p>
<p><strong>What it is NOT</strong>:</p>
<ul>
<li>❌ The probability that H₀ is true<br>
</li>
<li>❌ The probability that the treatment doesn’t work<br>
</li>
<li>❌ The probability we made a mistake<br>
</li>
<li>❌ One minus the probability that Hₐ is true</li>
</ul>
<p><strong>What it IS</strong>:</p>
<ul>
<li>✅ The probability of seeing data this extreme if H₀ is true<br>
</li>
<li>✅ A measure of compatibility between data and H₀<br>
</li>
<li>✅ Evidence against H₀ (smaller p-value = stronger evidence)</li>
</ul>
<p><strong>Rule of thumb</strong>: Small <em>p</em>-value = data would be very surprising if H₀ were true = evidence against H₀</p>
</div>
</div>
</section>
<section id="the-prosecutors-fallacy" class="level3">
<h3 class="anchored" data-anchor-id="the-prosecutors-fallacy">The “Prosecutor’s Fallacy”</h3>
<p>Maria thinks for a moment. “So it’s like… if you found a defendant’s fingerprint at a crime scene, you might say ‘If this person is innocent, the probability of finding their fingerprint here is very low.’ But you can’t flip it around and say ‘Therefore, there’s a low probability this person is innocent.’”</p>
<p>“Exactly!” David lights up. “That’s called the ‘prosecutor’s fallacy’ in law. It’s the same logical error. P(evidence | innocence) ≠ P(innocence | evidence).”</p>
<p>“So what <em>should</em> BorderMed say?” Maria asks.</p>
<p>David writes out the correct interpretation:</p>
<blockquote class="blockquote">
<p>“We obtained p &lt; 0.001, indicating that if VasoRelief had no effect on blood pressure, results this extreme would occur less than 0.1% of the time by chance alone. This provides <strong>strong evidence against</strong> the null hypothesis and <strong>supports the conclusion</strong> that VasoRelief reduces blood pressure. However, we acknowledge that with α = 0.05, there remains a 5% chance of Type I error (false positive).”</p>
</blockquote>
<p>“Notice what we <em>don’t</em> say,” David points out. “We don’t say ‘proves.’ We don’t claim to know the probability the drug works. We don’t claim 99.9% certainty. We simply say the data provide strong evidence against the null hypothesis.”</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Common P-Value Misinterpretations
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>What the report said</strong> ❌<br>
“p &lt; 0.001 proves the drug works with 99.9% certainty”</p>
<p><strong>Why it’s wrong</strong>:</p>
<ul>
<li>“Proves” is too strong—statistics provides evidence, not proof<br>
</li>
<li>P-values don’t give probability hypotheses are true<br>
</li>
<li>Confuses P(data|H₀) with P(H₀|data)</li>
</ul>
<p><strong>Correct interpretation</strong> ✅<br>
“p &lt; 0.001 provides strong evidence against H₀, supporting the conclusion that VasoRelief reduces blood pressure”</p>
<p><strong>Business impact</strong>:</p>
<p>Overstating certainty leads to:<br>
- Overconfident investment decisions<br>
- Inadequate contingency planning<br>
- Surprise when Phase III results differ from Phase II<br>
- FDA skepticism of exaggerated claims</p>
</div>
</div>
</section>
</section>
<section id="the-fourth-error-accepting-the-null-hypothesis" class="level2" data-number="4.6">
<h2 data-number="4.6" class="anchored" data-anchor-id="the-fourth-error-accepting-the-null-hypothesis"><span class="header-section-number">4.6</span> The Fourth Error: “Accepting” the Null Hypothesis</h2>
<p>David flips to the safety analysis section. “Here’s another critical error. Look at this headache rate analysis.”</p>
<p>He reads: “‘We fail to reject the null hypothesis (p = 0.10 &gt; 0.05). This means we <strong>accept</strong> that VasoRelief’s headache rate is the same as placebo. There is <strong>no significant headache risk</strong>.’”</p>
<p>Maria’s eyes widen. “That’s a safety endpoint. They’re saying there’s no risk?”</p>
<p>“Based on failing to find statistical significance,” David confirms. “This is dangerous. They’re confusing ‘absence of evidence’ with ‘evidence of absence.’”</p>
<section id="the-asymmetry-of-hypothesis-testing" class="level3">
<h3 class="anchored" data-anchor-id="the-asymmetry-of-hypothesis-testing">The Asymmetry of Hypothesis Testing</h3>
<p>“In hypothesis testing, there’s an asymmetry,” David explains, drawing a diagram:</p>
<pre><code>Hypothesis Test Outcomes:

Small p-value (p &lt; α):
→ Reject H₀
→ "Strong evidence against H₀"
→ "Data support Hₐ"

Large p-value (p ≥ α):
→ Fail to reject H₀  
→ "Insufficient evidence against H₀"
→ "Cannot conclude Hₐ"
→ ≠ "Accept H₀"
→ ≠ "H₀ is true"
</code></pre>
<p>“When p &gt; α, we have two possible explanations,” he continues:</p>
<ul>
<li>“<strong>Explanation 1</strong>: H₀ is actually true (no difference exists)<br>
</li>
<li><strong>Explanation 2</strong>: H₀ is false, but our sample was too small to detect the difference (Type II error)</li>
</ul>
<p>We can’t distinguish between these! That’s why we say ‘fail to reject’ not ‘accept.’”</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Definition: Fail to Reject vs.&nbsp;Accept
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>“Fail to reject H₀”</strong> (correct):</p>
<ul>
<li>Insufficient evidence to conclude a difference exists<br>
</li>
<li>Could be because: (a) no difference exists, or (b) sample too small<br>
</li>
<li>Acknowledges uncertainty<br>
</li>
<li>Leaves question open</li>
</ul>
<p><strong>“Accept H₀”</strong> (incorrect):</p>
<ul>
<li>Implies we’ve proven no difference exists<br>
</li>
<li>Ignores possibility of Type II error<br>
</li>
<li>Overstates what the data show<br>
</li>
<li>Closes question inappropriately</li>
</ul>
<p><strong>Legal analogy</strong>:</p>
<ul>
<li>“Not guilty” ≠ “innocent”<br>
</li>
<li>Insufficient evidence to convict ≠ proof of innocence<br>
</li>
<li>Fail to reject H₀ ≠ accept H₀</li>
</ul>
</div>
</div>
</section>
<section id="the-specific-problem-with-bordermeds-safety-analysis" class="level3">
<h3 class="anchored" data-anchor-id="the-specific-problem-with-bordermeds-safety-analysis">The Specific Problem with BorderMed’s Safety Analysis</h3>
<p>“Let’s look at their actual numbers,” Maria says, pulling up the data.</p>
<p>“They tested whether the headache rate (27.1%) differs from placebo (20%).”</p>
<p>David calculates: “With n = 85 and observed rate of 27.1%, they got z = 1.64 and p = 0.10.”</p>
<p>“Since p = 0.10 &gt; α = 0.05, they failed to reject H₀,” Maria continues. “But then they concluded: ‘VasoRelief’s headache rate is the same as placebo. No significant headache risk.’”</p>
<p>“That’s exactly backward,” David says firmly. “Look at the numbers. The observed rate was 27.1%. The placebo rate was 20%. That’s 7.1 percentage points higher. That’s not ‘no risk’, that’s a 35% increase!”</p>
<p>He writes out what they should have said:</p>
<blockquote class="blockquote">
<p>“We failed to reject the null hypothesis (p = 0.10). This indicates <strong>insufficient statistical evidence</strong> to conclude the headache rate differs from placebo. However, the observed rate was <strong>numerically higher</strong> (27.1% vs 20%, a 7.1 percentage point or 35% relative increase). Our failure to detect a significant difference may reflect <strong>insufficient sample size</strong> (Type II error) rather than true equivalence. This potential safety signal requires careful monitoring in Phase III trials with adequate statistical power.”</p>
</blockquote>
<p>“See the difference?” David asks. “Instead of claiming ‘no risk,’ we acknowledge the numerical difference, consider Type II error, and recommend further investigation.”</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>The Danger of “Accepting” H₀ for Safety Endpoints
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Why this error is especially dangerous in safety analysis:</strong></p>
<p><strong>Efficacy (benefits)</strong>:</p>
<ul>
<li>If you miss a real effect (Type II error), you might abandon a useful drug<br>
</li>
<li>Consequence: Lost opportunity, but no harm to patients</li>
</ul>
<p><strong>Safety (risks)</strong>:</p>
<ul>
<li>If you miss a real adverse event (Type II error), you might expose patients to harm<br>
</li>
<li>Consequence: Patient injuries or deaths</li>
</ul>
<p><strong>BorderMed’s error</strong>: Claiming “no headache risk” when they actually have:</p>
<ul>
<li>Observed rate 35% higher than placebo<br>
</li>
<li>Inadequate sample size (n=85) to detect moderate increases<br>
</li>
<li>Only ~50% power to detect a 7% difference</li>
</ul>
<p><strong>Correct approach</strong>:</p>
<ul>
<li>Acknowledge insufficient evidence<br>
</li>
<li>Note numerical increase<br>
</li>
<li>Highlight Type II error risk<br>
</li>
<li>Call for larger safety studies</li>
</ul>
</div>
</div>
</section>
</section>
<section id="the-fifth-error-ignoring-type-i-and-type-ii-errors" class="level2" data-number="4.7">
<h2 data-number="4.7" class="anchored" data-anchor-id="the-fifth-error-ignoring-type-i-and-type-ii-errors"><span class="header-section-number">4.7</span> The Fifth Error: Ignoring Type I and Type II Errors</h2>
<p>“One thing completely missing from this report,” Maria observes, “is any discussion of Type I and Type II errors.”</p>
<p>David nods. “They set α = 0.05 for their hypothesis tests, but never explain what that means. And they never consider the risk of Type II errors, especially for their safety endpoints.”</p>
<section id="type-i-error-the-false-positive" class="level3">
<h3 class="anchored" data-anchor-id="type-i-error-the-false-positive">Type I Error: The False Positive</h3>
<p>“Type I error is rejecting H₀ when it’s actually true,” David explains. “In BorderMed’s efficacy test, that would mean concluding the drug works when it actually doesn’t.”</p>
<p>He draws a table:</p>
<pre><code>Type I Error (α = 0.05)

Reality: H₀ is true (drug has no effect)
Our decision: Reject H₀ (conclude drug works)
Consequence: FALSE POSITIVE

By setting α = 0.05, BorderMed accepts a 5% chance of this error.

Business impact:
- Invest $500M in Phase III for ineffective drug
- Waste resources, time, and potentially harm patients
- Regulatory rejection after costly trials</code></pre>
<p>“The good news,” Maria says, “is that their p &lt; 0.001 is much smaller than α = 0.05. So the risk of Type I error for efficacy is low.”</p>
<p>“True,” David agrees. “With such a small <em>p</em>-value and a confidence interval that doesn’t include zero, we can be reasonably confident the drug has some effect. The question is whether that effect is large enough to matter clinically.”</p>
</section>
<section id="type-ii-error-the-false-negative" class="level3">
<h3 class="anchored" data-anchor-id="type-ii-error-the-false-negative">Type II Error: The False Negative</h3>
<p>“Type II error is <em>failing</em> to reject H₀ when it’s actually false,” David continues. “This is what we’re worried about for the headache analysis.”</p>
<pre><code>Type II Error (β)

Reality: Hₐ is true (drug does increase headaches)
Our decision: Fail to reject H₀ (insufficient evidence)
Consequence: FALSE NEGATIVE

Probability of Type II error: β
Power = 1 - β (probability of correctly detecting a real effect)

BorderMed's headache test:
- Observed: 27.1% vs 20% (7.1 percentage point difference)
- p = 0.10 (not significant)
- With n = 85, power ≈ 50% to detect this size difference
- β ≈ 50% (50% chance of missing a real 7% increase!)</code></pre>
<p>“So there’s a coin flip’s chance they’re missing a real safety problem?” Maria asks, concerned.</p>
<p>“Exactly,” David confirms. “That’s why their conclusion ‘no significant headache risk’ is so problematic. They had insufficient power to detect moderate increases in adverse events.”</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Definition: Type I and Type II Errors
</div>
</div>
<div class="callout-body-container callout-body">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: center;"><strong>H₀ is TRUE</strong></th>
<th style="text-align: center;"><strong>Hₐ is TRUE</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Reject H₀</strong></td>
<td style="text-align: center;">Type I Error (α)</td>
<td style="text-align: center;">✓ Correct</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Fail to reject H₀</strong></td>
<td style="text-align: center;">✓ Correct</td>
<td style="text-align: center;">Type II Error (β)</td>
</tr>
</tbody>
</table>
<p><strong>Type I Error (α)</strong>:</p>
<ul>
<li>Reject H₀ when it’s true (false positive)<br>
</li>
<li>Probability = α (we control this)<br>
</li>
<li>Common choice: α = 0.05 (5% risk)</li>
</ul>
<p><strong>Type II Error (β)</strong>:</p>
<ul>
<li>Fail to reject H₀ when it’s false (false negative)<br>
</li>
<li>Probability = β (depends on sample size, effect size, α)<br>
</li>
<li>Power = 1 - β (probability of detecting real effect)</li>
</ul>
<p><strong>Typical target</strong>: Power = 80% or 90% (β = 20% or 10%)</p>
</div>
</div>
</section>
<section id="calculating-power-and-sample-size" class="level3">
<h3 class="anchored" data-anchor-id="calculating-power-and-sample-size">Calculating Power and Sample Size</h3>
<p>“Let’s show them what proper power analysis looks like,” David suggests.</p>
<p>He pulls up Excel and demonstrates:</p>
<p>“For their headache analysis, they’re testing:<br>
- H₀: p = 0.20 (placebo rate)<br>
- Observed: p̂ = 0.271 (7.1 percentage point increase)<br>
- n = 85<br>
- α = 0.05</p>
<p>To calculate power to detect a 7.1 percentage point difference:</p>
<p><strong>Power ≈ 48%</strong></p>
<p>This means they have less than 50-50 odds of detecting this difference!”</p>
<p>“What sample size would they need for adequate power?” Maria asks.</p>
<p>David calculates: “For 80% power to detect a difference between 20% and 27.1%:</p>
<p><span class="math display">\[n = \frac{(z_{\alpha/2} + z_\beta)^2[p_1(1-p_1) + p_2(1-p_2)]}{(p_1 - p_2)^2}\]</span></p>
<p><span class="math display">\[n = \frac{(1.96 + 0.84)^2[0.20(0.80) + 0.271(0.729)]}{(0.071)^2} \approx 294\]</span></p>
<p>They’d need about <strong>300 patients per group</strong> to have adequate power for this safety endpoint.”</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>The Consequences of Low Power
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>BorderMed’s situation</strong>:</p>
<ul>
<li>Efficacy test: Very high power (&gt;99%), p &lt; 0.001 ✓<br>
</li>
<li>Safety test: Low power (~48%), p = 0.10 ⚠️</li>
</ul>
<p><strong>Problem</strong>:<br>
They can detect the benefit (BP reduction) but might miss the harm (increased headaches)</p>
<p><strong>Why this matters</strong>:</p>
<ul>
<li>Asymmetric risk: Missing a benefit ≠ Missing a harm<br>
</li>
<li>For patient safety, high power is crucial for adverse event detection<br>
</li>
<li>“Fail to reject” with low power provides false reassurance</li>
</ul>
<p><strong>Recommendation</strong>:<br>
Phase III must be powered for safety endpoints, not just efficacy. With n=600 total (300 per group), power to detect 7% difference &gt;90%.</p>
</div>
</div>
</section>
</section>
<section id="the-sixth-error-ignoring-small-sample-sizes" class="level2" data-number="4.8">
<h2 data-number="4.8" class="anchored" data-anchor-id="the-sixth-error-ignoring-small-sample-sizes"><span class="header-section-number">4.8</span> The Sixth Error: Ignoring Small Sample Sizes</h2>
<p>Maria scrolls through the site-specific analysis. “Look at this. Albuquerque site: n = 15 patients. They’re reporting the mean (9.2 mmHg) as if it’s just as reliable as El Paso’s mean (n = 42).”</p>
<p>David calculates the confidence intervals for each site:</p>
<p>“Let’s see the precision:</p>
<p><strong>El Paso (n = 42)</strong>:</p>
<ul>
<li>Mean: 13.8 mmHg<br>
</li>
<li>SE = 8.6/√42 = 1.33<br>
</li>
<li>95% CI = 13.8 ± 2.68 = (11.1, 16.5)<br>
</li>
<li>Width: 5.4 mmHg</li>
</ul>
<p><strong>Phoenix (n = 28)</strong>:</p>
<ul>
<li>Mean: 11.6 mmHg<br>
</li>
<li>SE = 8.6/√28 = 1.63<br>
</li>
<li>95% CI = 11.6 ± 3.28 = (8.3, 14.9)<br>
</li>
<li>Width: 6.6 mmHg</li>
</ul>
<p><strong>Albuquerque (n = 15)</strong>:</p>
<ul>
<li>Mean: 9.2 mmHg<br>
</li>
<li>SE = 8.6/√15 = 2.22<br>
</li>
<li>95% CI = 9.2 ± 4.74 = (4.5, 13.9)<br>
</li>
<li>Width: <strong>9.4 mmHg</strong> 🚨”</li>
</ul>
<p>“Look at that,” Maria exclaims. “The Albuquerque confidence interval is almost 10 mmHg wide! It could be anywhere from 4.5 to 13.9.”</p>
<p>“And it overlaps completely with the other sites,” David adds. “We can’t conclude anything meaningful about site differences with such imprecise estimates.”</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>The Effect of Sample Size on Precision
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Standard Error</strong>: <span class="math inline">\(SE = \frac{s}{\sqrt{n}}\)</span></p>
<p>As <span class="math inline">\(n\)</span> increases, SE decreases, giving narrower confidence intervals:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Sample Size</th>
<th style="text-align: left;">Standard Error</th>
<th style="text-align: left;">95% Margin of Error</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">n = 15</td>
<td style="text-align: left;">2.22</td>
<td style="text-align: left;">±4.74 mmHg</td>
</tr>
<tr class="even">
<td style="text-align: left;">n = 25</td>
<td style="text-align: left;">1.72</td>
<td style="text-align: left;">±3.67 mmHg</td>
</tr>
<tr class="odd">
<td style="text-align: left;">n = 50</td>
<td style="text-align: left;">1.22</td>
<td style="text-align: left;">±2.44 mmHg</td>
</tr>
<tr class="even">
<td style="text-align: left;">n = 85</td>
<td style="text-align: left;">0.93</td>
<td style="text-align: left;">±1.84 mmHg</td>
</tr>
<tr class="odd">
<td style="text-align: left;">n = 100</td>
<td style="text-align: left;">0.86</td>
<td style="text-align: left;">±1.72 mmHg</td>
</tr>
</tbody>
</table>
<p><strong>Key insight</strong>: Precision improves with square root of sample size. To cut margin of error in half, need 4× the sample size.</p>
<p><strong>Excel</strong>:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb9"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="an">Standard Error:</span><span class="co"> =STDEV.S(range)/SQRT(COUNT(range))</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="an">Margin of Error:</span><span class="co"> =CONFIDENCE.T(0.05, STDEV.S(range), COUNT(range))</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
<p>“The report should flag this,” Maria says. “They should warn readers that the Albuquerque results are imprecise and shouldn’t be over-interpreted.”</p>
<p>David writes out what should have been included:</p>
<blockquote class="blockquote">
<p>⚠️ <strong>CAUTION: Small Sample Size</strong></p>
<p>The Albuquerque site (n=15) provides an imprecise estimate due to small sample size. The wide confidence interval (4.5 to 13.9 mmHg, spanning 9.4 mmHg) overlaps substantially with the other sites, making it impossible to determine if the lower observed mean reflects true site differences or sampling variability. Conclusions about site-specific effects should not be drawn from this small subsample.</p>
</blockquote>
</section>
<section id="creating-the-corrected-report" class="level2" data-number="4.9">
<h2 data-number="4.9" class="anchored" data-anchor-id="creating-the-corrected-report"><span class="header-section-number">4.9</span> Creating the Corrected Report</h2>
<p>After identifying all the errors, David and Maria spend the next three days creating a properly written clinical trial report. They follow the template from Lectures 1 and 2: take the same data, apply proper statistical methods, and communicate the uncertainty honestly.</p>
<p>Their corrected report includes:</p>
<section id="proper-confidence-intervals" class="level3">
<h3 class="anchored" data-anchor-id="proper-confidence-intervals">Proper Confidence Intervals</h3>
<p>Instead of: “12.4 mmHg represents the true efficacy”</p>
<p>They write:</p>
<blockquote class="blockquote">
<p>“In our sample of 85 patients, we observed a mean blood pressure reduction of 12.4 mmHg (SD = 8.6). Based on this sample, we estimate that the true population mean reduction lies between <strong>10.6 and 14.2 mmHg</strong> (95% confidence interval). We are 95% confident that this interval contains the true population mean effect of VasoRelief.”</p>
</blockquote>
</section>
<section id="proper-p-value-interpretation" class="level3">
<h3 class="anchored" data-anchor-id="proper-p-value-interpretation">Proper P-Value Interpretation</h3>
<p>Instead of: “p &lt; 0.001 proves the drug works with 99.9% certainty”</p>
<p>They write:</p>
<blockquote class="blockquote">
<p>“We obtained p &lt; 0.001, indicating that if VasoRelief had no effect on blood pressure, results this extreme would occur less than 0.1% of the time by chance alone. This provides <strong>strong evidence against</strong> the null hypothesis and <strong>supports the conclusion</strong> that VasoRelief reduces blood pressure. However, we acknowledge that with α = 0.05, there remains a 5% chance of Type I error (false positive).”</p>
</blockquote>
</section>
<section id="proper-treatment-of-fail-to-reject" class="level3">
<h3 class="anchored" data-anchor-id="proper-treatment-of-fail-to-reject">Proper Treatment of “Fail to Reject”</h3>
<p>Instead of: “We accept that headache rates are the same. No significant headache risk.”</p>
<p>They write:</p>
<blockquote class="blockquote">
<p>“We failed to reject the null hypothesis (p = 0.10). This indicates <strong>insufficient statistical evidence</strong> to conclude the headache rate differs from placebo. However, the observed rate was <strong>numerically higher</strong> (27.1% vs 20%, a 35% relative increase). ⚠️ <strong>RISK OF TYPE II ERROR</strong>: With n=85, our statistical power to detect a 7 percentage point difference is approximately 50%. This means we had a 50% chance of failing to detect a real safety issue. <strong>Phase III trials should specifically monitor headache rates with adequate power</strong> (n≈300 per group) to definitively assess this potential safety signal.”</p>
</blockquote>
</section>
<section id="sample-size-justification" class="level3">
<h3 class="anchored" data-anchor-id="sample-size-justification">Sample Size Justification</h3>
<p>They add a proper <em>a priori</em> sample size calculation:</p>
<blockquote class="blockquote">
<p>“Sample size was calculated to detect a minimum clinically important difference of 10 mmHg with 90% power at α = 0.05, assuming SD = 8.0 mmHg:</p>
<p><span class="math display">\[n = \left[\frac{(z_{1-\alpha/2} + z_{1-\beta}) \times \sigma}{\delta}\right]^2 = \left[\frac{(1.96 + 1.28) \times 8.0}{10}\right]^2 = 67\]</span></p>
<p>We enrolled 85 patients to provide a safety margin above the minimum required sample size.”</p>
</blockquote>
</section>
<section id="a-comprehensive-limitations-section" class="level3">
<h3 class="anchored" data-anchor-id="a-comprehensive-limitations-section">A Comprehensive Limitations Section</h3>
<p>They add a section completely missing from the original:</p>
<blockquote class="blockquote">
<p><strong>Study Limitations</strong></p>
<p>Several important limitations should be considered:</p>
<ul>
<li><strong>Limited sample size</strong>: With n=85, our estimates have moderate precision (margin of error ±1.84 mmHg)</li>
<li><strong>Unbalanced site enrollment</strong>: Albuquerque site (n=15) provides imprecise estimates with wide confidence intervals</li>
<li><strong>Insufficient power for safety endpoints</strong>: With n=85, statistical power to detect moderate increases in adverse event rates is limited</li>
<li><strong>Phase II exploratory nature</strong>: This trial was designed to estimate effect sizes and inform Phase III design, not to provide definitive evidence of efficacy</li>
</ul>
</blockquote>
</section>
<section id="measured-recommendations" class="level3">
<h3 class="anchored" data-anchor-id="measured-recommendations">Measured Recommendations</h3>
<p>Instead of: “The drug demonstrates CLEAR EFFICACY… should proceed to Phase III”</p>
<p>They write:</p>
<blockquote class="blockquote">
<p>“Based on promising Phase II results (estimated 10.6-14.2 mmHg reduction with 95% confidence), we recommend Phase III trials to <strong>confirm</strong> efficacy in a larger, more diverse population. The Phase II results are <strong>encouraging but not definitive</strong>—they provide confidence intervals to guide Phase III design, not proof of effectiveness.”</p>
</blockquote>
</section>
</section>
<section id="the-board-presentation" class="level2" data-number="4.10">
<h2 data-number="4.10" class="anchored" data-anchor-id="the-board-presentation"><span class="header-section-number">4.10</span> The Board Presentation</h2>
<p>One week later, David and Maria present their corrected analysis to BorderMed’s board of directors.</p>
<p>Dr.&nbsp;Walsh introduces them. “David and Maria have reviewed our Phase II results with a critical statistical eye. Their findings are… illuminating.”</p>
<p>David opens his presentation. “The good news: your drug appears to work. The bad news: your original report dramatically overstated your certainty.”</p>
<p>He clicks to the comparison slide:</p>
<p><strong>Original Report Errors</strong>:</p>
<ol type="1">
<li>Treated sample statistic as population parameter (“true efficacy”)<br>
</li>
<li>No confidence intervals reported<br>
</li>
<li>Misinterpreted <em>p</em>-values (“proves,” “99.9% certainty”)<br>
</li>
<li>“Accepted” null hypothesis for safety endpoint<br>
</li>
<li>No discussion of Type I/II errors<br>
</li>
<li>Ignored small sample size issues</li>
</ol>
<p>Maria takes over. “Here’s what we can actually conclude with appropriate statistical confidence:</p>
<p><strong>Efficacy</strong>: Strong evidence of blood pressure reduction</p>
<ul>
<li>Sample mean: 12.4 mmHg<br>
</li>
<li><strong>95% CI: 10.6 to 14.2 mmHg</strong><br>
</li>
<li>Both bounds exceed FDA’s 10 mmHg threshold ✓<br>
</li>
<li>p &lt; 0.001 provides strong evidence against H₀</li>
</ul>
<p><strong>Response Rate</strong>: Promising but uncertain</p>
<ul>
<li>Sample: 68.2% achieved target BP<br>
</li>
<li><strong>95% CI: 58.3% to 78.1%</strong><br>
</li>
<li>Lower bound only modestly better than existing agents</li>
</ul>
<p><strong>Safety Concern</strong>: Insufficient evidence, not “no risk”</p>
<ul>
<li>Headache rate numerically higher (27.1% vs 20%)<br>
</li>
<li>Failed to reject H₀, but <strong>⚠️ 50% Type II error risk</strong><br>
</li>
<li>Phase III must be adequately powered for safety endpoints</li>
</ul>
<p><strong>Site Heterogeneity</strong>: Cannot assess with confidence</p>
<ul>
<li>Albuquerque (n=15): CI too wide for meaningful conclusions<br>
</li>
<li>All site CIs overlap substantially”</li>
</ul>
<p>One board member raises his hand. “So… should we proceed to Phase III or not?”</p>
<p>“Yes,” David answers. “But with eyes wide open about the uncertainty. Your Phase II suggests the drug works, but you need to:</p>
<ol type="1">
<li><strong>Design Phase III conservatively</strong>: Assume effect closer to lower bound (10-11 mmHg)</li>
<li><strong>Increase sample size</strong>: Target n=300 per group for adequate power on safety endpoints</li>
<li><strong>Pre-specify safety monitoring</strong>: Headache rates need definitive assessment</li>
<li><strong>Budget for uncertainty</strong>: The true effect could be anywhere in the 10.6-14.2 range”</li>
</ol>
<p>“The original report set you up to be overconfident,” Maria adds. “You might have committed $500M based on point estimates, only to discover Phase III results differ from your expectations. Our report gives you the <strong>range</strong> of plausible outcomes so you can plan appropriately.”</p>
<p>Dr.&nbsp;Walsh nods slowly. “This is exactly what we needed. The FDA would have torn apart our original report. Now we have honest uncertainty estimates we can defend.”</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Key Takeaways: Statistical Inference Done Right
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Always Report Confidence Intervals</strong>:</p>
<ul>
<li>Point estimates alone are insufficient<br>
</li>
<li>CIs quantify uncertainty and precision<br>
</li>
<li>Enable evidence-based planning</li>
</ul>
<p><strong>Interpret P-Values Correctly</strong>:</p>
<ul>
<li>P(data|H₀), not P(H₀|data)<br>
</li>
<li>“Evidence against” not “proof”<br>
</li>
<li>Never claim “proves” or “X% certain hypothesis is true”</li>
</ul>
<p><strong>Never “Accept” H₀</strong>:</p>
<ul>
<li>“Fail to reject” ≠ “Accept”<br>
</li>
<li>Consider Type II error risk<br>
</li>
<li>Especially critical for safety endpoints</li>
</ul>
<p><strong>Acknowledge Type I and Type II Errors</strong>:</p>
<ul>
<li>α = probability of false positive (you control)<br>
</li>
<li>β = probability of false negative (depends on n, effect size)<br>
</li>
<li>Asymmetric consequences: missing harms ≠ missing benefits</li>
</ul>
<p><strong>Respect Sample Size Limitations</strong>:</p>
<ul>
<li>Small samples → wide CIs → imprecise estimates<br>
</li>
<li>Calculate required n <em>before</em> study<br>
</li>
<li>Flag subgroups with inadequate precision</li>
</ul>
<p><strong>Communicate Uncertainty Honestly</strong>:</p>
<ul>
<li>Use ranges, not point estimates<br>
</li>
<li>Acknowledge limitations<br>
</li>
<li>Make recommendations that account for uncertainty</li>
</ul>
</div>
</div>
</section>
<section id="connecting-the-statistical-journey" class="level2" data-number="4.11">
<h2 data-number="4.11" class="anchored" data-anchor-id="connecting-the-statistical-journey"><span class="header-section-number">4.11</span> Connecting the Statistical Journey</h2>
<p>As they pack up after the presentation, Maria reflects on their six-month journey.</p>
<p>“January: TechFlow taught us to calculate precise statistics from data.”</p>
<p>“April: PrecisionCast taught us to use probability for prediction,” David adds.</p>
<p>“July: BorderMed taught us the hardest lesson, acknowledging what we <strong>don’t</strong> know.”</p>
<p>Maria nods. “Descriptive statistics describe the sample. Probability predicts the future. But statistical inference? That’s about honestly assessing what a sample can tell us about a population, and what it can’t.”</p>
<p>“And in some ways,” David observes, “this is the most important skill for business. Anyone can calculate a mean. But knowing when to say ‘we need more data’ or ‘our estimate is too imprecise’? That takes judgment informed by proper statistical inference.”</p>
<p>“Three companies, three questions, three statistical approaches,” Maria summarizes. “But they all lead to the same principle: <strong>be precise about what you know, and honest about what you don’t</strong>.”</p>
</section>
<section id="chapter-summary-from-samples-to-populations" class="level2" data-number="4.12">
<h2 data-number="4.12" class="anchored" data-anchor-id="chapter-summary-from-samples-to-populations"><span class="header-section-number">4.12</span> Chapter Summary: From Samples to Populations</h2>
<p>Seven days after Dr.&nbsp;Walsh’s initial request, David and Maria present their final corrected report. Gone are the phrases “true efficacy,” “proves,” and “accept the null hypothesis.”</p>
<p>In their place:</p>
<p><strong>Statistical Inference Done Right</strong>:</p>
<p><strong>Confidence Intervals</strong> (not just point estimates):</p>
<ul>
<li>Mean BP reduction: 12.4 mmHg, 95% CI (10.6, 14.2)<br>
</li>
<li>Response rate: 68.2%, 95% CI (58.3%, 78.1%)<br>
</li>
<li>Site-specific CIs acknowledging precision differences</li>
</ul>
<p><strong>Proper P-Value Interpretation</strong> (not “proves”):</p>
<ul>
<li>“Strong evidence against H₀” not “proves drug works”<br>
</li>
<li>“Supports the conclusion that” not “99.9% certain that”<br>
</li>
<li>P(data|H₀) explained correctly</li>
</ul>
<p><strong>Appropriate Handling of Non-Significance</strong> (not “accept”):</p>
<ul>
<li>“Insufficient evidence” not “no difference exists”<br>
</li>
<li>Type II error risk quantified (50% for headache test)<br>
</li>
<li>Safety signals flagged for Phase III investigation</li>
</ul>
<p><strong>Power and Sample Size</strong> (not vague justifications):</p>
<ul>
<li><em>A priori</em> calculation shown with formula<br>
</li>
<li>Phase III requirements specified (n=300/group)<br>
</li>
<li>Power inadequacy for safety endpoints acknowledged</li>
</ul>
<p><strong>Honest Communication of Uncertainty</strong>:</p>
<ul>
<li>Limitations section added<br>
</li>
<li>Small sample sizes flagged<br>
</li>
<li>Recommendations account for range of plausible effects</li>
</ul>
<p>The board approves the Phase III trial, but with the conservative design that proper statistical inference demands. The corrected report provides defendable estimates the FDA will respect.</p>
<p>“This,” Dr.&nbsp;Walsh says, “is what statistical inference should look like.”</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>The Three Pillars of Statistical Inference
</div>
</div>
<div class="callout-body-container callout-body">
<p>After three lectures and three companies, David and Maria have learned the complete toolkit:</p>
<p><strong>Lecture 1: Descriptive Statistics</strong> (TechFlow)</p>
<ul>
<li><strong>Question</strong>: “What happened?”<br>
</li>
<li><strong>Tools</strong>: Mean, median, SD, z-scores, correlation<br>
</li>
<li><strong>Purpose</strong>: Precisely describe the sample at hand<br>
</li>
<li><strong>Output</strong>: Exact statistics from observed data</li>
</ul>
<p><strong>Lecture 2: Probability</strong> (PrecisionCast)</p>
<ul>
<li><strong>Question</strong>: “What will happen?”<br>
</li>
<li><strong>Tools</strong>: P(Event), E(X), binomial, normal distributions<br>
</li>
<li><strong>Purpose</strong>: Predict future outcomes under uncertainty<br>
</li>
<li><strong>Output</strong>: Probabilities and expected values</li>
</ul>
<p><strong>Lecture 3: Statistical Inference</strong> (BorderMed)</p>
<ul>
<li><strong>Question</strong>: “What can we conclude?”<br>
</li>
<li><strong>Tools</strong>: Confidence intervals, hypothesis tests, power analysis<br>
</li>
<li><strong>Purpose</strong>: Learn about populations from samples, honestly<br>
</li>
<li><strong>Output</strong>: Estimates with quantified uncertainty</li>
</ul>
<p><strong>The Progression</strong>:</p>
<ul>
<li>Descriptive statistics <strong>describe</strong> what you have<br>
</li>
<li>Probability <strong>predicts</strong> what might happen<br>
</li>
<li>Statistical inference <strong>generalizes</strong> from sample to population <strong>with appropriate uncertainty</strong></li>
</ul>
<p><strong>The Integration</strong>:</p>
<ul>
<li>You need descriptive statistics (Lecture 1) to calculate sample statistics<br>
</li>
<li>You need probability distributions (Lecture 2) to build sampling distributions<br>
</li>
<li>You use both to do statistical inference (Lecture 3) properly</li>
</ul>
<p>All three are essential for data-driven decision making.</p>
</div>
</div>
</section>
<section id="looking-ahead" class="level2" data-number="4.13">
<h2 data-number="4.13" class="anchored" data-anchor-id="looking-ahead"><span class="header-section-number">4.13</span> Looking Ahead</h2>
<p>David and Maria have now completed the core of statistical inference: descriptive statistics, probability, and estimation/hypothesis testing for single populations.</p>
<p>But Dr.&nbsp;Walsh has one more question.</p>
<p>“Your report mentions that we can’t determine if site differences are real or just sampling variability,” she says. “You recommended ANOVA testing. Can you help us with that?”</p>
<p>Maria smiles. “Actually, that’s next lecture, Lecture 4. Next lecture is about comparing means and variances between groups. After that, we’ll tackle ANOVA for comparing multiple groups simultaneously.”</p>
<p>“But before we get there,” David adds, “we need to master the next building block: inference about means when we have <em>two</em> populations to compare, and inference about variances.”</p>
<p>The journey continues. From describing samples, to predicting futures, to generalizing to populations, and next, to comparing populations.</p>
<p>The toolkit expands. The power grows. The decisions improve.</p>
<p>That’s the promise of statistics.</p>
</section>
<section id="practice-problems" class="level2" data-number="4.14">
<h2 data-number="4.14" class="anchored" data-anchor-id="practice-problems"><span class="header-section-number">4.14</span> Practice Problems</h2>
<p>Now it’s your turn to apply statistical inference. These problems use the BorderMed clinical trial dataset and mirror the types of analyses David and Maria performed.</p>
<p><strong>Download the dataset</strong>: Get <code>BorderMed_Phase2_Trial.xlsx</code> from your course materials before starting.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>About This Dataset
</div>
</div>
<div class="callout-body-container callout-body">
<p>The dataset contains individual-level data for 85 patients: - Baseline systolic BP - Week 12 systolic BP - Change in systolic BP - Site (El Paso, Phoenix, Albuquerque) - Adverse events (headache: yes/no) - Demographics (age, sex)</p>
<p><strong>Use this data</strong> to complete the problems below.</p>
</div>
</div>
<section id="problem-set-1-confidence-intervals-30-points" class="level3">
<h3 class="anchored" data-anchor-id="problem-set-1-confidence-intervals-30-points">Problem Set 1: Confidence Intervals (30 points)</h3>
<p><strong>Part A: Mean Blood Pressure Reduction (15 points)</strong></p>
<p>Using the full sample (n = 85):</p>
<ol type="1">
<li>Calculate the sample mean reduction in systolic BP</li>
<li>Calculate the sample standard deviation</li>
<li>Calculate the standard error</li>
<li>Find the appropriate t-critical value for 95% confidence</li>
<li>Calculate the 95% confidence interval</li>
<li>Interpret your interval in one sentence (what does “95% confident” mean?)</li>
<li>Does your interval support the FDA’s 10 mmHg threshold? Explain.</li>
</ol>
<p><strong>Part B: Response Rate (15 points)</strong></p>
<p>Calculate the proportion of patients who achieved systolic BP &lt; 140 mmHg at week 12.</p>
<ol type="1">
<li>Calculate the sample proportion</li>
<li>Calculate the standard error for a proportion</li>
<li>Calculate the 95% confidence interval for the population proportion</li>
<li>The original report claimed this response rate is “superior to existing agents (50-60%).” Based on your confidence interval, is this claim justified?</li>
</ol>
</section>
<section id="problem-set-2-hypothesis-testing-35-points" class="level3">
<h3 class="anchored" data-anchor-id="problem-set-2-hypothesis-testing-35-points">Problem Set 2: Hypothesis Testing (35 points)</h3>
<p><strong>Part A: Efficacy Test (15 points)</strong></p>
<p>Test whether VasoRelief significantly reduces blood pressure:</p>
<ol type="1">
<li>State null and alternative hypotheses</li>
<li>Calculate the test statistic</li>
<li>Find the p-value</li>
<li>State your decision (reject or fail to reject H₀) at α = 0.05</li>
<li>Write a proper interpretation (2-3 sentences, avoiding common p-value misinterpretations)</li>
</ol>
<p><strong>Part B: Safety Test (20 points)</strong></p>
<p>Test whether the headache rate differs from the known placebo rate of 20%:</p>
<ol type="1">
<li>State null and alternative hypotheses</li>
<li>Calculate the observed proportion who experienced headaches</li>
<li>Calculate the z-test statistic for proportions</li>
<li>Find the p-value (two-tailed)</li>
<li>State your decision at α = 0.05</li>
<li><strong>Critical thinking</strong>: The original report concluded “no significant headache risk.” Explain why this conclusion is problematic, considering:
<ul>
<li>The numerical difference between observed and placebo rates</li>
<li>The concept of Type II error</li>
<li>The implications for patient safety</li>
</ul></li>
</ol>
</section>
<section id="problem-set-3-sample-size-and-power-20-points" class="level3">
<h3 class="anchored" data-anchor-id="problem-set-3-sample-size-and-power-20-points">Problem Set 3: Sample Size and Power (20 points)</h3>
<p><strong>Part A: Required Sample Size (10 points)</strong></p>
<p>BorderMed wants to design Phase III to detect a minimum effect of 9 mmHg with 90% power at α = 0.05.</p>
<ol type="1">
<li>Using SD = 8.6 mmHg, calculate the required sample size per group</li>
<li>How does this compare to their Phase II sample (n = 85 total)?</li>
<li>Explain why Phase III needs a larger sample even though Phase II “worked”</li>
</ol>
<p><strong>Part B: Power Analysis for Safety (10 points)</strong></p>
<p>For the headache endpoint:</p>
<ol type="1">
<li>With n = 85 and observed rates of 27.1% vs 20% (placebo), the power was approximately 48%. Explain what “48% power” means in context.</li>
<li>Calculate the required sample size per group to achieve 80% power for detecting this difference</li>
<li>Explain why adequate power is especially important for safety endpoints</li>
</ol>
</section>
<section id="problem-set-4-site-specific-analysis-15-points" class="level3">
<h3 class="anchored" data-anchor-id="problem-set-4-site-specific-analysis-15-points">Problem Set 4: Site-Specific Analysis (15 points)</h3>
<p>Calculate 95% confidence intervals for mean BP reduction at each site:</p>
<ol type="1">
<li><strong>El Paso</strong> (n = 42, mean = 13.8 mmHg): Calculate CI</li>
<li><strong>Phoenix</strong> (n = 28, mean = 11.6 mmHg): Calculate CI<br>
</li>
<li><strong>Albuquerque</strong> (n = 15, mean = 9.2 mmHg): Calculate CI</li>
<li>Compare the widths of these three confidence intervals. What does the difference in widths tell you?</li>
<li>Do the confidence intervals provide strong evidence that sites differ in true efficacy? Explain.</li>
<li>Why should we be especially cautious about interpreting the Albuquerque results?</li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-17-contents" aria-controls="callout-17" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Excel Functions You’ll Need
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-17" class="callout-17-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Descriptive Statistics</strong>:</p>
<pre><code>=AVERAGE(range)
=STDEV.S(range)
=COUNT(range)</code></pre>
<p><strong>Confidence Intervals</strong>:</p>
<pre><code>Standard Error: =STDEV.S(range)/SQRT(COUNT(range))
t-critical value: =T.INV.2T(0.05, degrees_freedom)
Margin of Error: =CONFIDENCE.T(0.05, stdev, n)</code></pre>
<p><strong>Hypothesis Tests</strong>:</p>
<pre><code>t-test statistic: =T.TEST(range1, range2, tails, type)
p-value for t-test: =T.DIST.2T(test_statistic, df)
z-test for proportion: Use formula =(p_hat - p0)/SQRT(p0*(1-p0)/n)</code></pre>
<p><strong>Sample Size</strong> (use formula): <span class="math display">\[n = \left[\frac{(z_{1-\alpha/2} + z_{1-\beta}) \times \sigma}{\delta}\right]^2\]</span></p>
<p>Where: - <span class="math inline">\(z_{1-\alpha/2}\)</span> = 1.96 for 95% confidence - <span class="math inline">\(z_{1-\beta}\)</span> = 0.84 for 80% power, 1.28 for 90% power - <span class="math inline">\(\sigma\)</span> = standard deviation - <span class="math inline">\(\delta\)</span> = minimum detectable difference</p>
</div>
</div>
</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/ncachanosky\.github\.io\/XQMB-5311");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./chapter_02.html" class="pagination-link" aria-label="Probability">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Probability</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./chapter_04.html" class="pagination-link" aria-label="ANOVA: Analysis of Variance">
        <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">ANOVA: Analysis of Variance</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© Nicolas Cachanosky, The University of Texas at El Paso, Center for Free Enterprise</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/ncachanosky/XQMB-5311/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link active" href="https://github.com/ncachanosky/XQMB-5311" aria-current="page">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/ncachanosky">
      <i class="bi bi-linkedin" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com/n_cachanosky">
      <i class="bi bi-twitter-x" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




<script src="site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>