<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="Course readings for XQMB 5311 – Statistics for Business – The University of Texas at El Paso.">

<title>6&nbsp; Categorical Data Analysis – The Precision Advantage: Statistics for Business</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./chapter_06.html" rel="next">
<link href="./chapter_04.html" rel="prev">
<link href="./favicon.png" rel="icon" type="image/png">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-065a5179aebd64318d7ea99d77b64a9e.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-969ddfa49e00a70eb3423444dbc81f6c.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-065a5179aebd64318d7ea99d77b64a9e.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-224b48a91c0f626bf087add3423f4096.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark-8fba65ec5d79e9223d5579f32ee5f772.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="site_libs/bootstrap/bootstrap-224b48a91c0f626bf087add3423f4096.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="https://raw.github.com/ncachanosky/EO-styles/main/styles.css">
<meta property="og:title" content="The Precision Advantage: Statistics for Business">
<meta property="og:description" content="Course readings for XQMB 5311 – Quantitative Methods for Business – The University of Texas at El Paso. An institutions-first treatment of monetary and financial economics.">
<meta property="og:image" content="https://ncachanosky.github.io/XQMB-5311/assets/logo.png">
<meta property="og:site_name" content="The Precision Advantage: Statistics for Business">
<meta property="og:image:height" content="1687">
<meta property="og:image:width" content="1687">
<meta name="twitter:title" content="Money, The Precision Advantage: Statistics for Business">
<meta name="twitter:description" content="Course readings for ECON 3320 – Quantitative Methods for Business – The University of Texas at El Paso. An institutions-first treatment of monetary and financial economics.">
<meta name="twitter:image" content="https://ncachanosky.github.io/XQMB-5311/assets/logo.png">
<meta name="twitter:creator" content="@n_cachanosky">
<meta name="twitter:card" content="summary">
<meta name="twitter:image-height" content="1687">
<meta name="twitter:image-width" content="1687">
</head>

<body class="nav-sidebar docked quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./chapter_05.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Categorical Data Analysis</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="./index.html" class="sidebar-logo-link">
      <img src="./assets/logo.png" alt="" class="sidebar-logo light-content py-0 d-lg-inline d-none">
      <img src="./assets/logo.png" alt="" class="sidebar-logo dark-content py-0 d-lg-inline d-none">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="./">The Precision Advantage: Statistics for Business</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/ncachanosky/XQMB-5311" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter_01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Descriptive Statistics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter_02.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Probability</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter_03.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Interval Estimation and Hypothesis Testing</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter_04.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">ANOVA: Analysis of Variance</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter_05.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Categorical Data Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter_06.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Statistical Foundations Review: From Description to Decision</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter_07.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Regression Analysis: Introduction to Econometrics</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#learning-objectives" id="toc-learning-objectives" class="nav-link active" data-scroll-target="#learning-objectives">Learning Objectives</a></li>
  <li><a href="#introduction-the-150000-question" id="toc-introduction-the-150000-question" class="nav-link" data-scroll-target="#introduction-the-150000-question"><span class="header-section-number">6.1</span> Introduction: The $150,000 Question</a></li>
  <li><a href="#the-statistical-journey-continues" id="toc-the-statistical-journey-continues" class="nav-link" data-scroll-target="#the-statistical-journey-continues"><span class="header-section-number">6.2</span> The Statistical Journey Continues</a></li>
  <li><a href="#the-first-error-association-vs.-causation" id="toc-the-first-error-association-vs.-causation" class="nav-link" data-scroll-target="#the-first-error-association-vs.-causation"><span class="header-section-number">6.3</span> The First Error: Association vs.&nbsp;Causation</a>
  <ul class="collapse">
  <li><a href="#what-chi-square-actually-tests" id="toc-what-chi-square-actually-tests" class="nav-link" data-scroll-target="#what-chi-square-actually-tests">What Chi-Square Actually Tests</a></li>
  </ul></li>
  <li><a href="#the-second-error-accepting-the-null-hypothesis" id="toc-the-second-error-accepting-the-null-hypothesis" class="nav-link" data-scroll-target="#the-second-error-accepting-the-null-hypothesis"><span class="header-section-number">6.4</span> The Second Error: “Accepting” the Null Hypothesis</a>
  <ul class="collapse">
  <li><a href="#the-courtroom-analogy" id="toc-the-courtroom-analogy" class="nav-link" data-scroll-target="#the-courtroom-analogy">The Courtroom Analogy</a></li>
  </ul></li>
  <li><a href="#the-third-error-misunderstanding-p-values" id="toc-the-third-error-misunderstanding-p-values" class="nav-link" data-scroll-target="#the-third-error-misunderstanding-p-values"><span class="header-section-number">6.5</span> The Third Error: Misunderstanding P-Values</a>
  <ul class="collapse">
  <li><a href="#what-p-values-actually-mean" id="toc-what-p-values-actually-mean" class="nav-link" data-scroll-target="#what-p-values-actually-mean">What P-Values Actually Mean</a></li>
  </ul></li>
  <li><a href="#the-correct-analysis-chi-square-test-of-independence" id="toc-the-correct-analysis-chi-square-test-of-independence" class="nav-link" data-scroll-target="#the-correct-analysis-chi-square-test-of-independence"><span class="header-section-number">6.6</span> The Correct Analysis: Chi-Square Test of Independence</a>
  <ul class="collapse">
  <li><a href="#step-1-the-observed-data-contingency-table" id="toc-step-1-the-observed-data-contingency-table" class="nav-link" data-scroll-target="#step-1-the-observed-data-contingency-table">Step 1: The Observed Data (Contingency Table)</a></li>
  <li><a href="#step-2-expected-frequencies-under-independence" id="toc-step-2-expected-frequencies-under-independence" class="nav-link" data-scroll-target="#step-2-expected-frequencies-under-independence">Step 2: Expected Frequencies Under Independence</a></li>
  <li><a href="#step-3-calculate-chi-square-statistic" id="toc-step-3-calculate-chi-square-statistic" class="nav-link" data-scroll-target="#step-3-calculate-chi-square-statistic">Step 3: Calculate Chi-Square Statistic</a></li>
  <li><a href="#understanding-the-chi-square-distribution" id="toc-understanding-the-chi-square-distribution" class="nav-link" data-scroll-target="#understanding-the-chi-square-distribution">Understanding the Chi-Square Distribution</a></li>
  <li><a href="#step-4-p-value-and-decision" id="toc-step-4-p-value-and-decision" class="nav-link" data-scroll-target="#step-4-p-value-and-decision">Step 4: P-Value and Decision</a></li>
  <li><a href="#step-5-proper-interpretation" id="toc-step-5-proper-interpretation" class="nav-link" data-scroll-target="#step-5-proper-interpretation">Step 5: Proper Interpretation</a></li>
  </ul></li>
  <li><a href="#adding-confidence-intervals-for-proportions" id="toc-adding-confidence-intervals-for-proportions" class="nav-link" data-scroll-target="#adding-confidence-intervals-for-proportions"><span class="header-section-number">6.7</span> Adding Confidence Intervals for Proportions</a>
  <ul class="collapse">
  <li><a href="#conversion-rate-confidence-intervals" id="toc-conversion-rate-confidence-intervals" class="nav-link" data-scroll-target="#conversion-rate-confidence-intervals">Conversion Rate Confidence Intervals</a></li>
  </ul></li>
  <li><a href="#cost-effectiveness-the-missing-analysis" id="toc-cost-effectiveness-the-missing-analysis" class="nav-link" data-scroll-target="#cost-effectiveness-the-missing-analysis"><span class="header-section-number">6.8</span> Cost-Effectiveness: The Missing Analysis</a></li>
  <li><a href="#potential-confounding-simpsons-paradox" id="toc-potential-confounding-simpsons-paradox" class="nav-link" data-scroll-target="#potential-confounding-simpsons-paradox"><span class="header-section-number">6.9</span> Potential Confounding: Simpson’s Paradox</a>
  <ul class="collapse">
  <li><a href="#the-product-mix-problem" id="toc-the-product-mix-problem" class="nav-link" data-scroll-target="#the-product-mix-problem">The Product Mix Problem</a></li>
  </ul></li>
  <li><a href="#the-corrected-report-what-david-and-maria-delivered" id="toc-the-corrected-report-what-david-and-maria-delivered" class="nav-link" data-scroll-target="#the-corrected-report-what-david-and-maria-delivered"><span class="header-section-number">6.10</span> The Corrected Report: What David and Maria Delivered</a></li>
  <li><a href="#connecting-the-complete-statistical-journey" id="toc-connecting-the-complete-statistical-journey" class="nav-link" data-scroll-target="#connecting-the-complete-statistical-journey"><span class="header-section-number">6.11</span> Connecting the Complete Statistical Journey</a></li>
  <li><a href="#looking-ahead-the-limits-of-what-weve-learned" id="toc-looking-ahead-the-limits-of-what-weve-learned" class="nav-link" data-scroll-target="#looking-ahead-the-limits-of-what-weve-learned"><span class="header-section-number">6.12</span> Looking Ahead: The Limits of What We’ve Learned</a>
  <ul class="collapse">
  <li><a href="#the-five-lectures-comparing-not-predicting" id="toc-the-five-lectures-comparing-not-predicting" class="nav-link" data-scroll-target="#the-five-lectures-comparing-not-predicting">The Five Lectures: Comparing, Not Predicting</a></li>
  <li><a href="#the-fundamental-limitation-categories-and-comparisons" id="toc-the-fundamental-limitation-categories-and-comparisons" class="nav-link" data-scroll-target="#the-fundamental-limitation-categories-and-comparisons">The Fundamental Limitation: Categories and Comparisons</a></li>
  <li><a href="#what-regression-analysis-adds" id="toc-what-regression-analysis-adds" class="nav-link" data-scroll-target="#what-regression-analysis-adds">What Regression Analysis Adds</a></li>
  <li><a href="#the-statistical-toolkit-complete-vs.-comprehensive" id="toc-the-statistical-toolkit-complete-vs.-comprehensive" class="nav-link" data-scroll-target="#the-statistical-toolkit-complete-vs.-comprehensive">The Statistical Toolkit: Complete vs.&nbsp;Comprehensive</a></li>
  <li><a href="#the-bridge-to-lecture-6" id="toc-the-bridge-to-lecture-6" class="nav-link" data-scroll-target="#the-bridge-to-lecture-6">The Bridge to Lecture 6</a></li>
  </ul></li>
  <li><a href="#practice-problems" id="toc-practice-problems" class="nav-link" data-scroll-target="#practice-problems"><span class="header-section-number">6.13</span> Practice Problems</a>
  <ul class="collapse">
  <li><a href="#problem-1-chi-square-test-of-independence-30-points" id="toc-problem-1-chi-square-test-of-independence-30-points" class="nav-link" data-scroll-target="#problem-1-chi-square-test-of-independence-30-points">Problem 1: Chi-Square Test of Independence (30 points)</a></li>
  <li><a href="#problem-2-conversion-rate-confidence-intervals-25-points" id="toc-problem-2-conversion-rate-confidence-intervals-25-points" class="nav-link" data-scroll-target="#problem-2-conversion-rate-confidence-intervals-25-points">Problem 2: Conversion Rate Confidence Intervals (25 points)</a></li>
  <li><a href="#problem-3-testing-for-confounding-30-points" id="toc-problem-3-testing-for-confounding-30-points" class="nav-link" data-scroll-target="#problem-3-testing-for-confounding-30-points">Problem 3: Testing for Confounding (30 points)</a></li>
  <li><a href="#problem-4-the-regional-analysis-revisited-15-points" id="toc-problem-4-the-regional-analysis-revisited-15-points" class="nav-link" data-scroll-target="#problem-4-the-regional-analysis-revisited-15-points">Problem 4: The Regional Analysis Revisited (15 points)</a></li>
  <li><a href="#submission-requirements" id="toc-submission-requirements" class="nav-link" data-scroll-target="#submission-requirements">Submission Requirements</a></li>
  <li><a href="#additional-resources" id="toc-additional-resources" class="nav-link" data-scroll-target="#additional-resources">Additional Resources</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/ncachanosky/XQMB-5311/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Categorical Data Analysis</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  
<div>
  <div class="abstract">
    <div class="block-title">Abstract</div>
    <p>A statistically significant result is not a license to claim causation. This chapter covers chi-square goodness-of-fit and independence tests, confidence intervals for proportions, and — critically — the boundary between association and causation in observational data. Working through PixelPerfect Marketing’s campaign analysis, where a correct chi-square test leads to dangerously wrong conclusions, students learn to interpret categorical data honestly and avoid the analytical errors that can send $150,000 in the wrong direction.</p>
  </div>
</div>


</header>


<section id="learning-objectives" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="learning-objectives">Learning Objectives</h2>
<p>By the end of this chapter, you will be able to:</p>
<ol type="1">
<li>✅ Conduct goodness of fit tests to evaluate whether data follows a hypothesized distribution</li>
<li>✅ Perform tests of independence to determine relationships between categorical variables</li>
<li>✅ Calculate and interpret chi-square test statistics and p-values for categorical data</li>
<li>✅ Understand the critical difference between association and causation in observational studies</li>
<li>✅ Calculate confidence intervals for proportions and conversion rates</li>
<li>✅ Recognize and avoid common interpretation errors in chi-square testing</li>
<li>✅ Apply categorical data analysis to digital marketing, A/B testing, and customer segmentation decisions</li>
</ol>
</section>
<section id="introduction-the-150000-question" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="introduction-the-150000-question"><span class="header-section-number">6.1</span> Introduction: The $150,000 Question</h2>
<p>It’s 8:30 AM on October 8, 2025. Jennifer Torres, Chief Marketing Officer at PixelPerfect Marketing Agency, sits in her office reviewing her team’s Q3 2025 campaign performance report. Her digital marketing agency tracked 2,400 customer interactions across four channels for their major e-commerce client, and the recommendations seem… dangerously aggressive.</p>
<p>Her analytics director’s report states:</p>
<blockquote class="blockquote">
<p><strong>Channel Performance Analysis</strong>: Social Media has the highest conversion rate at 24.5%, establishing it as our top-performing channel. Email marketing converts at 18.7%, significantly lower than Social Media. Display Ads perform worst with only 12.3% conversion, raising serious concerns about ROI.</p>
<p><strong>Statistical Validation</strong>: Chi-square statistic: χ² = 42.87, p-value: &lt; 0.001. Since the p-value is less than 0.001, we can conclude that <strong>channel choice causes different conversion rates</strong>. The relationship between channel and conversion is statistically significant, meaning these differences are real and not due to chance. With such a low p-value, we can be <strong>over 99.9% confident in this finding</strong>.</p>
<p><strong>Regional Analysis</strong>: The p-value of 0.64 is well above our significance threshold of 0.05, so we <strong>accept the null hypothesis</strong> that regions have equal conversion rates. There is no regional effect, the small differences we observe are simply random variation.</p>
<p><strong>Recommendation</strong>: Increase Social Media budget by 40% and reduce Display Ad spending by 50%. Reallocate <strong>$150,000 from Display to Social Media for Q4</strong> to maximize conversions.</p>
</blockquote>
<p>Jennifer sets down the report, alarmed. “Hold on. We’re recommending a $150,000 budget shift based on one quarter of observational data?”</p>
<p>Her analytics director nods confidently. “The p-value is less than 0.001. The chi-square test <strong>proves</strong> that channel choice <strong>causes</strong> different conversion rates.”</p>
<p>“Does it?” Jennifer challenges. “I see several red flags here:</p>
<ul>
<li>You say the test ‘<strong>proves</strong>’ and ‘<strong>causes</strong>’—chi-square tests association, not causation<br>
</li>
<li>You ‘<strong>accept the null hypothesis</strong>’ for regions—we never accept H₀, only fail to reject it<br>
</li>
<li>You claim ‘99.9% confident’—that’s not what p-values mean<br>
</li>
<li>I see no confidence intervals for conversion rates<br>
</li>
<li>I see no cost-per-conversion analysis (what if Email converts less but costs way less?)<br>
</li>
<li>I see no consideration of confounding: product type, customer intent, seasonality”</li>
</ul>
<p>She pushes the report across the table. “I want this redone. I want proper interpretation of what chi-square tests actually mean. I want confidence intervals. I want cost-effectiveness. And most importantly, I want acknowledgment of what we DON’T know from observational data. We’re presenting to the client Friday. I will not recommend a $150,000 shift without proper statistical justification.”</p>
<p>The analytics team realizes they’ve fundamentally misunderstood chi-square interpretation—not the calculations, but what the results actually mean. Following the success stories from TechFlow Solutions, PrecisionCast Industries, and BorderMed Pharmaceuticals, they reach out to the EMBA program at The University of Texas at El Paso.</p>
<p>Enter David Martinez and Maria Rodriguez, the same EMBA students who transformed vague reports into statistical precision over the past nine months. But this time, the challenge is different. The math is correct. The chi-square test was run properly. The p-value is accurate. But the <strong>interpretations</strong> are dangerously wrong.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>The Cost of Misinterpreting Chi-Square Tests
</div>
</div>
<div class="callout-body-container callout-body">
<p>When TechFlow said “around $767,000,” they couldn’t set budgets. When PrecisionCast said “tests are pretty good,” they risked shipping defective units. When BorderMed said “proves efficacy,” they nearly committed $500M based on overconfidence.</p>
<p>When PixelPerfect says chi-square “<strong>proves</strong> that channel choice <strong>causes</strong> different conversion rates” and recommends reallocating $150,000 based on observational data, they might:</p>
<ul>
<li>Waste $150,000 shifting budget to channels that appear better only due to confounding<br>
</li>
<li>Miss that Display Ads might excel for certain product categories despite lower overall rates<br>
</li>
<li>Ignore critical cost differences (Email: $187/conversion vs Social Media: $306/conversion)<br>
</li>
<li>Make causal claims that observational chi-square tests cannot support<br>
</li>
<li>“Accept” null hypotheses when they should only “fail to reject”<br>
</li>
<li>Overlook Simpson’s Paradox: channel rankings might reverse within product categories</li>
</ul>
<p>In digital marketing, misinterpreting chi-square tests doesn’t just cost money—it destroys client relationships when promised results fail to materialize.</p>
<p><strong>The fix</strong>: Understand chi-square tests <strong>association</strong>, NOT causation. Calculate confidence intervals for proportions. Acknowledge confounding in observational data. Never say “proves,” “causes,” or “accept H₀.”</p>
</div>
</div>
<p>This chapter is about mastering categorical data analysis the right way. From “proves causation” to “shows association.” From “accept the null” to “fail to reject.” From treating observational data like experimental data to acknowledging inherent limitations.</p>
<p>Welcome to categorical data analysis—where the calculations are straightforward, but interpretation requires careful, critical thinking.</p>
</section>
<section id="the-statistical-journey-continues" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="the-statistical-journey-continues"><span class="header-section-number">6.2</span> The Statistical Journey Continues</h2>
<p>David and Maria meet with Jennifer and her analytics team at PixelPerfect’s El Paso office. It’s been nine months since they started their EMBA program, and their statistical toolkit has grown systematically.</p>
<p>“Let’s review your journey,” Maria begins, pulling up a timeline. “January: TechFlow taught you descriptive statistics for continuous data—means, standard deviations, z-scores.”</p>
<p>“April: PrecisionCast taught you probability—binomial distributions, expected values, normal curves,” David continues.</p>
<p>“July: BorderMed taught you statistical inference—confidence intervals, hypothesis testing, acknowledging uncertainty,” Maria adds.</p>
<p>“And now,” David says, “PixelPerfect is teaching you categorical data analysis. But there’s a twist this time.”</p>
<p>Jennifer leans forward. “What’s the twist?”</p>
<p>“Your team got the math right,” Maria explains. “The chi-square statistic of 42.87 is correct. The p-value &lt; 0.001 is correct. The contingency table is accurate. The problem isn’t the calculations—it’s the <strong>interpretation</strong>.”</p>
<p>David pulls up the report. “Three critical errors:</p>
<ol type="1">
<li><strong>Causation from association</strong>: Claiming chi-square proves channel choice <strong>causes</strong> conversion differences<br>
</li>
<li><strong>Accepting H₀</strong>: Saying you ‘accept the null hypothesis’ for regional differences<br>
</li>
<li><strong>Misunderstanding p-values</strong>: Claiming ‘99.9% confident’ based on p &lt; 0.001”</li>
</ol>
<p>“Each of these errors,” Maria emphasizes, “could lead to a disastrous $150,000 budget decision. Let’s fix them.”</p>
</section>
<section id="the-first-error-association-vs.-causation" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="the-first-error-association-vs.-causation"><span class="header-section-number">6.3</span> The First Error: Association vs.&nbsp;Causation</h2>
<p>David highlights the most dangerous line in the report: “Since the p-value is less than 0.001, we can conclude that channel choice <strong>causes</strong> different conversion rates.”</p>
<p>“That single word, ‘causes’, turns a correct statistical test into a false claim,” he says.</p>
<section id="what-chi-square-actually-tests" class="level3">
<h3 class="anchored" data-anchor-id="what-chi-square-actually-tests">What Chi-Square Actually Tests</h3>
<p>Maria creates a clear explanation:</p>
<p><strong>The Chi-Square Test of Independence Asks ONE Question:</strong><br>
<em>“Are these two categorical variables statistically independent, or is there evidence they are associated?”</em></p>
<p><strong>What Chi-Square Does NOT Test:</strong></p>
<ul>
<li>Whether X causes Y<br>
</li>
<li>Whether Y causes X<br>
</li>
<li>Whether some third variable Z causes both X and Y<br>
</li>
<li>The direction of any causal relationship<br>
</li>
<li>The mechanism of the relationship<br>
</li>
<li>Whether the association matters practically</li>
</ul>
<p>“In your case,” David explains to the team, “chi-square tells you that marketing channel and conversion outcome are <strong>associated</strong>—they’re not independent. But it says absolutely nothing about WHY they’re associated.”</p>
<p>Maria draws a diagram on the whiteboard:</p>
<pre><code>Possible Explanations for Channel-Conversion Association:

✗ Channel CAUSES conversion differences (what your report claims)

✓ Product type confounds both:
  - Premium products → promoted on Social Media → naturally convert better
  - Budget products → promoted via Email → naturally convert worse
  
✓ Customer intent drives everything:
  - High-intent buyers → convert regardless of channel
  - Low-intent browsers → don't convert regardless of channel
  
✓ Selection bias:
  - Social Media reaches younger, tech-savvy customers (already more likely to convert)
  - Email reaches older, less engaged customers (already less likely to convert)
  
✓ Time of day:
  - Social Media ads shown during peak shopping hours
  - Display Ads shown during low-engagement times</code></pre>
<p>“Chi-square can’t distinguish between these scenarios,” David emphasizes. “To claim causation, you need:</p>
<ul>
<li><strong>Randomized experiments</strong>: Randomly assign customers to channels<br>
</li>
<li><strong>Statistical control</strong>: Analyze within product categories, demographics, etc.<br>
</li>
<li><strong>Causal inference methods</strong>: Propensity scores, instrumental variables, difference-in-differences”</li>
</ul>
<p>Jennifer processes this. “So when my team says ‘channel choice causes different conversion rates,’ they’re…”</p>
<p>“Making an unjustified causal inference from correlation,” Maria finishes. “It’s the #1 error in observational data analysis.”</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Critical Distinction: Association vs.&nbsp;Causation
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Chi-Square Tests Tell You:</strong> Two categorical variables are statistically associated (not independent). They tend to occur together in patterns not explained by chance alone.</p>
<p><strong>Chi-Square Tests Do NOT Tell You:</strong></p>
<ul>
<li>Which variable (if either) causes the other<br>
</li>
<li>Whether a third variable causes both<br>
</li>
<li>Whether the association is causal or merely correlational<br>
</li>
<li>The mechanism behind the relationship</li>
</ul>
<p><strong>To Claim Causation from Observational Data, You Must:</strong></p>
<ol type="1">
<li>Establish temporal precedence (cause precedes effect)<br>
</li>
<li>Show the association persists after controlling for confounders<br>
</li>
<li>Rule out plausible alternative explanations<br>
</li>
<li>Provide a theoretical mechanism<br>
</li>
<li>Ideally: conduct randomized experiments (gold standard)</li>
</ol>
<p><strong>PixelPerfect’s Data:</strong> Observational (customers self-selected into channels), cross-sectional (single quarter), uncontrolled (no adjustment for confounders) → <strong>Cannot support causal claims</strong></p>
<p><strong>Correct Language:</strong></p>
<ul>
<li>❌ “Channel choice causes conversion differences”<br>
</li>
<li>❌ “Social Media directly impacts conversion rates”<br>
</li>
<li>✅ “Channel and conversion are statistically associated”<br>
</li>
<li>✅ “Conversion patterns differ by channel, though causation cannot be inferred”<br>
</li>
<li>✅ “The data suggest an association that warrants further investigation”</li>
</ul>
</div>
</div>
</section>
</section>
<section id="the-second-error-accepting-the-null-hypothesis" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="the-second-error-accepting-the-null-hypothesis"><span class="header-section-number">6.4</span> The Second Error: “Accepting” the Null Hypothesis</h2>
<p>David flips to page 3 of the report: “The p-value of 0.64 is well above 0.05, so we <strong>accept the null hypothesis</strong> that regions have equal conversion rates. There is no regional effect.”</p>
<p>Maria shakes her head. “Three words that shouldn’t exist in statistics: ‘accept the null.’ We <strong>never</strong> accept H₀. Ever.”</p>
<p>The analytics director looks confused. “But if p = 0.64, that means regions are the same, right?”</p>
<p>“No,” David responds firmly. “It means we don’t have sufficient evidence to conclude they’re different. Those are NOT the same statement.”</p>
<section id="the-courtroom-analogy" class="level3">
<h3 class="anchored" data-anchor-id="the-courtroom-analogy">The Courtroom Analogy</h3>
<p>Maria draws an analogy everyone understands:</p>
<p>“Imagine a criminal trial. The jury deliberates and returns with: ‘Not guilty.’ Does that mean the defendant is innocent?”</p>
<p>Jennifer responds immediately: “No.&nbsp;‘Not guilty’ means insufficient evidence to convict. The person might be innocent, or guilty but we can’t prove it.”</p>
<p>“Exactly!” David confirms. “Same principle in statistics:”</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 66%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Legal System</strong></th>
<th style="text-align: left;"><strong>Statistical Hypothesis Testing</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Presumption of innocence</td>
<td style="text-align: left;">Assume null hypothesis is true</td>
</tr>
<tr class="even">
<td style="text-align: left;">Prosecution must prove guilt beyond reasonable doubt</td>
<td style="text-align: left;">Researcher must show strong evidence against H₀</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Verdict: “Not guilty”</td>
<td style="text-align: left;">Decision: “Fail to reject H₀”</td>
</tr>
<tr class="even">
<td style="text-align: left;">Does NOT mean “proven innocent”</td>
<td style="text-align: left;">Does NOT mean “H₀ is true”</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Means “insufficient evidence to convict”</td>
<td style="text-align: left;">Means “insufficient evidence against H₀”</td>
</tr>
</tbody>
</table>
<p>“In your regional analysis,” Maria explains, “p = 0.64 means:</p>
<ul>
<li>We <strong>fail to reject</strong> H₀ (regions are equal)<br>
</li>
<li>We do <strong>NOT</strong> conclude regions are actually equal<br>
</li>
<li>We lack evidence of regional differences <strong>in this dataset</strong>”</li>
</ul>
<p>David adds three possible explanations:</p>
<p><strong>Why might we get p = 0.64?</strong></p>
<ol type="1">
<li><strong>Regions are truly equal</strong> (H₀ is actually true)</li>
<li><strong>Regions differ, but sample size too small</strong> to detect the difference (Type II error)</li>
<li><strong>Regions differ, but confounders obscure</strong> the pattern (measurement issues)</li>
</ol>
<p>“We don’t know which explanation is correct,” Maria emphasizes. “That’s why we never ‘accept’ H₀—we simply acknowledge we don’t have evidence against it.”</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Correct Interpretation of Non-Significant Results
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Wrong (from the bad report):</strong><br>
“p = 0.64, so we accept H₀. Regions have equal conversion rates. There is no regional effect.”</p>
<p><strong>Right:</strong><br>
“p = 0.64, so we fail to reject H₀. We lack sufficient evidence to conclude regional conversion rates differ. This could mean:</p>
<ul>
<li>Regions are truly similar in performance<br>
</li>
<li>Regional differences exist but our sample size (n=2,400) is insufficient to detect them<br>
</li>
<li>Regional differences exist but confounding variables obscure them<br>
</li>
<li>Seasonal or measurement factors mask real regional patterns”</li>
</ul>
<p><strong>Business Implications:</strong></p>
<ul>
<li>Don’t assume “not significant” means “no difference exists”<br>
</li>
<li>Consider statistical power: Did we collect enough data?<br>
</li>
<li>Consider effect size: Might the difference be real but small?<br>
</li>
<li>Consider practical significance: Even if not statistically detectable, could small regional differences matter strategically?</li>
</ul>
<p><strong>What to do:</strong> If regional performance is strategically important, collect more data rather than concluding regions don’t matter based on one non-significant test.</p>
</div>
</div>
</section>
</section>
<section id="the-third-error-misunderstanding-p-values" class="level2" data-number="6.5">
<h2 data-number="6.5" class="anchored" data-anchor-id="the-third-error-misunderstanding-p-values"><span class="header-section-number">6.5</span> The Third Error: Misunderstanding P-Values</h2>
<p>David points to another problematic sentence: “With such a low p-value, we can be over 99.9% confident in this finding.”</p>
<p>“That’s not what p-values mean,” Maria says. “Not even close.”</p>
<section id="what-p-values-actually-mean" class="level3">
<h3 class="anchored" data-anchor-id="what-p-values-actually-mean">What P-Values Actually Mean</h3>
<p>David writes out the formal definition:</p>
<p><strong>P-value = Probability of observing data this extreme (or more extreme) IF the null hypothesis were true</strong></p>
<p>“Breaking that down,” Maria explains:</p>
<ul>
<li><strong>IF H₀ is true</strong> (channel and outcome are independent)<br>
</li>
<li><strong>AND</strong> we repeated this study many times<br>
</li>
<li><strong>THEN</strong> we’d see a chi-square statistic ≥ 42.87 less than 0.1% of the time</li>
</ul>
<p>“The p-value is NOT,” David emphasizes:</p>
<ul>
<li>❌ The probability H₀ is true<br>
</li>
<li>❌ The probability H₁ is true<br>
</li>
<li>❌ The probability the results occurred by chance<br>
</li>
<li>❌ Our confidence in the finding<br>
</li>
<li>❌ The probability we’re making an error</li>
</ul>
<p>Jennifer interrupts: “So what DOES p &lt; 0.001 tell us?”</p>
<p>“It tells us,” Maria responds, “that IF channels and outcomes were truly independent, it would be very surprising to see differences this large. So either:</p>
<ol type="1">
<li>We witnessed a very rare event (&lt; 0.1% chance), OR<br>
</li>
<li>The null hypothesis of independence is false”</li>
</ol>
<p>“We conclude #2 is more plausible,” David adds, “but we can’t quantify how ‘confident’ we are. That would require Bayesian analysis with prior probabilities.”</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>P-Value Interpretation Guide
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>What p = 0.001 means:</strong><br>
“If channel and outcome were truly independent (H₀ true), we’d see data this extreme in fewer than 1 in 1,000 studies.”</p>
<p><strong>What p = 0.001 does NOT mean:</strong></p>
<ul>
<li>❌ “There’s a 0.1% chance H₀ is true”<br>
</li>
<li>❌ “We’re 99.9% confident in our conclusion”<br>
</li>
<li>❌ “There’s a 0.1% chance this is due to chance”<br>
</li>
<li>❌ “The effect size is large or important”</li>
</ul>
<p><strong>Correct interpretation:</strong></p>
<ul>
<li>✅ “This provides strong evidence against H₀”<br>
</li>
<li>✅ “These data are very unlikely under the assumption of independence”<br>
</li>
<li>✅ “We reject H₀ at the α = 0.05 level”</li>
</ul>
<p><strong>Remember:</strong> P-values measure evidence against H₀, not probability H₀ is false. They don’t tell you effect size, practical importance, or how confident you should be.</p>
</div>
</div>
</section>
</section>
<section id="the-correct-analysis-chi-square-test-of-independence" class="level2" data-number="6.6">
<h2 data-number="6.6" class="anchored" data-anchor-id="the-correct-analysis-chi-square-test-of-independence"><span class="header-section-number">6.6</span> The Correct Analysis: Chi-Square Test of Independence</h2>
<p>“Now let’s do this right,” David says, opening Excel. “Same data, same test, but proper interpretation.”</p>
<section id="step-1-the-observed-data-contingency-table" class="level3">
<h3 class="anchored" data-anchor-id="step-1-the-observed-data-contingency-table">Step 1: The Observed Data (Contingency Table)</h3>
<p>Maria recreates the 2,400 customer interactions:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Channel</strong></th>
<th style="text-align: left;"><strong>Conversion</strong></th>
<th style="text-align: left;"><strong>Click</strong></th>
<th style="text-align: left;"><strong>No Action</strong></th>
<th style="text-align: left;"><strong>Total</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Social Media</td>
<td style="text-align: left;">147</td>
<td style="text-align: left;">312</td>
<td style="text-align: left;">141</td>
<td style="text-align: left;">600</td>
</tr>
<tr class="even">
<td style="text-align: left;">Email</td>
<td style="text-align: left;">150</td>
<td style="text-align: left;">418</td>
<td style="text-align: left;">232</td>
<td style="text-align: left;">800</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Display Ads</td>
<td style="text-align: left;">74</td>
<td style="text-align: left;">298</td>
<td style="text-align: left;">228</td>
<td style="text-align: left;">600</td>
</tr>
<tr class="even">
<td style="text-align: left;">Search Ads</td>
<td style="text-align: left;">89</td>
<td style="text-align: left;">201</td>
<td style="text-align: left;">110</td>
<td style="text-align: left;">400</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Total</strong></td>
<td style="text-align: left;"><strong>460</strong></td>
<td style="text-align: left;"><strong>1,229</strong></td>
<td style="text-align: left;"><strong>711</strong></td>
<td style="text-align: left;"><strong>2,400</strong></td>
</tr>
</tbody>
</table>
<p>“This shows observed frequencies,” David explains. “147 Social Media impressions converted, 312 clicked without converting, 141 took no action.”</p>
</section>
<section id="step-2-expected-frequencies-under-independence" class="level3">
<h3 class="anchored" data-anchor-id="step-2-expected-frequencies-under-independence">Step 2: Expected Frequencies Under Independence</h3>
<p>“Under H₀ (independence),” Maria explains, “we calculate what we’d <strong>expect</strong> if channel choice told us nothing about outcome.”</p>
<p><span class="math display">\[E_{ij} = \frac{(\text{Row}_i \text{ Total}) \times (\text{Column}_j \text{ Total})}{\text{Grand Total}}\]</span></p>
<p>Example for Social Media/Conversion: <span class="math display">\[E_{\text{SM, Conv}} = \frac{600 \times 460}{2,400} = 115\]</span></p>
<p>“If channel doesn’t matter,” David clarifies, “we’d expect 115 conversions from Social Media’s 600 impressions (because overall, 460/2,400 = 19.2% convert).”</p>
<p>Expected frequencies:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Channel</strong></th>
<th style="text-align: left;"><strong>Conversion</strong></th>
<th style="text-align: left;"><strong>Click</strong></th>
<th style="text-align: left;"><strong>No Action</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Social Media</td>
<td style="text-align: left;">115.0</td>
<td style="text-align: left;">307.3</td>
<td style="text-align: left;">177.8</td>
</tr>
<tr class="even">
<td style="text-align: left;">Email</td>
<td style="text-align: left;">153.3</td>
<td style="text-align: left;">410.3</td>
<td style="text-align: left;">236.7</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Display Ads</td>
<td style="text-align: left;">115.0</td>
<td style="text-align: left;">307.3</td>
<td style="text-align: left;">177.8</td>
</tr>
<tr class="even">
<td style="text-align: left;">Search Ads</td>
<td style="text-align: left;">76.7</td>
<td style="text-align: left;">204.8</td>
<td style="text-align: left;">118.3</td>
</tr>
</tbody>
</table>
<p>“Notice,” Maria points out, “Social Media observed 147 conversions but expected only 115. That’s 32 more than expected under independence.”</p>
</section>
<section id="step-3-calculate-chi-square-statistic" class="level3">
<h3 class="anchored" data-anchor-id="step-3-calculate-chi-square-statistic">Step 3: Calculate Chi-Square Statistic</h3>
<p><span class="math display">\[\chi^2 = \sum_{i=1}^{r} \sum_{j=1}^{c} \frac{(O_{ij} - E_{ij})^2}{E_{ij}}\]</span></p>
<p>“This formula,” David explains, “measures how far observed frequencies deviate from expected frequencies, standardized by the expected frequencies.”</p>
<p>Computing for each cell:</p>
<ul>
<li>Social Media/Conversion: (147 - 115)² / 115 = 8.90<br>
</li>
<li>Social Media/Click: (312 - 307.3)² / 307.3 = 0.07<br>
</li>
<li>Social Media/No Action: (141 - 177.8)² / 177.8 = 7.60<br>
</li>
<li>… (repeating for all 12 cells)</li>
</ul>
<p><span class="math display">\[\chi^2 = 8.90 + 0.07 + 7.60 + ... = 42.87\]</span></p>
<p><strong>Degrees of freedom:</strong> df = (rows - 1)(columns - 1) = (4 - 1)(3 - 1) = 6</p>
</section>
<section id="understanding-the-chi-square-distribution" class="level3">
<h3 class="anchored" data-anchor-id="understanding-the-chi-square-distribution">Understanding the Chi-Square Distribution</h3>
<p>“Wait,” Jennifer interrupts. “We’ve calculated this chi-square statistic of 42.87. But what does that number actually mean? Why are we using chi-square anyway?”</p>
<p>Maria nods. “Great question. Let’s step back and understand what we’re doing.”</p>
<section id="what-is-the-chi-square-distribution" class="level4">
<h4 class="anchored" data-anchor-id="what-is-the-chi-square-distribution">What Is the Chi-Square Distribution?</h4>
<p>David explains: “Remember from BorderMed (Lecture 3) when we used the <strong>t-distribution</strong> to test hypotheses about means? The t-distribution told us what values of t we’d expect to see if the null hypothesis were true.”</p>
<p>“The <strong>chi-square distribution</strong> does the same thing, but for categorical data,” Maria adds. “It tells us what values of χ² we’d expect to see <strong>if the two variables were truly independent</strong>.”</p>
<p>She draws a chi-square distribution curve:</p>
<pre><code>         Chi-Square Distribution (df = 6)
         
    P(χ²)
      |     
 0.15 |    ╱‾╲
      |   ╱   ╲___
 0.10 |  ╱        ╲___
      | ╱             ╲____
 0.05 |╱                   ╲_______
      |__________________________|____╲______
      0    5    10   15   20   25   30   35   40  χ²
                          ↑            ↑
                      Critical     Our test
                      value        statistic
                      (12.59)      (42.87)</code></pre>
<p>“This distribution,” David explains, “shows us the probability of different χ² values <strong>if H₀ were true</strong> (if channel and outcome were independent).”</p>
<p><strong>Key Properties of Chi-Square Distribution:</strong></p>
<ol type="1">
<li><strong>Always positive</strong>: χ² ≥ 0 (because we’re squaring differences)<br>
</li>
<li><strong>Right-skewed</strong>: Most values cluster near zero, long tail to the right<br>
</li>
<li><strong>Shape depends on df</strong>: More degrees of freedom → more symmetric, shifts right<br>
</li>
<li><strong>Mean equals df</strong>: For df = 6, average χ² = 6 under H₀</li>
</ol>
</section>
<section id="why-chi-square-for-categorical-data" class="level4">
<h4 class="anchored" data-anchor-id="why-chi-square-for-categorical-data">Why Chi-Square for Categorical Data?</h4>
<p>“But why this specific distribution?” Jennifer asks.</p>
<p>Maria explains the mathematical foundation:</p>
<p>“When we calculate our test statistic, we’re summing up squared standardized differences:</p>
<p><span class="math display">\[\chi^2 = \sum \frac{(O - E)^2}{E}\]</span></p>
<p>Each term is approximately: <span class="math display">\[\frac{(O - E)^2}{E} \approx \frac{(O - E)^2}{\sqrt{E} \times \sqrt{E}} = \left(\frac{O - E}{\sqrt{E}}\right)^2\]</span></p>
<p>The part in parentheses, <span class="math inline">\(\frac{O - E}{\sqrt{E}}\)</span>, is like a <strong>z-score</strong> (it’s a standardized deviation). And remember from Lecture 2: when you square a standard normal variable (z), you get a chi-square distribution with df = 1.”</p>
<p>“So,” David continues, “our χ² statistic is essentially summing up <strong>squared z-scores</strong> across all cells. When we have multiple cells, the sum of independent squared z-scores follows a chi-square distribution with degrees of freedom equal to the number of <strong>independent</strong> squared terms.”</p>
</section>
<section id="why-df-r-1c-1" class="level4">
<h4 class="anchored" data-anchor-id="why-df-r-1c-1">Why df = (r-1)(c-1)?</h4>
<p>“Why not just df = rows × columns?” Jennifer asks.</p>
<p>“Because not all cells are independent,” Maria explains. “Once we know:</p>
<ul>
<li>The row totals (600 for Social Media, 800 for Email, etc.)<br>
</li>
<li>The column totals (460 Conversions, 1,229 Clicks, etc.)<br>
</li>
<li>And we fill in all but one cell in each row</li>
</ul>
<p>…the last cell in each row is <strong>determined</strong>. It must make the row total correct.”</p>
<p>David illustrates:</p>
<p>“For Social Media’s 600 impressions:</p>
<ul>
<li>If 147 converted and 312 clicked<br>
</li>
<li>Then No Action <strong>must be</strong> 600 - 147 - 312 = 141</li>
</ul>
<p>We have no freedom to choose that last cell.”</p>
<p>“Same logic applies to columns,” Maria adds. “So the number of ‘free’ cells is:</p>
<ul>
<li>Rows: We can freely choose (r-1) rows, the last is determined<br>
</li>
<li>Columns: We can freely choose (c-1) columns, the last is determined<br>
</li>
<li>Total free choices: (r-1) × (c-1) = degrees of freedom”</li>
</ul>
<p>“For our table: (4-1)(3-1) = 3 × 2 = 6 degrees of freedom”</p>
</section>
<section id="connecting-to-the-hypothesis-test" class="level4">
<h4 class="anchored" data-anchor-id="connecting-to-the-hypothesis-test">Connecting to the Hypothesis Test</h4>
<p>“Now here’s how it all comes together,” David says, pointing to the distribution curve.</p>
<p>“<strong>Under H₀</strong> (independence):</p>
<ul>
<li>Our χ² statistic should be relatively small<br>
</li>
<li>Most of the probability mass is near the mean (df = 6)<br>
</li>
<li>Values much larger than 6 are <strong>rare</strong></li>
</ul>
<p><strong>Our observed χ² = 42.87</strong>:</p>
<ul>
<li>Way out in the right tail<br>
</li>
<li>Far beyond the critical value of 12.59<br>
</li>
<li>Probability of seeing χ² ≥ 42.87 under H₀ is &lt; 0.001</li>
</ul>
<p><strong>Conclusion</strong>: Either:</p>
<ol type="1">
<li>We witnessed an extremely rare event (&lt; 0.1% chance), OR<br>
</li>
<li>H₀ is false—the variables are NOT independent”</li>
</ol>
<p>“We conclude #2,” Maria summarizes. “The data are incompatible with independence.”</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>The Chi-Square Distribution: Key Insights
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>What it is</strong>: A probability distribution for the sum of squared standard normal variables</p>
<p><strong>When we use it</strong>:</p>
<ul>
<li>Testing independence in contingency tables (this lecture)<br>
</li>
<li>Testing goodness of fit (comparing observed to expected distributions)<br>
</li>
<li>Testing variance (comparing sample variance to hypothesized value)</li>
</ul>
<p><strong>Why it works for categorical data</strong>: <span class="math display">\[\chi^2 = \sum \frac{(O - E)^2}{E} = \sum \left(\frac{O - E}{\sqrt{E}}\right)^2 = \sum (\text{standardized deviation})^2\]</span></p>
<ul>
<li>Each term is approximately a squared z-score<br>
</li>
<li>Sum of independent squared z-scores ~ χ²</li>
</ul>
<p><strong>Key properties</strong>:</p>
<ul>
<li>Always non-negative (χ² ≥ 0)<br>
</li>
<li>Right-skewed, especially for small df<br>
</li>
<li>Mean = df, Variance = 2×df<br>
</li>
<li>As df increases, approaches normal distribution</li>
</ul>
<p><strong>Degrees of freedom for contingency tables</strong>: <span class="math display">\[df = (r-1)(c-1)\]</span></p>
<ul>
<li>Accounts for constraints imposed by fixed row and column totals<br>
</li>
<li>Represents number of cells we can freely choose before rest are determined</li>
</ul>
<p><strong>Interpretation</strong>:</p>
<ul>
<li>Small χ² (close to df): Observed ≈ Expected → Consistent with H₀<br>
</li>
<li>Large χ² (far from df): Observed ≠ Expected → Evidence against H₀<br>
</li>
<li>Critical value (at α = 0.05): Threshold beyond which we reject H₀<br>
</li>
</ul>
</div>
</div>
</section>
</section>
<section id="step-4-p-value-and-decision" class="level3">
<h3 class="anchored" data-anchor-id="step-4-p-value-and-decision">Step 4: P-Value and Decision</h3>
<p>Using the chi-square distribution with df = 6: - <strong>Critical value</strong> at α = 0.05: χ²₀.₀₅,₆ = 12.59 - <strong>Test statistic</strong>: χ² = 42.87 - <strong>P-value</strong>: &lt; 0.001</p>
<p><strong>Decision:</strong> Since χ² = 42.87 &gt; 12.59 (or equivalently, p &lt; 0.001 &lt; 0.05), we <strong>reject H₀</strong>.</p>
</section>
<section id="step-5-proper-interpretation" class="level3">
<h3 class="anchored" data-anchor-id="step-5-proper-interpretation">Step 5: Proper Interpretation</h3>
<p>Maria writes out the correct conclusion:</p>
<p><strong>Statistical Conclusion:</strong><br>
“We reject the null hypothesis of independence (χ² = 42.87, df = 6, p &lt; 0.001). The data provide strong evidence that marketing channel and conversion outcome are statistically associated.”</p>
<p><strong>What This Means:</strong><br>
“Conversion patterns differ across channels in ways unlikely to occur if channel and outcome were truly independent. However, this observational study cannot determine whether channel choice causes conversion differences, or whether confounding variables explain the association.”</p>
<p><strong>What We DON’T Know:</strong></p>
<ul>
<li>Whether changing a customer’s channel would change their conversion probability<br>
</li>
<li>Whether product mix, customer intent, or other factors drive both channel exposure and conversion<br>
</li>
<li>Whether the association holds within specific product categories or customer segments</li>
</ul>
<p>“See the difference?” David asks Jennifer’s team. “Same test, same p-value, but we’re not claiming causation. We’re acknowledging association while being honest about limitations.”</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Chi-Square Test Formula and Assumptions
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Test Statistic:</strong> <span class="math display">\[\chi^2 = \sum_{i,j} \frac{(O_{ij} - E_{ij})^2}{E_{ij}}\]</span></p>
<p><strong>Expected Frequency:</strong> <span class="math display">\[E_{ij} = \frac{(\text{Row}_i \text{ Total}) \times (\text{Column}_j \text{ Total})}{\text{Grand Total}}\]</span></p>
<p><strong>Degrees of Freedom:</strong> <span class="math display">\[df = (r-1)(c-1)\]</span> where r = number of rows, c = number of columns</p>
<p><strong>Assumptions:</strong></p>
<ol type="1">
<li><strong>Independent observations</strong>: Each customer counted once<br>
</li>
<li><strong>Random sampling</strong>: Data represents population<br>
</li>
<li><strong>Expected frequencies ≥ 5</strong>: All E_{ij} ≥ 5 (if violated, combine categories)<br>
</li>
<li><strong>Fixed marginal totals</strong>: Row and column totals are treated as fixed</li>
</ol>
<p><strong>Excel Functions:</strong></p>
<pre><code>=CHISQ.TEST(observed_range, expected_range)    ' Returns p-value
=CHISQ.INV.RT(alpha, df)                       ' Returns critical value  
=CHISQ.DIST.RT(chi_square_stat, df)            ' Returns p-value from statistic</code></pre>
<p><strong>Interpretation:</strong></p>
<ul>
<li>Large χ² → Observed frequencies far from expected → Evidence against independence<br>
</li>
<li>Small χ² → Observed frequencies close to expected → Insufficient evidence against independence<br>
</li>
<li>P-value &lt; α → Reject H₀ (conclude association exists)<br>
</li>
<li>P-value ≥ α → Fail to reject H₀ (insufficient evidence of association)</li>
</ul>
</div>
</div>
</section>
</section>
<section id="adding-confidence-intervals-for-proportions" class="level2" data-number="6.7">
<h2 data-number="6.7" class="anchored" data-anchor-id="adding-confidence-intervals-for-proportions"><span class="header-section-number">6.7</span> Adding Confidence Intervals for Proportions</h2>
<p>“Chi-square tells us channels and outcomes are associated,” Maria says. “But it doesn’t quantify conversion rates with uncertainty. For that, we need confidence intervals.”</p>
<section id="conversion-rate-confidence-intervals" class="level3">
<h3 class="anchored" data-anchor-id="conversion-rate-confidence-intervals">Conversion Rate Confidence Intervals</h3>
<p>David calculates 95% CIs for each channel’s conversion rate:</p>
<p><strong>Formula for proportion CI:</strong> <span class="math display">\[\hat{p} \pm z_{\alpha/2} \sqrt{\frac{\hat{p}(1-\hat{p})}{n}}\]</span></p>
<p>where <span class="math inline">\(\hat{p}\)</span> = sample proportion, <span class="math inline">\(z_{0.025}\)</span> = 1.96 for 95% CI</p>
<p><strong>Results:</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Channel</strong></th>
<th style="text-align: left;"><strong>Conversions</strong></th>
<th style="text-align: left;"><strong>Total</strong></th>
<th style="text-align: left;"><strong>Rate</strong></th>
<th style="text-align: left;"><strong>95% CI</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Social Media</td>
<td style="text-align: left;">147</td>
<td style="text-align: left;">600</td>
<td style="text-align: left;">24.5%</td>
<td style="text-align: left;">(21.2%, 27.8%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Email</td>
<td style="text-align: left;">150</td>
<td style="text-align: left;">800</td>
<td style="text-align: left;">18.75%</td>
<td style="text-align: left;">(16.0%, 21.5%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Search Ads</td>
<td style="text-align: left;">89</td>
<td style="text-align: left;">400</td>
<td style="text-align: left;">22.25%</td>
<td style="text-align: left;">(18.2%, 26.3%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Display Ads</td>
<td style="text-align: left;">74</td>
<td style="text-align: left;">600</td>
<td style="text-align: left;">12.3%</td>
<td style="text-align: left;">(9.8%, 14.8%)</td>
</tr>
</tbody>
</table>
<p>“Notice,” Maria points out, “Social Media’s CI (21.2% to 27.8%) doesn’t overlap with Email’s CI (16.0% to 21.5%). That confirms they’re significantly different.”</p>
<p>“But,” David adds, “Social Media’s CI (21.2% to 27.8%) DOES overlap with Search Ads’ CI (18.2% to 26.3%). So while Social Media’s point estimate is higher (24.5% vs 22.25%), we can’t conclusively say Social Media beats Search Ads.”</p>
<p>Jennifer sees the implication: “So recommending we shift budget from Search Ads to Social Media might not be justified?”</p>
<p>“Exactly,” Maria confirms. “The uncertainty overlaps. You’d want more data before concluding Social Media is definitively better.”</p>
</section>
</section>
<section id="cost-effectiveness-the-missing-analysis" class="level2" data-number="6.8">
<h2 data-number="6.8" class="anchored" data-anchor-id="cost-effectiveness-the-missing-analysis"><span class="header-section-number">6.8</span> Cost-Effectiveness: The Missing Analysis</h2>
<p>“But there’s an even bigger problem with the original recommendation,” David says, pulling up a new spreadsheet.</p>
<p>“Your report recommends shifting $150,000 to Social Media because it has the highest conversion rate. But <strong>conversion rate isn’t the only metric that matters</strong>. What about cost-per-conversion?”</p>
<p>Maria displays the cost analysis:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 19%">
<col style="width: 22%">
<col style="width: 17%">
<col style="width: 22%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Channel</strong></th>
<th style="text-align: left;"><strong>Conv Rate</strong></th>
<th style="text-align: left;"><strong>95% CI</strong></th>
<th style="text-align: left;"><strong>Cost/Conv</strong></th>
<th style="text-align: left;"><strong>95% CI</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Email</strong></td>
<td style="text-align: left;">18.75%</td>
<td style="text-align: left;">(16.0%, 21.5%)</td>
<td style="text-align: left;"><strong>$187</strong></td>
<td style="text-align: left;">($168, $206)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Social Media</td>
<td style="text-align: left;">24.5%</td>
<td style="text-align: left;">(21.2%, 27.8%)</td>
<td style="text-align: left;"><strong>$306</strong></td>
<td style="text-align: left;">($275, $337)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Search Ads</td>
<td style="text-align: left;">22.25%</td>
<td style="text-align: left;">(18.2%, 26.3%)</td>
<td style="text-align: left;"><strong>$393</strong></td>
<td style="text-align: left;">($348, $438)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Display Ads</td>
<td style="text-align: left;">12.3%</td>
<td style="text-align: left;">(9.8%, 14.8%)</td>
<td style="text-align: left;"><strong>$703</strong></td>
<td style="text-align: left;">($621, $785)</td>
</tr>
</tbody>
</table>
<p>Jennifer’s eyes widen. “Email has the <strong>lowest</strong> cost-per-conversion at $187, even though it has the lowest conversion rate?”</p>
<p>“Exactly,” David confirms. “Social Media converts at 24.5% vs Email’s 18.75%—that’s 30% better. But Social Media costs $306 per conversion vs Email’s $187—that’s 64% more expensive.”</p>
<p>“So which channel is actually better?” Jennifer asks.</p>
<p>“It depends,” Maria responds, “on:</p>
<ol type="1">
<li><strong>Customer lifetime value (CLV)</strong>: If converted customers are worth $1,000+, paying $306 vs $187 doesn’t matter much<br>
</li>
<li><strong>Scale constraints</strong>: Can Email scale to 10x volume at the same cost?<br>
</li>
<li><strong>Attribution</strong>: Do customers see Social Media ads then convert via Email? (multi-touch attribution)<br>
</li>
<li><strong>Strategic goals</strong>: Are you optimizing for volume (favor Social Media) or efficiency (favor Email)?”</li>
</ol>
<p>“Your original report,” David emphasizes, “recommended a $150,000 shift based solely on conversion rate, ignoring cost-effectiveness entirely. That’s incomplete analysis.”</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>The Danger of Optimizing One Metric
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Original Recommendation (flawed):</strong></p>
<p>“Social Media has highest conversion rate (24.5%) → Shift $150,000 to Social Media”</p>
<p><strong>Problems:</strong></p>
<ol type="1">
<li>Ignores cost-per-conversion ($306 vs Email’s $187)<br>
</li>
<li>Ignores customer lifetime value by channel<br>
</li>
<li>Ignores scale/capacity constraints<br>
</li>
<li>Ignores multi-touch attribution<br>
</li>
<li>Based on 1 quarter of observational data<br>
</li>
<li>Makes causal claims from correlational evidence</li>
</ol>
<p><strong>Better Approach:</strong></p>
<ol type="1">
<li>Calculate cost-per-conversion with confidence intervals<br>
</li>
<li>Estimate CLV by channel (if possible)<br>
</li>
<li>Test sensitivity to confounders (product type, customer segment)<br>
</li>
<li>Run small-scale pilot ($20K) before major reallocation<br>
</li>
<li>Set clear success metrics and evaluation timeline<br>
</li>
<li>Acknowledge observational limitations</li>
</ol>
<p><strong>Recommendation:</strong><br>
“Before reallocating $150,000, conduct a 4-week pilot test with $20,000. Randomly assign 2,000 customers to channels, control for product type, and measure conversion rates, costs, and CLV. Use results to justify larger reallocation.”</p>
</div>
</div>
</section>
<section id="potential-confounding-simpsons-paradox" class="level2" data-number="6.9">
<h2 data-number="6.9" class="anchored" data-anchor-id="potential-confounding-simpsons-paradox"><span class="header-section-number">6.9</span> Potential Confounding: Simpson’s Paradox</h2>
<p>“There’s one more critical issue,” Maria says. “Your analysis doesn’t account for <strong>confounding variables</strong>.”</p>
<section id="the-product-mix-problem" class="level3">
<h3 class="anchored" data-anchor-id="the-product-mix-problem">The Product Mix Problem</h3>
<p>David creates a hypothetical scenario:</p>
<p>“Suppose your client sells two product types:</p>
<ul>
<li><strong>Premium products</strong> (naturally convert at 30%)<br>
</li>
<li><strong>Budget products</strong> (naturally convert at 15%)</li>
</ul>
<p>And suppose your marketing strategy is:</p>
<ul>
<li>Promote premium products mainly on Social Media<br>
</li>
<li>Promote budget products mainly via Email</li>
</ul>
<p><strong>What would happen?</strong>”</p>
<p>He shows the data:</p>
<p><strong>Overall (what you observed):</strong></p>
<ul>
<li>Social Media: 24.5% conversion<br>
</li>
<li>Email: 18.75% conversion<br>
</li>
<li>Conclusion: Social Media appears better</li>
</ul>
<p><strong>Within Premium Products:</strong></p>
<ul>
<li>Social Media: 28% conversion<br>
</li>
<li>Email: 32% conversion<br>
</li>
<li>Conclusion: Email is better!</li>
</ul>
<p><strong>Within Budget Products:</strong></p>
<ul>
<li>Social Media: 14% conversion<br>
</li>
<li>Email: 16% conversion<br>
</li>
<li>Conclusion: Email is better!</li>
</ul>
<p>“This is Simpson’s Paradox,” Maria explains. “Social Media appears better overall, but Email is actually better for BOTH product types. The overall reversal happens because Social Media gets disproportionately assigned to the higher-converting product category.”</p>
<p>Jennifer looks stunned. “So our recommendation to shift to Social Media could be completely backwards?”</p>
<p>“Possibly,” David confirms. “Without controlling for product type, customer intent, time of day, and other confounders, you can’t know if channels genuinely differ or if you’re seeing selection bias.”</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Simpson’s Paradox in Marketing
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Definition:</strong> A trend that appears in overall data reverses when data are separated into subgroups.</p>
<p><strong>Marketing Example:</strong></p>
<ul>
<li><strong>Overall:</strong> Channel A converts at 25%, Channel B at 20% → “A is better”<br>
</li>
<li><strong>Premium products:</strong> A converts at 22%, B at 28% → “B is better”<br>
</li>
<li><strong>Budget products:</strong> A converts at 18%, B at 19% → “B is better”</li>
</ul>
<p><strong>Why It Happens:</strong><br>
Channel A is assigned disproportionately to premium products (which convert better naturally), making A appear better overall even though B outperforms A within each category.</p>
<p><strong>How to Detect:</strong></p>
<ol type="1">
<li>Stratify analysis by potential confounders (product type, customer segment, etc.)<br>
</li>
<li>Check if channel rankings hold within each stratum<br>
</li>
<li>If rankings reverse, you have confounding</li>
</ol>
<p><strong>Implication for PixelPerfect:</strong><br>
Your overall channel rankings might reverse when controlling for:</p>
<ul>
<li>Product category (electronics vs apparel vs home goods)<br>
</li>
<li>Price point (premium vs budget)<br>
</li>
<li>Customer demographics (age, gender, location)<br>
</li>
<li>Time of day (morning vs evening)<br>
</li>
<li>Day of week (weekday vs weekend)</li>
</ul>
<p><strong>Recommendation:</strong> Before implementing $150,000 budget shift, stratify the analysis by product category and customer segment to ensure channel rankings hold within subgroups.</p>
</div>
</div>
</section>
</section>
<section id="the-corrected-report-what-david-and-maria-delivered" class="level2" data-number="6.10">
<h2 data-number="6.10" class="anchored" data-anchor-id="the-corrected-report-what-david-and-maria-delivered"><span class="header-section-number">6.10</span> The Corrected Report: What David and Maria Delivered</h2>
<p>Five days after receiving PixelPerfect’s request, David and Maria present their corrected analysis. Gone are the claims of “causation,” “accepting H₀,” and “99.9% confident.”</p>
<p>Instead, Jennifer sees:</p>
<p><strong>Statistical Findings:</strong></p>
<ul>
<li>Marketing channel and conversion outcome show strong statistical association (χ² = 42.87, df = 6, p &lt; 0.001)<br>
</li>
<li>This means conversion patterns differ across channels in ways unlikely under independence<br>
</li>
<li><strong>However</strong>, observational data cannot determine whether channels cause conversion differences<br>
</li>
<li>Social Media’s conversion rate: 24.5% (95% CI: 21.2%, 27.8%)<br>
</li>
<li>Email’s cost-per-conversion: $187 (95% CI: $168, $206) — lowest among all channels</li>
</ul>
<p><strong>Regional Analysis:</strong></p>
<ul>
<li>Fail to reject hypothesis that regions have equal conversion rates (χ² = 0.90, df = 4, p = 0.64)<br>
</li>
<li>This means: insufficient evidence of regional differences in this dataset<br>
</li>
<li><strong>Does NOT mean</strong> regions are proven equal — could be Type II error or confounding</li>
</ul>
<p><strong>Potential Confounding Factors:</strong></p>
<ul>
<li>Product type may drive both channel selection and conversion (Simpson’s Paradox risk)<br>
</li>
<li>Customer intent likely differs by channel (high-intent vs browsers)<br>
</li>
<li>Selection bias: Different customer demographics across channels<br>
</li>
<li>Temporal factors: Time-of-day, day-of-week effects not controlled</li>
</ul>
<p><strong>Cost-Effectiveness:</strong> | Channel | Conv Rate | Cost/Conv | Efficiency Rank | |:——–|:———-|:———-|:—————-| | Email | 18.75% | $187 | 1st (most efficient) | | Social Media | 24.5% | $306 | 2nd | | Search Ads | 22.25% | $393 | 3rd | | Display Ads | 12.3% | $703 | 4th |</p>
<p><strong>Recommendations:</strong></p>
<ol type="1">
<li><strong>Do NOT implement immediate $150,000 reallocation</strong>
<ul>
<li>Current analysis cannot support causal conclusions<br>
</li>
<li>Confounding factors not controlled<br>
</li>
<li>Cost-effectiveness varies dramatically by channel</li>
</ul></li>
<li><strong>Conduct controlled pilot test</strong>
<ul>
<li>Budget: $20,000 over 4 weeks<br>
</li>
<li>Randomly assign 2,000 customers to channels<br>
</li>
<li>Stratify by product category<br>
</li>
<li>Measure: conversion rate, cost-per-conversion, CLV, multi-touch attribution</li>
</ul></li>
<li><strong>Collect additional data</strong>
<ul>
<li>Product type/category for each interaction<br>
</li>
<li>Customer demographics and intent signals<br>
</li>
<li>Time-of-day and day-of-week patterns<br>
</li>
<li>Multi-touch attribution (customer journey)</li>
</ul></li>
<li><strong>Stratified analysis</strong>
<ul>
<li>Rerun chi-square tests within product categories<br>
</li>
<li>Check for Simpson’s Paradox<br>
</li>
<li>Calculate cost-effectiveness by customer segment</li>
</ul></li>
<li><strong>If pilot succeeds, implement phased rollout</strong>
<ul>
<li>Month 1: Shift $30K, monitor results<br>
</li>
<li>Month 2: If successful, shift another $50K<br>
</li>
<li>Month 3: If still successful, complete reallocation<br>
</li>
<li>Set clear success criteria and decision rules upfront</li>
</ul></li>
</ol>
<p>Jennifer reviews the corrected report carefully. “Three days ago, you recommended I invest $150,000 based on one chi-square test. Now you’re recommending a $20,000 pilot with clear evaluation criteria.”</p>
<p>“That’s right,” Maria confirms. “The first recommendation confused association with causation. The second acknowledges what we know, what we don’t know, and how to learn more.”</p>
<p>Every claim is qualified. Every limitation is acknowledged. Every recommendation accounts for uncertainty.</p>
<p>“This,” Jennifer says, “is analysis I can defend to my client. Not because it gives them the answer they want, but because it gives them the truth about what the data actually show.”</p>
</section>
<section id="connecting-the-complete-statistical-journey" class="level2" data-number="6.11">
<h2 data-number="6.11" class="anchored" data-anchor-id="connecting-the-complete-statistical-journey"><span class="header-section-number">6.11</span> Connecting the Complete Statistical Journey</h2>
<p>As David and Maria pack up, they reflect on their nine-month journey through the EMBA program.</p>
<p>“Five companies, five statistical challenges,” Maria says.</p>
<p><strong>January — TechFlow Solutions:</strong></p>
<ul>
<li><strong>Question</strong>: “What happened in Q4?”<br>
</li>
<li><strong>Tool</strong>: Descriptive statistics<br>
</li>
<li><strong>Lesson</strong>: Calculate exact values, quantify variability, identify outliers<br>
</li>
<li><strong>Error fixed</strong>: “Around” → “Exactly”</li>
</ul>
<p><strong>April — PrecisionCast Industries:</strong></p>
<ul>
<li><strong>Question</strong>: “What will happen in Q2?”<br>
</li>
<li><strong>Tool</strong>: Probability distributions<br>
</li>
<li><strong>Lesson</strong>: Model uncertainty, calculate expected values, understand distributions<br>
</li>
<li><strong>Error fixed</strong>: “Pretty good” → “95% sensitivity, 49.6% PPV”</li>
</ul>
<p><strong>July — BorderMed Pharmaceuticals:</strong></p>
<ul>
<li><strong>Question</strong>: “What can we conclude?”<br>
</li>
<li><strong>Tool</strong>: Statistical inference<br>
</li>
<li><strong>Lesson</strong>: Quantify uncertainty, test hypotheses, acknowledge Type I/II errors<br>
</li>
<li><strong>Error fixed</strong>: “Proves efficacy” → “95% CI: 10.6 to 14.2 mmHg”</li>
</ul>
<p><strong>September — Desert Vine Hospitality (Lecture 4 - ANOVA):</strong></p>
<ul>
<li><strong>Question</strong>: “Do groups differ?”<br>
</li>
<li><strong>Tool</strong>: Analysis of variance<br>
</li>
<li><strong>Lesson</strong>: Compare multiple groups, control family-wise error, interpret post-hoc tests</li>
</ul>
<p><strong>October — PixelPerfect Marketing:</strong></p>
<ul>
<li><strong>Question</strong>: “Are categories related?”<br>
</li>
<li><strong>Tool</strong>: Chi-square tests<br>
</li>
<li><strong>Lesson</strong>: Association ≠ causation, never “accept H₀”, interpret p-values correctly<br>
</li>
<li><strong>Error fixed</strong>: “Causes differences” → “Shows association; causation unclear”</li>
</ul>
<p>“Five different questions,” David observes. “Five different statistical approaches. But they all share the same foundation.”</p>
<p>Maria nods. “Every analysis requires:</p>
<ol type="1">
<li><strong>Precision over vagueness</strong>: Calculate exact values, not approximations<br>
</li>
<li><strong>Quantified uncertainty</strong>: Confidence intervals, p-values, power analysis<br>
</li>
<li><strong>Honest limitations</strong>: Acknowledge what you don’t know<br>
</li>
<li><strong>Proper interpretation</strong>: Say what the test actually shows, not what you wish it showed<br>
</li>
<li><strong>Business context</strong>: Connect statistics to decisions”</li>
</ol>
<p>“And,” David adds, “they all transform the same fundamental problem: leaders who need to make decisions saying ‘seems,’ ‘pretty good,’ ‘around,’ ‘proves,’ ‘causes’—and us turning that into ‘statistically significant association,’ ‘fails to reject,’ ‘95% confidence interval,’ and ‘insufficient evidence to determine causation.’”</p>
<p>The journey from vague to precise. From overconfident to appropriately uncertain. From amateur interpretation to professional statistical reasoning.</p>
<p>That’s what these nine months taught them. And that’s what they’ll carry into their careers as data-driven business leaders.</p>
<div class="callout callout-style-simple callout-note no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><em>Categorical data analysis completes your core statistical toolkit. Combined with descriptive statistics, probability, inference, and ANOVA, you now have the methods to analyze any business data—continuous, discrete, or categorical. The key is not just running the tests correctly, but interpreting results honestly, acknowledging limitations transparently, and making recommendations that account for uncertainty.</em></p>
</div>
</div>
</div>
</section>
<section id="looking-ahead-the-limits-of-what-weve-learned" class="level2" data-number="6.12">
<h2 data-number="6.12" class="anchored" data-anchor-id="looking-ahead-the-limits-of-what-weve-learned"><span class="header-section-number">6.12</span> Looking Ahead: The Limits of What We’ve Learned</h2>
<p>As David and Maria finish their PixelPerfect presentation, Jennifer asks one final question.</p>
<p>“This has been incredibly helpful,” she says. “But I’m curious—with all these statistical tools we’ve learned, descriptive statistics, probability, inference, ANOVA, chi-square—can we predict exactly how much a customer will spend based on their demographics and behavior?”</p>
<p>David and Maria exchange glances. “That’s a great question,” Maria responds. “And it reveals something important about what we’ve learned so far.”</p>
<section id="the-five-lectures-comparing-not-predicting" class="level3">
<h3 class="anchored" data-anchor-id="the-five-lectures-comparing-not-predicting">The Five Lectures: Comparing, Not Predicting</h3>
<p>David pulls up their statistical journey summary one more time:</p>
<p>“Look at what all five lectures have in common,” he says, pointing to the table:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 18%">
<col style="width: 20%">
<col style="width: 28%">
<col style="width: 31%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Lecture</strong></th>
<th style="text-align: left;"><strong>Question</strong></th>
<th style="text-align: left;"><strong>What We Can Do</strong></th>
<th style="text-align: left;"><strong>What We Can’t Do</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1: Descriptive</td>
<td style="text-align: left;">“What happened?”</td>
<td style="text-align: left;">Describe center, spread, shape</td>
<td style="text-align: left;">Predict individual values</td>
</tr>
<tr class="even">
<td style="text-align: left;">2: Probability</td>
<td style="text-align: left;">“What will happen?”</td>
<td style="text-align: left;">Calculate probabilities, expected values</td>
<td style="text-align: left;">Predict precise outcomes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3: Inference</td>
<td style="text-align: left;">“What can we conclude?”</td>
<td style="text-align: left;">Test hypotheses, build CIs</td>
<td style="text-align: left;">Predict individual responses</td>
</tr>
<tr class="even">
<td style="text-align: left;">4: ANOVA</td>
<td style="text-align: left;">“Do groups differ?”</td>
<td style="text-align: left;">Compare group means</td>
<td style="text-align: left;">Predict individual measurements</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5: Chi-Square</td>
<td style="text-align: left;">“Are categories related?”</td>
<td style="text-align: left;">Test independence, association</td>
<td style="text-align: left;">Predict individual classifications</td>
</tr>
</tbody>
</table>
<p>“Notice the pattern,” Maria adds. “Every method we’ve used answers comparative questions:</p>
<ul>
<li>Is this group different from that group?<br>
</li>
<li>Is this variable associated with that variable?<br>
</li>
<li>Is this mean significantly different from zero?<br>
</li>
<li>Do these categories occur together more than by chance?”</li>
</ul>
<p>“But none of them,” David emphasizes, “answer predictive questions like:</p>
<ul>
<li><strong>How much</strong> will Customer #2,401 spend?<br>
</li>
<li><strong>Exactly what</strong> conversion rate should we expect if we spend $50,000 on Social Media?<br>
</li>
<li><strong>Which specific</strong> customers should we target to maximize ROI?<br>
</li>
<li><strong>How does</strong> customer lifetime value <strong>change</strong> as we increase ad frequency?”</li>
</ul>
<p>Jennifer leans forward. “So all this statistical analysis we’ve done… we still can’t predict?”</p>
<p>“Correct,” Maria confirms. “We can compare. We can test. We can describe associations. But we can’t build a <strong>prediction model</strong>.”</p>
</section>
<section id="the-fundamental-limitation-categories-and-comparisons" class="level3">
<h3 class="anchored" data-anchor-id="the-fundamental-limitation-categories-and-comparisons">The Fundamental Limitation: Categories and Comparisons</h3>
<p>David explains the core issue:</p>
<p>“Think about what PixelPerfect’s chi-square test told us. Channel and conversion are associated. Social Media converts at 24.5%, Email at 18.75%. Great—we compared categories.”</p>
<p>“But suppose Jennifer asks: ‘If we increase Social Media budget by $10,000, how many additional conversions should we expect?’ The chi-square test can’t answer that. It tells us channels differ, not <strong>by how much</strong> outcomes change when we change inputs.”</p>
<p>Maria adds another example: “Or suppose she asks: ‘Can we predict which specific customers will convert based on their demographics, browsing behavior, and channel exposure?’ Chi-square tells us these variables are associated, but it doesn’t give us a prediction equation.”</p>
<p>“That’s because,” David continues, “everything we’ve learned treats variables as <strong>categories</strong> or <strong>groups to compare</strong>:</p>
<ul>
<li>TechFlow: Compare Product A vs Product B vs Product C vs Product D<br>
</li>
<li>PrecisionCast: Compare defective vs non-defective<br>
</li>
<li>BorderMed: Compare treatment vs control (or sites)<br>
</li>
<li>PixelPerfect: Compare Social Media vs Email vs Display vs Search”</li>
</ul>
<p>“But in the real world,” Maria says, “many business variables are <strong>continuous and related</strong>:</p>
<ul>
<li>Advertising spend (dollars) → Conversions (count)<br>
</li>
<li>Customer age (years) → Purchase amount (dollars)<br>
</li>
<li>Website visits (count) → Conversion probability (0-1)<br>
</li>
<li>Product price (dollars) → Sales volume (units)”</li>
</ul>
<p>“To model those relationships,” David concludes, “we need a different tool. We need <strong>regression analysis</strong>.”</p>
</section>
<section id="what-regression-analysis-adds" class="level3">
<h3 class="anchored" data-anchor-id="what-regression-analysis-adds">What Regression Analysis Adds</h3>
<p>Maria creates a new comparison:</p>
<p><strong>What We’ve Learned (Lectures 1-5): Statistical Comparison</strong></p>
<ul>
<li>Compare groups: Is Group A different from Group B?<br>
</li>
<li>Test associations: Are Variable X and Variable Y related?<br>
</li>
<li>Quantify uncertainty: What’s the confidence interval for the difference?<br>
</li>
<li>Make binary decisions: Reject H₀ or fail to reject?</li>
</ul>
<p><strong>What’s Missing: Statistical Prediction</strong></p>
<ul>
<li>Model relationships: <strong>How does</strong> Y change when X changes?<br>
</li>
<li>Quantify effects: For every $1 increase in ad spend, conversions increase by ___<br>
</li>
<li>Make predictions: <strong>What value</strong> of Y should we expect when X = 100?<br>
</li>
<li>Control for confounders: What’s the effect of X on Y <strong>holding Z constant</strong>?<br>
</li>
<li>Optimize decisions: What value of X <strong>maximizes</strong> Y?</li>
</ul>
<p>“Chi-square told us channel and conversion are associated,” David explains. “Regression will tell us <strong>how much</strong> conversion rates change when we shift from one channel to another, <strong>controlling for</strong> product type and demographics.”</p>
<p>“ANOVA told us that sites differ in blood pressure reduction,” Maria adds. “Regression will tell us <strong>how much</strong> blood pressure decreases for each additional mg of medication dosage, <strong>while accounting for</strong> patient age and baseline BP.”</p>
<p>Jennifer’s eyes light up. “So regression lets us build prediction models?”</p>
<p>“Exactly,” David confirms. “And that’s Lecture 6.”</p>
</section>
<section id="the-statistical-toolkit-complete-vs.-comprehensive" class="level3">
<h3 class="anchored" data-anchor-id="the-statistical-toolkit-complete-vs.-comprehensive">The Statistical Toolkit: Complete vs.&nbsp;Comprehensive</h3>
<p>Maria draws a final distinction:</p>
<p>“The toolkit you have now—descriptive statistics through chi-square—is <strong>complete</strong> for statistical comparison and testing:</p>
<ul>
<li>You can describe any data<br>
</li>
<li>You can test any hypothesis about group differences<br>
</li>
<li>You can quantify uncertainty for any estimate<br>
</li>
<li>You can evaluate associations between any categorical variables”</li>
</ul>
<p>“But,” David adds, “your toolkit isn’t yet <strong>comprehensive</strong> for business analytics:</p>
<ul>
<li>You can’t predict individual outcomes<br>
</li>
<li>You can’t model continuous relationships<br>
</li>
<li>You can’t control for multiple variables simultaneously<br>
</li>
<li>You can’t optimize decisions based on predicted outcomes”</li>
</ul>
<p>“Regression analysis,” Maria concludes, “completes your transition from <strong>statistical analyst</strong> to <strong>business analyst</strong>. From answering ‘Are these groups different?’ to answering ‘What should we expect to happen, and how can we optimize outcomes?’”</p>
</section>
<section id="the-bridge-to-lecture-6" class="level3">
<h3 class="anchored" data-anchor-id="the-bridge-to-lecture-6">The Bridge to Lecture 6</h3>
<p>“So here’s what happens next,” David says to Jennifer. “You now know:</p>
<ul>
<li>PixelPerfect’s channels are <strong>associated</strong> with conversion outcomes (chi-square)<br>
</li>
<li>Email is the most cost-effective channel (cost-per-conversion analysis)<br>
</li>
<li>You should test for confounding before recommending budget shifts (Simpson’s Paradox)”</li>
</ul>
<p>“But you still don’t know:” Maria continues: - <strong>How many</strong> conversions to expect if you spend $X on each channel<br>
- <strong>Which customers</strong> are most likely to convert based on demographics + behavior<br>
- <strong>What mix</strong> of channels maximizes conversions for a given budget<br>
- <strong>How</strong> conversion rates change as you scale up channel spending”</p>
<p>“To answer those questions,” David says, “you need regression analysis. That’s Lecture 6: <strong>Building prediction models and quantifying relationships between continuous variables</strong>.”</p>
<p>Jennifer nods slowly. “So we’ve learned to test and compare. Now we learn to predict and optimize.”</p>
<p>“Exactly,” Maria confirms. “And that’s when statistics becomes truly powerful for business decision-making.”</p>
<div class="callout callout-style-simple callout-note no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>The Journey Continues:</strong></p>
<p><strong>Lectures 1-5:</strong> Statistical <strong>comparison</strong> and <strong>testing</strong></p>
<ul>
<li>Descriptive statistics: Describe data precisely<br>
</li>
<li>Probability: Model uncertainty<br>
</li>
<li>Inference: Generalize from samples honestly<br>
</li>
<li>ANOVA: Compare multiple groups<br>
</li>
<li>Chi-square: Test categorical associations</li>
</ul>
<p><strong>Lecture 6:</strong> Statistical <strong>prediction</strong> and <strong>modeling</strong></p>
<ul>
<li>Simple regression: Model relationships between two variables<br>
</li>
<li>Multiple regression: Control for confounders, predict outcomes<br>
</li>
<li>Regression diagnostics: Validate model assumptions<br>
</li>
<li>Business applications: Optimize decisions using predictive models</li>
</ul>
<p>The toolkit isn’t complete yet. But you’re ready for the next level.</p>
</div>
</div>
</div>
</section>
</section>
<section id="practice-problems" class="level2" data-number="6.13">
<h2 data-number="6.13" class="anchored" data-anchor-id="practice-problems"><span class="header-section-number">6.13</span> Practice Problems</h2>
<p>Now it’s your turn to apply categorical data analysis using the PixelPerfect Marketing dataset.</p>
<p>🔢 <strong>Download the dataset</strong>: Get <code>PixelPerfect_Q3_2025.xlsx</code> from your course materials.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>About This Dataset
</div>
</div>
<div class="callout-body-container callout-body">
<p>The dataset contains 2,400 customer interactions from PixelPerfect’s Q3 2025 campaign:</p>
<ul>
<li><strong>Marketing Channel</strong>: Social Media, Email, Display Ads, Search Ads</li>
<li><strong>Outcome</strong>: Conversion, Click, No Action</li>
<li><strong>Demographics</strong>: Gender (Male, Female), Age Group (18-34, 35-54, 55+)</li>
<li><strong>Region</strong>: West, Central, East</li>
<li><strong>Product Category</strong>: Electronics, Apparel, Home Goods</li>
</ul>
<p><strong>Use this data</strong> to complete the problems below.</p>
</div>
</div>
<section id="problem-1-chi-square-test-of-independence-30-points" class="level3">
<h3 class="anchored" data-anchor-id="problem-1-chi-square-test-of-independence-30-points">Problem 1: Chi-Square Test of Independence (30 points)</h3>
<p><strong>Background</strong>: The marketing team wants to know if conversion outcome depends on customer gender.</p>
<p><strong>Required</strong>:</p>
<ol type="a">
<li>Create a contingency table with Gender (rows) and Outcome (columns)</li>
<li>Calculate expected frequencies for each cell under independence</li>
<li>Verify all expected frequencies ≥ 5</li>
<li>Calculate the chi-square test statistic</li>
<li>Determine degrees of freedom and critical value (α = 0.05)</li>
<li>Calculate p-value using Excel’s <code>CHISQ.TEST</code> function</li>
<li>State your statistical conclusion (reject or fail to reject H₀)</li>
<li>Write a 2-3 sentence <strong>correct</strong> interpretation (avoid claiming causation)</li>
</ol>
<p><strong>Excel Hints:</strong></p>
<pre><code>=COUNTIFS(Gender_range, "Male", Outcome_range, "Conversion")   ' Observed frequencies
=CHISQ.TEST(observed_range, expected_range)                    ' P-value</code></pre>
</section>
<section id="problem-2-conversion-rate-confidence-intervals-25-points" class="level3">
<h3 class="anchored" data-anchor-id="problem-2-conversion-rate-confidence-intervals-25-points">Problem 2: Conversion Rate Confidence Intervals (25 points)</h3>
<p><strong>Background</strong>: Calculate 95% confidence intervals for conversion rates by age group.</p>
<p><strong>Required</strong>:</p>
<ol type="a">
<li>Calculate conversion rate for each age group (18-34, 35-54, 55+)</li>
<li>Calculate 95% confidence interval for each conversion rate</li>
<li>Identify which age groups have non-overlapping CIs (indicating significant differences)</li>
<li>Create a visualization showing point estimates and CIs</li>
<li>Write 3-4 sentences interpreting: Which age groups convert significantly differently? What are the business implications?</li>
</ol>
<p><strong>Formula:</strong> <span class="math display">\[\hat{p} \pm 1.96 \sqrt{\frac{\hat{p}(1-\hat{p})}{n}}\]</span></p>
</section>
<section id="problem-3-testing-for-confounding-30-points" class="level3">
<h3 class="anchored" data-anchor-id="problem-3-testing-for-confounding-30-points">Problem 3: Testing for Confounding (30 points)</h3>
<p><strong>Background</strong>: Check whether product category confounds the channel-outcome relationship (Simpson’s Paradox).</p>
<p><strong>Required</strong>:</p>
<ol type="a">
<li>Calculate overall conversion rates by channel (all products combined)</li>
<li>Calculate conversion rates by channel <strong>within Electronics category only</strong></li>
<li>Calculate conversion rates by channel <strong>within Apparel category only</strong></li>
<li>Compare rankings: Do channels rank the same overall vs within categories?</li>
<li>Conduct chi-square test for channel×outcome independence within each product category</li>
<li>Write 4-5 sentences: Is there evidence of confounding? Do recommendations change when controlling for product category?</li>
</ol>
</section>
<section id="problem-4-the-regional-analysis-revisited-15-points" class="level3">
<h3 class="anchored" data-anchor-id="problem-4-the-regional-analysis-revisited-15-points">Problem 4: The Regional Analysis Revisited (15 points)</h3>
<p><strong>Background</strong>: The original report claimed “we accept H₀” for regional differences (p = 0.64).</p>
<p><strong>Required</strong>:</p>
<ol type="a">
<li>Conduct chi-square test for Region × Outcome independence</li>
<li>Calculate the p-value</li>
<li>Explain why “we accept H₀ that regions are equal” is <strong>incorrect</strong> language</li>
<li>Provide the <strong>correct</strong> interpretation of p = 0.64</li>
<li>List three possible reasons for a non-significant result</li>
<li>Write 2-3 sentences: Should PixelPerfect conclude regions don’t matter? Why or why not?</li>
</ol>
<hr>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Common Mistakes to Avoid
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Association vs.&nbsp;Causation:</strong> ❌ “Chi-square proves that channel causes conversion differences” ✅ “Chi-square shows channel and conversion are statistically associated; causation cannot be inferred from observational data”</p>
<p><strong>Accepting H₀:</strong> ❌ “p = 0.64, so we accept H₀. Regions have equal conversion rates.” ✅ “p = 0.64, so we fail to reject H₀. Insufficient evidence that regional conversion rates differ.”</p>
<p><strong>P-Value Interpretation:</strong> ❌ “p &lt; 0.001 means we’re 99.9% confident the finding is correct” ✅ “p &lt; 0.001 provides strong evidence against H₀; these data would be very unlikely if variables were truly independent”</p>
<p><strong>Confidence Intervals:</strong> ❌ Reporting point estimates without CIs ✅ Always report: “Social Media: 24.5% (95% CI: 21.2%, 27.8%)”</p>
<p><strong>Cost-Effectiveness:</strong> ❌ Recommending channels based solely on conversion rate ✅ Considering both conversion rate AND cost-per-conversion</p>
<p><strong>Confounding:</strong> ❌ Ignoring potential confounders in observational data ✅ Stratifying analysis by product category, demographics, etc.</p>
</div>
</div>
<hr>
</section>
<section id="submission-requirements" class="level3">
<h3 class="anchored" data-anchor-id="submission-requirements">Submission Requirements</h3>
<p>Submit the following:</p>
<ol type="1">
<li><label><input type="checkbox">Excel workbook with all calculations clearly labeled</label></li>
<li><label><input type="checkbox">Written report (3-4 pages) with:</label>
<ul>
<li>Statistical findings (test statistics, p-values, CIs)</li>
<li>Proper interpretations (avoiding common errors)</li>
<li>Business recommendations</li>
<li>Acknowledgment of limitations</li>
</ul></li>
<li><label><input type="checkbox">Ensure all formulas are visible and documented</label></li>
</ol>
<hr>
</section>
<section id="additional-resources" class="level3">
<h3 class="anchored" data-anchor-id="additional-resources">Additional Resources</h3>
<ul>
<li><strong>Lecture 5 Notes</strong>: Review chi-square formulas and interpretation guidelines</li>
<li><strong>Textbook</strong>: Chapter 12 (Categorical Data Analysis)</li>
<li><strong>Excel Functions</strong>: <code>CHISQ.TEST</code>, <code>CHISQ.DIST.RT</code>, <code>CHISQ.INV.RT</code>, <code>COUNTIFS</code></li>
<li><strong>Office Hours</strong>: [Insert your office hours]</li>
</ul>
<hr>
<p><strong>Total Points: 100</strong></p>
<p>Good luck! Remember: The hardest part of categorical data analysis isn’t the math—it’s the interpretation. Focus on saying what the tests actually show, acknowledging what they don’t show, and avoiding overconfident claims from observational data.</p>
<hr>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/ncachanosky\.github\.io\/XQMB-5311");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./chapter_04.html" class="pagination-link" aria-label="ANOVA: Analysis of Variance">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">ANOVA: Analysis of Variance</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./chapter_06.html" class="pagination-link" aria-label="Statistical Foundations Review: From Description to Decision">
        <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Statistical Foundations Review: From Description to Decision</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© Nicolas Cachanosky, The University of Texas at El Paso, Center for Free Enterprise</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/ncachanosky/XQMB-5311/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link active" href="https://github.com/ncachanosky/XQMB-5311" aria-current="page">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/ncachanosky">
      <i class="bi bi-linkedin" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com/n_cachanosky">
      <i class="bi bi-twitter-x" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




<script src="site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>