<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="Course readings for XQMB 5311 – Statistics for Business – The University of Texas at El Paso.">

<title>7&nbsp; Statistical Foundations Review: From Description to Decision – The Precision Advantage: Statistics for Business</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./chapter_07.html" rel="next">
<link href="./chapter_05.html" rel="prev">
<link href="./favicon.png" rel="icon" type="image/png">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-065a5179aebd64318d7ea99d77b64a9e.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-969ddfa49e00a70eb3423444dbc81f6c.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-065a5179aebd64318d7ea99d77b64a9e.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-224b48a91c0f626bf087add3423f4096.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark-8fba65ec5d79e9223d5579f32ee5f772.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="site_libs/bootstrap/bootstrap-224b48a91c0f626bf087add3423f4096.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>


<link rel="stylesheet" href="https://raw.github.com/ncachanosky/EO-styles/main/styles.css">
<meta property="og:title" content="The Precision Advantage: Statistics for Business">
<meta property="og:description" content="Course readings for XQMB 5311 – Quantitative Methods for Business – The University of Texas at El Paso. An institutions-first treatment of monetary and financial economics.">
<meta property="og:image" content="https://ncachanosky.github.io/XQMB-5311/assets/logo.png">
<meta property="og:site_name" content="The Precision Advantage: Statistics for Business">
<meta property="og:image:height" content="1687">
<meta property="og:image:width" content="1687">
<meta name="twitter:title" content="Money, The Precision Advantage: Statistics for Business">
<meta name="twitter:description" content="Course readings for ECON 3320 – Quantitative Methods for Business – The University of Texas at El Paso. An institutions-first treatment of monetary and financial economics.">
<meta name="twitter:image" content="https://ncachanosky.github.io/XQMB-5311/assets/logo.png">
<meta name="twitter:creator" content="@n_cachanosky">
<meta name="twitter:card" content="summary">
<meta name="twitter:image-height" content="1687">
<meta name="twitter:image-width" content="1687">
</head>

<body class="nav-sidebar docked quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./chapter_06.html"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Statistical Foundations Review: From Description to Decision</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="./index.html" class="sidebar-logo-link">
      <img src="./assets/logo.png" alt="" class="sidebar-logo light-content py-0 d-lg-inline d-none">
      <img src="./assets/logo.png" alt="" class="sidebar-logo dark-content py-0 d-lg-inline d-none">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="./">The Precision Advantage: Statistics for Business</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/ncachanosky/XQMB-5311" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter_01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Descriptive Statistics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter_02.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Probability</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter_03.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Interval Estimation and Hypothesis Testing</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter_04.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">ANOVA: Analysis of Variance</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter_05.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Categorical Data Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter_06.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Statistical Foundations Review: From Description to Decision</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter_07.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Regression Analysis: Introduction to Econometrics</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#learning-objectives" id="toc-learning-objectives" class="nav-link active" data-scroll-target="#learning-objectives">Learning Objectives</a></li>
  <li><a href="#introduction-the-journey-back-to-campus" id="toc-introduction-the-journey-back-to-campus" class="nav-link" data-scroll-target="#introduction-the-journey-back-to-campus"><span class="header-section-number">7.1</span> Introduction: The Journey Back to Campus</a></li>
  <li><a href="#the-statistical-progression-a-framework-for-business-analysis" id="toc-the-statistical-progression-a-framework-for-business-analysis" class="nav-link" data-scroll-target="#the-statistical-progression-a-framework-for-business-analysis"><span class="header-section-number">7.2</span> The Statistical Progression: A Framework for Business Analysis</a></li>
  <li><a href="#lecture-1-review-descriptive-statisticsprecision-over-vagueness" id="toc-lecture-1-review-descriptive-statisticsprecision-over-vagueness" class="nav-link" data-scroll-target="#lecture-1-review-descriptive-statisticsprecision-over-vagueness"><span class="header-section-number">7.3</span> Lecture 1 Review: Descriptive Statistics—Precision Over Vagueness</a>
  <ul class="collapse">
  <li><a href="#the-core-lesson-descriptive-statistics-tell-you-exactly-what-happened" id="toc-the-core-lesson-descriptive-statistics-tell-you-exactly-what-happened" class="nav-link" data-scroll-target="#the-core-lesson-descriptive-statistics-tell-you-exactly-what-happened">The Core Lesson: Descriptive Statistics Tell You <em>Exactly</em> What Happened</a></li>
  <li><a href="#a-students-question-when-do-i-use-mean-vs.-median" id="toc-a-students-question-when-do-i-use-mean-vs.-median" class="nav-link" data-scroll-target="#a-students-question-when-do-i-use-mean-vs.-median">A Student’s Question: “When Do I Use Mean vs.&nbsp;Median?”</a></li>
  <li><a href="#common-pitfalls-in-descriptive-statistics" id="toc-common-pitfalls-in-descriptive-statistics" class="nav-link" data-scroll-target="#common-pitfalls-in-descriptive-statistics">Common Pitfalls in Descriptive Statistics</a></li>
  <li><a href="#key-takeaway-descriptive-statistics" id="toc-key-takeaway-descriptive-statistics" class="nav-link" data-scroll-target="#key-takeaway-descriptive-statistics">Key Takeaway: Descriptive Statistics</a></li>
  </ul></li>
  <li><a href="#lecture-2-review-probabilityquantifying-uncertainty" id="toc-lecture-2-review-probabilityquantifying-uncertainty" class="nav-link" data-scroll-target="#lecture-2-review-probabilityquantifying-uncertainty"><span class="header-section-number">7.4</span> Lecture 2 Review: Probability—Quantifying Uncertainty</a>
  <ul class="collapse">
  <li><a href="#the-core-lesson-probability-converts-uncertainty-into-decisions" id="toc-the-core-lesson-probability-converts-uncertainty-into-decisions" class="nav-link" data-scroll-target="#the-core-lesson-probability-converts-uncertainty-into-decisions">The Core Lesson: Probability Converts Uncertainty into Decisions</a></li>
  <li><a href="#a-students-question-whats-the-difference-between-probability-and-statistics" id="toc-a-students-question-whats-the-difference-between-probability-and-statistics" class="nav-link" data-scroll-target="#a-students-question-whats-the-difference-between-probability-and-statistics">A Student’s Question: “What’s the Difference Between Probability and Statistics?”</a></li>
  <li><a href="#common-pitfalls-in-probability" id="toc-common-pitfalls-in-probability" class="nav-link" data-scroll-target="#common-pitfalls-in-probability">Common Pitfalls in Probability</a></li>
  <li><a href="#the-expected-value-decision-framework" id="toc-the-expected-value-decision-framework" class="nav-link" data-scroll-target="#the-expected-value-decision-framework">The Expected Value Decision Framework</a></li>
  </ul></li>
  <li><a href="#lecture-3-review-statistical-inferenceacknowledging-what-we-dont-know" id="toc-lecture-3-review-statistical-inferenceacknowledging-what-we-dont-know" class="nav-link" data-scroll-target="#lecture-3-review-statistical-inferenceacknowledging-what-we-dont-know"><span class="header-section-number">7.5</span> Lecture 3 Review: Statistical Inference—Acknowledging What We Don’t Know</a>
  <ul class="collapse">
  <li><a href="#the-core-lesson-sample-statistics-population-parameters" id="toc-the-core-lesson-sample-statistics-population-parameters" class="nav-link" data-scroll-target="#the-core-lesson-sample-statistics-population-parameters">The Core Lesson: Sample Statistics ≠ Population Parameters</a></li>
  <li><a href="#a-students-question-what-does-95-confidence-mean" id="toc-a-students-question-what-does-95-confidence-mean" class="nav-link" data-scroll-target="#a-students-question-what-does-95-confidence-mean">A Student’s Question: “What Does 95% Confidence Mean?”</a></li>
  <li><a href="#common-pitfalls-in-statistical-inference" id="toc-common-pitfalls-in-statistical-inference" class="nav-link" data-scroll-target="#common-pitfalls-in-statistical-inference">Common Pitfalls in Statistical Inference</a></li>
  <li><a href="#the-asymmetry-of-hypothesis-testing" id="toc-the-asymmetry-of-hypothesis-testing" class="nav-link" data-scroll-target="#the-asymmetry-of-hypothesis-testing">The Asymmetry of Hypothesis Testing</a></li>
  </ul></li>
  <li><a href="#lecture-4-review-anovacomparing-multiple-groups-simultaneously" id="toc-lecture-4-review-anovacomparing-multiple-groups-simultaneously" class="nav-link" data-scroll-target="#lecture-4-review-anovacomparing-multiple-groups-simultaneously"><span class="header-section-number">7.6</span> Lecture 4 Review: ANOVA—Comparing Multiple Groups Simultaneously</a>
  <ul class="collapse">
  <li><a href="#the-core-lesson-multiple-comparisons-inflate-error-rates" id="toc-the-core-lesson-multiple-comparisons-inflate-error-rates" class="nav-link" data-scroll-target="#the-core-lesson-multiple-comparisons-inflate-error-rates">The Core Lesson: Multiple Comparisons Inflate Error Rates</a></li>
  <li><a href="#a-students-question-what-does-the-f-statistic-tell-me" id="toc-a-students-question-what-does-the-f-statistic-tell-me" class="nav-link" data-scroll-target="#a-students-question-what-does-the-f-statistic-tell-me">A Student’s Question: “What Does the F-Statistic Tell Me?”</a></li>
  <li><a href="#common-pitfalls-in-anova" id="toc-common-pitfalls-in-anova" class="nav-link" data-scroll-target="#common-pitfalls-in-anova">Common Pitfalls in ANOVA</a></li>
  <li><a href="#when-to-use-anova-vs.-multiple-t-tests" id="toc-when-to-use-anova-vs.-multiple-t-tests" class="nav-link" data-scroll-target="#when-to-use-anova-vs.-multiple-t-tests">When to Use ANOVA vs.&nbsp;Multiple t-Tests</a></li>
  </ul></li>
  <li><a href="#lecture-5-review-categorical-data-analysisassociation-causation" id="toc-lecture-5-review-categorical-data-analysisassociation-causation" class="nav-link" data-scroll-target="#lecture-5-review-categorical-data-analysisassociation-causation"><span class="header-section-number">7.7</span> Lecture 5 Review: Categorical Data Analysis—Association ≠ Causation</a>
  <ul class="collapse">
  <li><a href="#the-core-lesson-statistical-association-does-not-establish-causation" id="toc-the-core-lesson-statistical-association-does-not-establish-causation" class="nav-link" data-scroll-target="#the-core-lesson-statistical-association-does-not-establish-causation">The Core Lesson: Statistical Association Does Not Establish Causation</a></li>
  <li><a href="#a-students-question-why-cant-i-say-causes-if-its-significant" id="toc-a-students-question-why-cant-i-say-causes-if-its-significant" class="nav-link" data-scroll-target="#a-students-question-why-cant-i-say-causes-if-its-significant">A Student’s Question: “Why Can’t I Say ‘Causes’ If It’s Significant?”</a></li>
  <li><a href="#common-pitfalls-in-categorical-data-analysis" id="toc-common-pitfalls-in-categorical-data-analysis" class="nav-link" data-scroll-target="#common-pitfalls-in-categorical-data-analysis">Common Pitfalls in Categorical Data Analysis</a></li>
  <li><a href="#the-recommended-approach-pilot-study" id="toc-the-recommended-approach-pilot-study" class="nav-link" data-scroll-target="#the-recommended-approach-pilot-study">The Recommended Approach: Pilot Study</a></li>
  </ul></li>
  <li><a href="#the-mistakes-we-almost-made-a-candid-reflection" id="toc-the-mistakes-we-almost-made-a-candid-reflection" class="nav-link" data-scroll-target="#the-mistakes-we-almost-made-a-candid-reflection"><span class="header-section-number">7.8</span> The Mistakes We Almost Made: A Candid Reflection</a>
  <ul class="collapse">
  <li><a href="#mistake-1-treating-calculations-as-understanding" id="toc-mistake-1-treating-calculations-as-understanding" class="nav-link" data-scroll-target="#mistake-1-treating-calculations-as-understanding">Mistake #1: Treating Calculations as Understanding</a></li>
  <li><a href="#mistake-2-confusing-correct-with-appropriate" id="toc-mistake-2-confusing-correct-with-appropriate" class="nav-link" data-scroll-target="#mistake-2-confusing-correct-with-appropriate">Mistake #2: Confusing “Correct” with “Appropriate”</a></li>
  <li><a href="#mistake-3-overconfidence-in-our-conclusions" id="toc-mistake-3-overconfidence-in-our-conclusions" class="nav-link" data-scroll-target="#mistake-3-overconfidence-in-our-conclusions">Mistake #3: Overconfidence in Our Conclusions</a></li>
  <li><a href="#mistake-4-accepting-results-that-confirmed-our-priors" id="toc-mistake-4-accepting-results-that-confirmed-our-priors" class="nav-link" data-scroll-target="#mistake-4-accepting-results-that-confirmed-our-priors">Mistake #4: Accepting Results That Confirmed Our Priors</a></li>
  <li><a href="#mistake-5-confusing-statistical-significance-with-importance" id="toc-mistake-5-confusing-statistical-significance-with-importance" class="nav-link" data-scroll-target="#mistake-5-confusing-statistical-significance-with-importance">Mistake #5: Confusing Statistical Significance with Importance</a></li>
  </ul></li>
  <li><a href="#looking-forward-preparing-for-econometrics" id="toc-looking-forward-preparing-for-econometrics" class="nav-link" data-scroll-target="#looking-forward-preparing-for-econometrics"><span class="header-section-number">7.9</span> Looking Forward: Preparing for Econometrics</a>
  <ul class="collapse">
  <li><a href="#the-bridge-to-econometrics" id="toc-the-bridge-to-econometrics" class="nav-link" data-scroll-target="#the-bridge-to-econometrics">The Bridge to Econometrics</a></li>
  <li><a href="#what-makes-econometrics-different" id="toc-what-makes-econometrics-different" class="nav-link" data-scroll-target="#what-makes-econometrics-different">What Makes Econometrics Different?</a></li>
  <li><a href="#a-final-question-from-the-cohort" id="toc-a-final-question-from-the-cohort" class="nav-link" data-scroll-target="#a-final-question-from-the-cohort">A Final Question from the Cohort</a></li>
  </ul></li>
  <li><a href="#chapter-summary-the-statistical-toolkit-in-review" id="toc-chapter-summary-the-statistical-toolkit-in-review" class="nav-link" data-scroll-target="#chapter-summary-the-statistical-toolkit-in-review"><span class="header-section-number">7.10</span> Chapter Summary: The Statistical Toolkit in Review</a>
  <ul class="collapse">
  <li><a href="#the-common-thread-statistical-thinking" id="toc-the-common-thread-statistical-thinking" class="nav-link" data-scroll-target="#the-common-thread-statistical-thinking">The Common Thread: Statistical Thinking</a></li>
  </ul></li>
  <li><a href="#closing-thoughts-the-journey-continues" id="toc-closing-thoughts-the-journey-continues" class="nav-link" data-scroll-target="#closing-thoughts-the-journey-continues"><span class="header-section-number">7.11</span> Closing Thoughts: The Journey Continues</a></li>
  <li><a href="#practice-questions-for-review" id="toc-practice-questions-for-review" class="nav-link" data-scroll-target="#practice-questions-for-review"><span class="header-section-number">7.12</span> Practice Questions for Review</a>
  <ul class="collapse">
  <li><a href="#question-1-connecting-descriptive-statistics-and-inference" id="toc-question-1-connecting-descriptive-statistics-and-inference" class="nav-link" data-scroll-target="#question-1-connecting-descriptive-statistics-and-inference">Question 1: Connecting Descriptive Statistics and Inference</a></li>
  <li><a href="#question-2-connecting-probability-and-inference" id="toc-question-2-connecting-probability-and-inference" class="nav-link" data-scroll-target="#question-2-connecting-probability-and-inference">Question 2: Connecting Probability and Inference</a></li>
  <li><a href="#question-3-connecting-anova-and-multiple-testing" id="toc-question-3-connecting-anova-and-multiple-testing" class="nav-link" data-scroll-target="#question-3-connecting-anova-and-multiple-testing">Question 3: Connecting ANOVA and Multiple Testing</a></li>
  <li><a href="#question-4-connecting-categorical-analysis-and-causation" id="toc-question-4-connecting-categorical-analysis-and-causation" class="nav-link" data-scroll-target="#question-4-connecting-categorical-analysis-and-causation">Question 4: Connecting Categorical Analysis and Causation</a></li>
  <li><a href="#question-5-integrative-case-study" id="toc-question-5-integrative-case-study" class="nav-link" data-scroll-target="#question-5-integrative-case-study">Question 5: Integrative Case Study</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/ncachanosky/XQMB-5311/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Statistical Foundations Review: From Description to Decision</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  
<div>
  <div class="abstract">
    <div class="block-title">Abstract</div>
    <p>After five consulting engagements across five industries, David and Maria return to campus to synthesize what they have learned. This review chapter maps the full statistical progression from description to probability to inference to comparison, identifies the most common and costly interpretation errors encountered in practice, and connects the foundational methods of Lectures 1–5 to the econometric tools introduced in Lecture 7. It is as much a lesson in statistical thinking as it is a recap of technical content.</p>
  </div>
</div>


</header>


<section id="learning-objectives" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="learning-objectives">Learning Objectives</h2>
<p>By the end of this review session, you will be able to:</p>
<ol type="1">
<li>✅ Explain when to use each statistical method covered in Lectures 1-5<br>
</li>
<li>✅ Identify common interpretation errors and how to avoid them<br>
</li>
<li>✅ Recognize the progression from description to prediction to inference to comparison<br>
</li>
<li>✅ Understand how these foundational concepts prepare you for econometric analysis<br>
</li>
<li>✅ Apply appropriate statistical thinking to business decision-making</li>
</ol>
</section>
<section id="introduction-the-journey-back-to-campus" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="introduction-the-journey-back-to-campus"><span class="header-section-number">7.1</span> Introduction: The Journey Back to Campus</h2>
<p>After ten months in the field conducting statistical consulting for five companies, David Martinez and Maria Rodriguez return to the EMBA program at The University of Texas at El Paso. The lecture hall buzzes with anticipation as their cohort gathers for this special review session.</p>
<p>“Welcome back, David and Maria,” the professor says warmly. “Your classmates have been following your work through the course materials. Today, we want to hear directly from you. What did you learn out there? What mistakes did you almost make? And most importantly, what advice would you give to future consultants?”</p>
<p>David and Maria exchange a glance. They’ve prepared for this presentation carefully, knowing their peers will ask tough questions. This isn’t just a victory lap—it’s an opportunity to crystallize the lessons they’ve learned through trial, error, and occasionally painful realizations.</p>
<p>“Let’s start at the beginning,” Maria says, pulling up their first slide. “Five companies. Five different statistical challenges. One connecting thread: the difference between doing calculations and doing statistics right.”</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>The Five Cases at a Glance
</div>
</div>
<div class="callout-body-container callout-body">
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Company</strong></th>
<th style="text-align: left;"><strong>Industry</strong></th>
<th style="text-align: left;"><strong>Challenge</strong></th>
<th style="text-align: left;"><strong>Statistical Focus</strong></th>
<th style="text-align: left;"><strong>Key Learning</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">TechFlow Solutions</td>
<td style="text-align: left;">Consumer Electronics</td>
<td style="text-align: left;">Vague Q4 performance report</td>
<td style="text-align: left;">Descriptive Statistics</td>
<td style="text-align: left;">Precision replaces vagueness</td>
</tr>
<tr class="even">
<td style="text-align: left;">PrecisionCast Industries</td>
<td style="text-align: left;">Manufacturing</td>
<td style="text-align: left;">“Pretty good” quality estimates</td>
<td style="text-align: left;">Probability</td>
<td style="text-align: left;">Quantify uncertainty</td>
</tr>
<tr class="odd">
<td style="text-align: left;">BorderMed Pharmaceuticals</td>
<td style="text-align: left;">Clinical Trials</td>
<td style="text-align: left;">Overconfident drug claims</td>
<td style="text-align: left;">Statistical Inference</td>
<td style="text-align: left;">Acknowledge what you don’t know</td>
</tr>
<tr class="even">
<td style="text-align: left;">DesertVine Hospitality</td>
<td style="text-align: left;">Hotel Chain</td>
<td style="text-align: left;">Misinterpreted satisfaction data</td>
<td style="text-align: left;">ANOVA</td>
<td style="text-align: left;">Multiple comparisons require care</td>
</tr>
<tr class="odd">
<td style="text-align: left;">PixelPerfect Marketing</td>
<td style="text-align: left;">Digital Advertising</td>
<td style="text-align: left;">Correlation confused with causation</td>
<td style="text-align: left;">Categorical Data Analysis</td>
<td style="text-align: left;">Association ≠ causation</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>A hand shoots up from the back row. “Before we dive into each case,” asks Jennifer, an EMBA student specializing in supply chain, “can you explain the big picture? How do these five topics connect?”</p>
</section>
<section id="the-statistical-progression-a-framework-for-business-analysis" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="the-statistical-progression-a-framework-for-business-analysis"><span class="header-section-number">7.2</span> The Statistical Progression: A Framework for Business Analysis</h2>
<p>David nods. “Great question. We didn’t see it at first either. We thought each company was a separate problem. But about halfway through the BorderMed case, we realized these weren’t five different statistical methods—they were five stages of the same analytical journey.”</p>
<p>He projects a diagram on the screen:</p>
<pre><code>THE STATISTICAL JOURNEY

STAGE 1: DESCRIPTION
├─ Question: "What happened?"
├─ Tool: Descriptive Statistics
├─ Output: Precise measurements of past data
└─ Example: "Q4 mean revenue was $766,667 with SD = $40,825"

STAGE 2: PREDICTION  
├─ Question: "What will happen?"
├─ Tool: Probability
├─ Output: Quantified forecasts and risks
└─ Example: "Expected Q2 defects = 1,117 ± 66 (95% range)"

STAGE 3: INFERENCE
├─ Question: "What can we conclude?"
├─ Tool: Hypothesis Testing &amp; Confidence Intervals
├─ Output: Population estimates from samples
└─ Example: "True drug effect: 10.6 to 14.2 mmHg (95% CI)"

STAGE 4: COMPARISON
├─ Question: "Which groups differ?"
├─ Tool: ANOVA
├─ Output: Systematic comparison across multiple groups
└─ Example: "Property differences exist (F=4.89, p=0.003)"

STAGE 5: ASSOCIATION
├─ Question: "What relates to what?"
├─ Tool: Chi-Square &amp; Categorical Analysis
├─ Output: Relationships between categorical variables
└─ Example: "Channel and conversion are associated (χ²=42.87, p&lt;0.001)"</code></pre>
<p>Maria continues the explanation. “Each stage builds on the previous one. You can’t do probability without understanding variability from descriptive statistics. You can’t do inference without probability distributions. And you can’t properly interpret ANOVA or chi-square without understanding hypothesis testing.”</p>
<p>“But here’s what we learned the hard way,” David adds. “You also can’t skip stages. When DesertVine’s original analyst went straight to ANOVA without checking descriptive statistics first, they missed the fact that one property had only 47 guests—way too small for reliable conclusions.”</p>
<p>Carlos, an operations manager in the cohort, raises his hand. “You mentioned mistakes you almost made. Can you walk us through those? That’s what I really want to learn—what to watch out for.”</p>
</section>
<section id="lecture-1-review-descriptive-statisticsprecision-over-vagueness" class="level2" data-number="7.3">
<h2 data-number="7.3" class="anchored" data-anchor-id="lecture-1-review-descriptive-statisticsprecision-over-vagueness"><span class="header-section-number">7.3</span> Lecture 1 Review: Descriptive Statistics—Precision Over Vagueness</h2>
<p>Maria takes this one. “TechFlow was our wake-up call. They handed us a marketing report that said things like ‘around $767,000’ and ‘somewhere in the middle.’ At first, we thought, ‘What’s wrong with that? We get the general idea.’”</p>
<p>“But then Sarah Chen, their CEO, asked us: ‘Should I discontinue Product D? Should I expand in Asia-Pacific? Should I hire more customer service staff?’ And we realized—you can’t make decisions with vague statistics.”</p>
<section id="the-core-lesson-descriptive-statistics-tell-you-exactly-what-happened" class="level3">
<h3 class="anchored" data-anchor-id="the-core-lesson-descriptive-statistics-tell-you-exactly-what-happened">The Core Lesson: Descriptive Statistics Tell You <em>Exactly</em> What Happened</h3>
<p>David pulls up the TechFlow dashboard:</p>
<p><strong>Before Our Analysis</strong> (❌):<br>
“Revenue was around $767,000. Most days were somewhere in the middle range. Some outliers on both ends.”</p>
<p><strong>After Our Analysis</strong> (✓):</p>
<ul>
<li>Mean monthly revenue: $766,667<br>
</li>
<li>Median monthly revenue: $780,000<br>
</li>
<li>Standard deviation: $40,825 (CV: 5.3%—highly consistent)<br>
</li>
<li>Product D: z-score = -1.21 (statistical underperformer)<br>
</li>
<li>Regional CV: 76.8% (geography varies more than products)<br>
</li>
<li>Customer satisfaction: median 4.3/5 (left-skewed distribution)</li>
</ul>
<p>“Every number is precise,” Maria emphasizes. “But more importantly, every number <em>means</em> something for business decisions.”</p>
</section>
<section id="a-students-question-when-do-i-use-mean-vs.-median" class="level3">
<h3 class="anchored" data-anchor-id="a-students-question-when-do-i-use-mean-vs.-median">A Student’s Question: “When Do I Use Mean vs.&nbsp;Median?”</h3>
<p>Sarah, an accountant in the class, raises her hand. “I’m still confused about when to use mean versus median. Can you explain that?”</p>
<p>Maria lights up. “This was actually one of our first major realizations. The answer is: it depends on the distribution shape.”</p>
<p>She projects a comparison:</p>
<p><strong>Use MEAN when:</strong></p>
<ul>
<li>Distribution is roughly symmetric<br>
</li>
<li>No extreme outliers<br>
</li>
<li>You want to account for every data point’s value<br>
</li>
<li>Example: TechFlow’s monthly revenue (symmetric, no outliers)</li>
</ul>
<p><strong>Use MEDIAN when:</strong></p>
<ul>
<li>Distribution is skewed<br>
</li>
<li>Outliers present<br>
</li>
<li>You want the “typical” value that represents most cases<br>
</li>
<li>Example: TechFlow’s response times (right-skewed: most fast, some very slow)</li>
</ul>
<p>“Here’s the mistake we almost made,” David admits. “TechFlow’s satisfaction scores had mean = 4.1 and median = 4.3. We almost reported the mean in our executive summary. But then we looked at the distribution—it was left-skewed. Most customers rated 4-5, but a few unhappy customers dragged the mean down.”</p>
<p>“If we’d reported mean = 4.1, Sarah would think typical satisfaction was lower than it actually is. The median of 4.3 better represents the typical customer experience. And those few unhappy customers? They become a separate analysis: ‘Who are they and why are they churning?’”</p>
</section>
<section id="common-pitfalls-in-descriptive-statistics" class="level3">
<h3 class="anchored" data-anchor-id="common-pitfalls-in-descriptive-statistics">Common Pitfalls in Descriptive Statistics</h3>
<p>Maria clicks to the next slide, titled “Mistakes We Almost Made—And How We Caught Them.”</p>
<p><strong>Pitfall 1: Treating Standard Deviation as a Nuisance</strong></p>
<p>“At first, we calculated standard deviations because the assignment required it,” Maria admits. “We didn’t <em>get</em> why it mattered. Then Sarah asked: ‘How consistent are we month-to-month?’ That’s when it clicked.”</p>
<p>“SD tells you consistency. TechFlow’s monthly revenue had SD = $40,825 on mean = $766,667. That’s a coefficient of variation of 5.3%. Translation: very consistent, easy to forecast. Their product portfolio? CV = 46.6%. Translation: huge variability, each product needs individual strategy.”</p>
<p><strong>Pitfall 2: Ignoring Outliers</strong></p>
<p>“The original TechFlow report said ‘some outliers on both ends,’” David recalls. “They treated outliers like data errors. But outliers tell stories. TechFlow had six orders above $513—that’s their B2B opportunity, 3% of customers generating 8% of revenue. Missing that costs money.”</p>
<p><strong>Pitfall 3: Not Checking Distribution Shape</strong></p>
<p>“We calculated skewness because the formula was in the textbook,” Maria says. “But we didn’t understand what -0.95 meant until we plotted the data. Left-skewed satisfaction means most customers happy, few unhappy. Right-skewed response times means most tickets resolved quickly, few taking forever. Same statistic, opposite business implications.”</p>
</section>
<section id="key-takeaway-descriptive-statistics" class="level3">
<h3 class="anchored" data-anchor-id="key-takeaway-descriptive-statistics">Key Takeaway: Descriptive Statistics</h3>
<p>A student named Miguel asks, “So what’s the one thing you’d tell someone just starting descriptive statistics?”</p>
<p>David doesn’t hesitate: “Every statistic answers a business question. Mean answers ‘What’s typical?’ SD answers ‘How consistent?’ Z-scores answer ‘What’s unusual?’ Correlation answers ‘What’s related?’ Don’t calculate statistics because they’re in the textbook. Calculate them because they help someone make a decision.”</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Descriptive Statistics Quick Reference
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Measures of Location</strong> (What’s typical?)</p>
<ul>
<li><strong>Mean</strong>: Use for symmetric data, no outliers<br>
</li>
<li><strong>Median</strong>: Use for skewed data, robust to outliers<br>
</li>
<li><strong>Mode</strong>: Use for categorical data, multi-modal distributions<br>
</li>
<li><strong>Percentiles</strong>: Use to define thresholds (e.g., “top 10% get bonus”)</li>
</ul>
<p><strong>Measures of Variability</strong> (How consistent?)</p>
<ul>
<li><strong>Standard Deviation</strong>: Typical deviation from mean<br>
</li>
<li><strong>Coefficient of Variation</strong>: Compare variability across different scales<br>
</li>
<li><strong>IQR</strong>: Robust measure of spread, resistant to outliers<br>
</li>
<li><strong>Range</strong>: Simple spread measure, sensitive to outliers</li>
</ul>
<p><strong>Distribution Characteristics</strong> (What’s the shape?)</p>
<ul>
<li><strong>Skewness</strong>: Is data symmetric or leaning one direction?<br>
</li>
<li><strong>Z-scores</strong>: How unusual is this value? (|z| &gt; 2 is notable)<br>
</li>
<li><strong>Outliers</strong>: Problems to fix or opportunities to leverage?</li>
</ul>
<p><strong>Association</strong> (What’s related?)</p>
<ul>
<li><strong>Correlation</strong>: Strength and direction of linear relationship (-1 to +1)<br>
</li>
<li><strong>Remember</strong>: Correlation ≠ Causation (always)</li>
</ul>
</div>
</div>
<hr>
</section>
</section>
<section id="lecture-2-review-probabilityquantifying-uncertainty" class="level2" data-number="7.4">
<h2 data-number="7.4" class="anchored" data-anchor-id="lecture-2-review-probabilityquantifying-uncertainty"><span class="header-section-number">7.4</span> Lecture 2 Review: Probability—Quantifying Uncertainty</h2>
<p>“PrecisionCast Industries was our second case,” David begins. “And honestly, it was where we almost failed.”</p>
<p>The room goes quiet. A few students lean forward.</p>
<p>“Their quality manager, Robert Martinez, handed us a report that said things like ‘defect rate is around 2%’ and ‘tests are pretty good.’ We thought, ‘Okay, we learned from TechFlow—let’s calculate exact numbers!’ So we did. P(Defect) = 0.0203 exactly. Expected Q2 defects = 1,117. Done.”</p>
<p>“Except,” Maria interjects, “we missed the entire point of probability. It’s not about calculating exact numbers. It’s about understanding what those numbers mean for decision-making under uncertainty.”</p>
<section id="the-core-lesson-probability-converts-uncertainty-into-decisions" class="level3">
<h3 class="anchored" data-anchor-id="the-core-lesson-probability-converts-uncertainty-into-decisions">The Core Lesson: Probability Converts Uncertainty into Decisions</h3>
<p>Maria pulls up the PrecisionCast case:</p>
<p>“Robert was about to spend $2 million on new equipment because his inspection system showed ‘pretty good’ test accuracy. Here’s what we discovered through probability analysis:”</p>
<p><strong>The Inspection System:</strong></p>
<ul>
<li>Sensitivity (catch defects): 95%<br>
</li>
<li>Specificity (correctly pass good parts): 99%<br>
</li>
<li>Sound great, right?</li>
</ul>
<p>“Wrong,” David says flatly. “We calculated the Positive Predictive Value using Bayes’ Theorem. When a part tests positive for defects, what’s the probability it’s actually defective?”</p>
<p><strong>Answer: 49.6%</strong></p>
<p>“Basically a coin flip,” Maria adds. “Despite ‘95% accuracy,’ half of all flagged parts were actually fine. Robert was about to invest $2 million to reduce ‘false positives,’ but the real problem was the base rate—only 2% defect rate makes even good tests unreliable.”</p>
</section>
<section id="a-students-question-whats-the-difference-between-probability-and-statistics" class="level3">
<h3 class="anchored" data-anchor-id="a-students-question-whats-the-difference-between-probability-and-statistics">A Student’s Question: “What’s the Difference Between Probability and Statistics?”</h3>
<p>Jennifer asks, “I’m still not clear on when I’m doing probability versus when I’m doing statistics. Aren’t they the same thing?”</p>
<p>David shakes his head. “That’s the question we asked too. Here’s how we finally understood it:”</p>
<p><strong>Probability</strong> (known population → predict sample):</p>
<ul>
<li>“I know the defect rate is 2%. What’s the probability the next batch has 10 or fewer defects?”<br>
</li>
<li>You know the population parameters, predict sample outcomes<br>
</li>
<li>Forward-looking: What will happen?</li>
</ul>
<p><strong>Statistics</strong> (observed sample → infer population):</p>
<ul>
<li>“I observed 1,015 defects in 50,000 parts. What’s the population defect rate?”<br>
</li>
<li>You observe sample data, infer population parameters<br>
</li>
<li>Backward-looking: What does this tell us about reality?</li>
</ul>
<p>“PrecisionCast was pure probability,” Maria clarifies. “We knew their historical defect rate (2.03%), we knew their batch size (55,000 units), we knew their machine characteristics. We used probability to predict Q2 outcomes and evaluate the proposed equipment investment.”</p>
</section>
<section id="common-pitfalls-in-probability" class="level3">
<h3 class="anchored" data-anchor-id="common-pitfalls-in-probability">Common Pitfalls in Probability</h3>
<p><strong>Pitfall 1: Confusing P(A|B) with P(B|A)</strong></p>
<p>“This almost cost Robert $2 million,” David says. “His test manufacturer claimed ‘95% sensitivity’—meaning P(Test+ | Defect) = 0.95. Robert interpreted this as ‘if the test is positive, there’s 95% probability of a defect’—which would be P(Defect | Test+).”</p>
<p>“Bayes’ Theorem reverses conditional probabilities. We calculated P(Defect | Test+) = 49.6%. Huge difference.”</p>
<p><strong>Pitfall 2: Treating Probability as Certainty</strong></p>
<p>“Expected value is <em>expected</em>—not guaranteed,” Maria emphasizes. “We calculated E(Q2 defects) = 1,117. Robert started planning capacity for exactly 1,117 defects. We had to explain: ‘That’s the average over many quarters. Any individual quarter could be 1,000 or 1,200. You need buffer capacity.’”</p>
<p><strong>Pitfall 3: Ignoring Distributions</strong></p>
<p>“Robert asked: ‘What’s the probability Q2 defects exceed 1,200?’” David recalls. “We couldn’t answer with expected value alone. We needed the binomial distribution to calculate: P(X &gt; 1,200) = 10.2%. That became his contingency planning threshold.”</p>
</section>
<section id="the-expected-value-decision-framework" class="level3">
<h3 class="anchored" data-anchor-id="the-expected-value-decision-framework">The Expected Value Decision Framework</h3>
<p>Carlos asks, “How did you use probability to actually make the recommendation about the $2 million investment?”</p>
<p>Maria projects the decision tree:</p>
<p><strong>Decision: Invest $2M in new equipment?</strong></p>
<p><strong>Scenario Analysis:</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 11%">
<col style="width: 15%">
<col style="width: 30%">
<col style="width: 6%">
<col style="width: 29%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Scenario</th>
<th style="text-align: left;">Probability</th>
<th style="text-align: left;">Defects (w/o investment)</th>
<th style="text-align: left;">Cost</th>
<th style="text-align: left;">Defects (w/ investment)</th>
<th style="text-align: left;">Cost</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Best case</td>
<td style="text-align: left;">0.30</td>
<td style="text-align: left;">1,000</td>
<td style="text-align: left;">$200,000</td>
<td style="text-align: left;">500</td>
<td style="text-align: left;">$30,000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Most likely</td>
<td style="text-align: left;">0.50</td>
<td style="text-align: left;">1,117</td>
<td style="text-align: left;">$223,400</td>
<td style="text-align: left;">700</td>
<td style="text-align: left;">$70,000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Worst case</td>
<td style="text-align: left;">0.20</td>
<td style="text-align: left;">1,300</td>
<td style="text-align: left;">$260,000</td>
<td style="text-align: left;">850</td>
<td style="text-align: left;">$34,000</td>
</tr>
</tbody>
</table>
<p><strong>Expected Cost Without Investment:</strong> $223,800<br>
<strong>Expected Cost With Investment:</strong> $134,000<br>
<strong>Expected Savings:</strong> $89,800/quarter</p>
<p>“But the investment costs $2 million,” David continues. “Payback period: $2M / $357,200 per year = 5.6 years. Robert’s equipment lifespan: 7 years. Marginal decision, not the slam dunk the manufacturer claimed.”</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Probability Quick Reference
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Basic Probability:</strong></p>
<ul>
<li>P(Event) = favorable outcomes / total outcomes<br>
</li>
<li>Use for forecasting, capacity planning, budgeting</li>
</ul>
<p><strong>Conditional Probability:</strong></p>
<ul>
<li>P(A|B) asks “given B occurred, what’s P(A)?”<br>
</li>
<li>Use for root cause analysis, targeted interventions</li>
</ul>
<p><strong>Bayes’ Theorem:</strong></p>
<ul>
<li>Reverses conditional probabilities: P(A|B) → P(B|A)<br>
</li>
<li>Critical for medical testing, quality control, fraud detection<br>
</li>
<li><strong>Warning</strong>: P(Test+|Disease) ≠ P(Disease|Test+)</li>
</ul>
<p><strong>Expected Value:</strong></p>
<ul>
<li>E(X) = Σ[value × probability]<br>
</li>
<li>Use for decision-making under uncertainty<br>
</li>
<li>Remember: Expected ≠ guaranteed</li>
</ul>
<p><strong>Distributions:</strong></p>
<ul>
<li><strong>Binomial</strong>: Count successes/failures (discrete events)<br>
</li>
<li><strong>Normal</strong>: Model continuous measurements<br>
</li>
<li>Match the distribution to the business question</li>
</ul>
</div>
</div>
<hr>
</section>
</section>
<section id="lecture-3-review-statistical-inferenceacknowledging-what-we-dont-know" class="level2" data-number="7.5">
<h2 data-number="7.5" class="anchored" data-anchor-id="lecture-3-review-statistical-inferenceacknowledging-what-we-dont-know"><span class="header-section-number">7.5</span> Lecture 3 Review: Statistical Inference—Acknowledging What We Don’t Know</h2>
<p>The room shifts. Students sense this topic is different.</p>
<p>“BorderMed Pharmaceuticals,” Maria begins quietly, “was where statistics stopped being academic and started being life-or-death. They’d developed a drug for hypertension. Their Phase II clinical trial showed a 12.4 mmHg reduction in blood pressure. They were ready to commit $500 million to Phase III trials.”</p>
<p>“Their report said the drug ‘proves efficacy’ and ‘has no significant safety risk,’” David continues. “Every calculation was correct. Every p-value properly computed. And every conclusion was dangerously wrong.”</p>
<section id="the-core-lesson-sample-statistics-population-parameters" class="level3">
<h3 class="anchored" data-anchor-id="the-core-lesson-sample-statistics-population-parameters">The Core Lesson: Sample Statistics ≠ Population Parameters</h3>
<p>“This is where we learned the hardest lesson in statistics,” Maria says. “You observe a sample. You calculate statistics. But those statistics are just estimates of population parameters—and estimates come with uncertainty.”</p>
<p>David projects the BorderMed error:</p>
<p><strong>What Their Report Said</strong> (❌):<br>
“VasoRelief reduced systolic blood pressure by 12.4 mmHg. This <strong>represents the true efficacy</strong> of the drug.”</p>
<p><strong>What They Should Have Said</strong> (✓):<br>
“In our sample of 85 patients, we observed a mean reduction of 12.4 mmHg (SD = 8.6). We estimate the true population mean reduction to be between <strong>10.6 and 14.2 mmHg</strong> (95% confidence interval).”</p>
<p>“See the difference?” Maria asks the class. “One treats the sample statistic as truth. The other acknowledges it’s an estimate with a range of plausible values.”</p>
</section>
<section id="a-students-question-what-does-95-confidence-mean" class="level3">
<h3 class="anchored" data-anchor-id="a-students-question-what-does-95-confidence-mean">A Student’s Question: “What Does 95% Confidence Mean?”</h3>
<p>Sarah asks, “I’ve heard ‘95% confidence interval’ a hundred times, but I still don’t fully understand what it means. Can you explain it without the technical jargon?”</p>
<p>David nods. “We struggled with this too. Here’s how we finally got it:”</p>
<p>“Imagine you could repeat the BorderMed trial infinite times—same size (n=85), same drug, different random patients each time. Each trial gives you a different sample mean and a different confidence interval.”</p>
<p>“If you calculated 95% CIs for all those trials, approximately 95% of them would contain the true population mean. About 5% would miss it entirely—that’s the risk we accept.”</p>
<p>“For BorderMed’s specific CI of (10.6, 14.2), we can’t say ‘there’s a 95% probability the true mean is in this range’—the true mean is either in there or it isn’t. What we can say is: ‘We’re 95% confident this interval contains the true mean.’”</p>
<p>Maria adds the business translation: “For decision-makers, it means: ‘The effect is probably somewhere between 10.6 and 14.2 mmHg. Plan for that range, not for exactly 12.4.’”</p>
</section>
<section id="common-pitfalls-in-statistical-inference" class="level3">
<h3 class="anchored" data-anchor-id="common-pitfalls-in-statistical-inference">Common Pitfalls in Statistical Inference</h3>
<p><strong>Pitfall 1: Confusing “Fail to Reject” with “Accept”</strong></p>
<p>“This almost became a patient safety disaster,” David says seriously. “BorderMed tested whether headache rates differed from placebo. Result: p = 0.10. Their report concluded: ‘We accept the null hypothesis. No significant headache risk.’”</p>
<p>“That’s not what p = 0.10 means,” Maria emphasizes. “When p &gt; α, you haven’t proven the null hypothesis true. You’ve just failed to find evidence against it. Two completely different things.”</p>
<p>“BorderMed’s observed headache rate was 27.1% versus 20% placebo—a 35% relative increase. But with only 85 patients, they lacked statistical power to detect it. Type II error risk was approximately 50%.”</p>
<p>“‘No evidence of difference’ is not the same as ‘evidence of no difference,’” David states firmly. “Especially for safety endpoints, failing to detect harm doesn’t mean harm doesn’t exist.”</p>
<p><strong>Pitfall 2: Misinterpreting P-Values</strong></p>
<p>“Their report said: ‘p &lt; 0.001 proves the drug works with 99.9% certainty,’” Maria recalls. “This is the single most common statistical error in all of science.”</p>
<p>She projects the correction:</p>
<p><strong>Wrong Interpretation</strong> (❌):<br>
“p-value = probability the hypothesis is true”<br>
“p &lt; 0.001 = 99.9% certain the drug works”</p>
<p><strong>Correct Interpretation</strong> (✓):<br>
“p-value = probability of observing data this extreme if H₀ were true”<br>
“p &lt; 0.001 = if drug had no effect, data this extreme would occur &lt;0.1% of the time by chance”</p>
<p>“P-values tell you about the data, not about the hypothesis,” David clarifies. “They measure ‘how weird would this data be if nothing were happening?’ Not ‘how likely is it that something is happening?’”</p>
<p><strong>Pitfall 3: Treating Small Samples Like Large Ones</strong></p>
<p>“BorderMed had one site with only 15 patients,” Maria notes. “Their confidence interval for that site was 9.4 mmHg wide. The other sites? About 3-4 mmHg wide. But their report treated all sites as equally reliable.”</p>
<p>“Small samples → wide confidence intervals → imprecise estimates. You can’t fix that with fancier statistics. You need more data.”</p>
</section>
<section id="the-asymmetry-of-hypothesis-testing" class="level3">
<h3 class="anchored" data-anchor-id="the-asymmetry-of-hypothesis-testing">The Asymmetry of Hypothesis Testing</h3>
<p>Miguel raises his hand. “I’m still confused about the asymmetry. Why can we ‘reject’ but not ‘accept’?”</p>
<p>“Great question,” David responds. “Think of it like a criminal trial. The defendant is presumed innocent (null hypothesis). If evidence is overwhelming, we reject innocence (reject H₀). But if evidence is weak, we don’t ‘accept innocence’—we just say ‘insufficient evidence to convict.’”</p>
<p>“In hypothesis testing:”</p>
<ul>
<li><strong>Small p-value</strong> (p &lt; α): Strong evidence against H₀ → Reject H₀<br>
</li>
<li><strong>Large p-value</strong> (p ≥ α): Insufficient evidence against H₀ → Fail to reject H₀</li>
</ul>
<p>“You never ‘accept’ H₀ because a large p-value could mean either: (1) H₀ is actually true, or (2) H₀ is false but your sample was too small to detect it. You can’t tell which.”</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Statistical Inference Quick Reference
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Confidence Intervals:</strong></p>
<ul>
<li>Quantify uncertainty in estimates<br>
</li>
<li>Provide range of plausible population parameter values<br>
</li>
<li><strong>Interpretation</strong>: “95% confident this interval contains the true mean”<br>
</li>
<li><strong>NOT</strong>: “95% probability the true mean is in this interval”</li>
</ul>
<p><strong>P-Values:</strong></p>
<ul>
<li>P(data this extreme | H₀ true)<br>
</li>
<li><strong>NOT</strong> P(hypothesis true | data)<br>
</li>
<li>Small p-value = strong evidence against H₀<br>
</li>
<li><strong>Never say</strong>: “proves,” “X% certain hypothesis is true”</li>
</ul>
<p><strong>Hypothesis Testing:</strong></p>
<ul>
<li>Reject H₀: Strong evidence for H_a<br>
</li>
<li>Fail to reject H₀: Insufficient evidence (not “accept H₀”)<br>
</li>
<li>Always consider Type I error (α) and Type II error (β)<br>
</li>
<li>For safety endpoints, Type II errors can be catastrophic</li>
</ul>
<p><strong>Sample Size Matters:</strong></p>
<ul>
<li>Small n → wide CIs → imprecise estimates<br>
</li>
<li>Calculate required n before study, not after<br>
</li>
<li>Don’t treat all CIs as equally reliable regardless of n</li>
</ul>
</div>
</div>
<hr>
</section>
</section>
<section id="lecture-4-review-anovacomparing-multiple-groups-simultaneously" class="level2" data-number="7.6">
<h2 data-number="7.6" class="anchored" data-anchor-id="lecture-4-review-anovacomparing-multiple-groups-simultaneously"><span class="header-section-number">7.6</span> Lecture 4 Review: ANOVA—Comparing Multiple Groups Simultaneously</h2>
<p>“DesertVine Hospitality Group taught us about multiple comparisons,” Maria begins. “They had four hotel properties and wanted to know: ‘Do they all perform equally?’ Simple question. Not a simple answer.”</p>
<section id="the-core-lesson-multiple-comparisons-inflate-error-rates" class="level3">
<h3 class="anchored" data-anchor-id="the-core-lesson-multiple-comparisons-inflate-error-rates">The Core Lesson: Multiple Comparisons Inflate Error Rates</h3>
<p>David projects the challenge:</p>
<p>“DesertVine had satisfaction data from four properties: El Paso (8.4), Tucson (8.5), Santa Fe (7.8), and Albuquerque (8.0). They wanted to compare them all.”</p>
<p>“Naive approach: Run six pairwise t-tests (El Paso vs.&nbsp;Tucson, El Paso vs.&nbsp;Santa Fe, etc.). Problem: Each test has 5% chance of false positive. Six tests means cumulative error rate of approximately 26%.”</p>
<p><strong>Why ANOVA?</strong><br>
“ANOVA does one omnibus test first: ‘Is there any difference among the four properties?’ If yes (reject H₀), then we investigate which specific properties differ. If no (fail to reject), we stop. This controls the family-wise error rate.”</p>
</section>
<section id="a-students-question-what-does-the-f-statistic-tell-me" class="level3">
<h3 class="anchored" data-anchor-id="a-students-question-what-does-the-f-statistic-tell-me">A Student’s Question: “What Does the F-Statistic Tell Me?”</h3>
<p>Carlos asks, “I can calculate F = MS_between / MS_within, but what does it actually mean?”</p>
<p>Maria responds: “F-statistic compares two sources of variation:”</p>
<p><strong>MS_between</strong> (variation between groups):</p>
<ul>
<li>How much do the group means differ from each other?<br>
</li>
<li>If groups truly differ, this should be large</li>
</ul>
<p><strong>MS_within</strong> (variation within groups):</p>
<ul>
<li>How much do individuals within each group vary?<br>
</li>
<li>This represents random noise</li>
</ul>
<p>“F = between-group variation / within-group variation. If F is large, group differences are bigger than random noise. If F is small, apparent differences might just be noise.”</p>
<p>“DesertVine’s F = 4.89 with p = 0.003. Translation: The property differences are real, not just random variation.”</p>
</section>
<section id="common-pitfalls-in-anova" class="level3">
<h3 class="anchored" data-anchor-id="common-pitfalls-in-anova">Common Pitfalls in ANOVA</h3>
<p><strong>Pitfall 1: Multiple Testing Without Adjustment</strong></p>
<p>“DesertVine’s original report ran six pairwise t-tests after ANOVA without any adjustment,” David recalls. “They found several ‘significant’ differences that weren’t really there.”</p>
<p>“If you run multiple tests, you need Bonferroni correction or Tukey’s HSD. Otherwise, you’re inflating your Type I error rate.”</p>
<p><strong>Bonferroni Correction:</strong><br>
α_adjusted = α_family / number of comparisons<br>
For 6 comparisons: 0.05 / 6 = 0.0083</p>
<p><strong>Pitfall 2: Confusing “No Evidence of Difference” with “No Difference”</strong></p>
<p>“Their original report compared business vs.&nbsp;leisure travelers,” Maria notes. “Result: p = 0.279. They concluded: ‘Travel purpose has no effect. Business and leisure travelers have identical satisfaction.’”</p>
<p>“Wrong on two counts. First, we don’t ‘accept’ null hypotheses. Second, the confidence interval was (-0.56 to 0.16). That includes zero, but it also includes differences as large as 0.56 points—potentially meaningful for business decisions.”</p>
<p><strong>Pitfall 3: Ignoring Unequal Sample Sizes</strong></p>
<p>“Albuquerque property had only 47 guests compared to 95+ at other properties,” David points out. “This creates unequal precision. Albuquerque’s CI was much wider, but the report treated all properties as equally reliable.”</p>
<p>“When sample sizes differ substantially, be extra cautious about conclusions involving the small-sample groups.”</p>
</section>
<section id="when-to-use-anova-vs.-multiple-t-tests" class="level3">
<h3 class="anchored" data-anchor-id="when-to-use-anova-vs.-multiple-t-tests">When to Use ANOVA vs.&nbsp;Multiple t-Tests</h3>
<p>Jennifer asks, “If I only have two groups, do I use ANOVA or t-test?”</p>
<p>“Either works,” Maria responds. “For two groups, ANOVA and t-test give identical results (actually, F = t²). But for three or more groups, always start with ANOVA.”</p>
<p><strong>The Decision Tree:</strong></p>
<pre><code>How many groups?
├─ Two groups → Independent samples t-test (or ANOVA, equivalent)
└─ Three or more groups → ANOVA
   ├─ ANOVA insignificant (p &gt; α) → Stop, no evidence of differences
   └─ ANOVA significant (p &lt; α) → Post-hoc tests (Tukey or Bonferroni)</code></pre>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>ANOVA Quick Reference
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>When to Use ANOVA:</strong></p>
<ul>
<li>Comparing means of three or more groups<br>
</li>
<li>Want to control family-wise error rate<br>
</li>
<li>Example: Compare satisfaction across multiple properties</li>
</ul>
<p><strong>F-Statistic Interpretation:</strong></p>
<ul>
<li>F = between-group variation / within-group variation<br>
</li>
<li>Large F → groups differ more than expected by chance<br>
</li>
<li>Small F → observed differences consistent with random variation</li>
</ul>
<p><strong>Post-Hoc Testing:</strong></p>
<ul>
<li>Only conduct if ANOVA is significant<br>
</li>
<li>Use Tukey HSD or Bonferroni correction<br>
</li>
<li>Controls Type I error inflation from multiple comparisons</li>
</ul>
<p><strong>Common Mistakes:</strong></p>
<ul>
<li>Running multiple t-tests without ANOVA<br>
</li>
<li>No adjustment for multiple comparisons<br>
</li>
<li>Accepting H₀ when ANOVA is non-significant<br>
</li>
<li>Ignoring unequal sample sizes</li>
</ul>
</div>
</div>
<hr>
</section>
</section>
<section id="lecture-5-review-categorical-data-analysisassociation-causation" class="level2" data-number="7.7">
<h2 data-number="7.7" class="anchored" data-anchor-id="lecture-5-review-categorical-data-analysisassociation-causation"><span class="header-section-number">7.7</span> Lecture 5 Review: Categorical Data Analysis—Association ≠ Causation</h2>
<p>“PixelPerfect Marketing Agency was our final case,” David begins, “and in some ways, the most dangerous. Because their statistical analysis was technically correct, but their interpretation was completely wrong.”</p>
<section id="the-core-lesson-statistical-association-does-not-establish-causation" class="level3">
<h3 class="anchored" data-anchor-id="the-core-lesson-statistical-association-does-not-establish-causation">The Core Lesson: Statistical Association Does Not Establish Causation</h3>
<p>Maria projects the PixelPerfect findings:</p>
<p><strong>Their Analysis:</strong></p>
<ul>
<li>Tested whether marketing channel (Social Media, Email, Display Ads, Search Ads) was associated with conversion outcome<br>
</li>
<li>χ² = 42.87, p &lt; 0.001<br>
</li>
<li>Conclusion: “Channel choice <strong>causes</strong> different conversion rates”<br>
</li>
<li>Recommendation: Reallocate $150,000 budget based on observed conversion rates</li>
</ul>
<p>“Everything up to the word ‘causes’ was correct,” David emphasizes. “The chi-square test shows association. But association doesn’t prove causation—especially in observational data.”</p>
</section>
<section id="a-students-question-why-cant-i-say-causes-if-its-significant" class="level3">
<h3 class="anchored" data-anchor-id="a-students-question-why-cant-i-say-causes-if-its-significant">A Student’s Question: “Why Can’t I Say ‘Causes’ If It’s Significant?”</h3>
<p>Sarah challenges this. “If the chi-square test shows a significant relationship with p &lt; 0.001, why can’t I say the channel causes the difference? Isn’t that what ‘significant’ means?”</p>
<p>David shakes his head. “This is the most important distinction in all of applied statistics. Statistical significance tells you the association is unlikely due to chance. It doesn’t tell you why the association exists.”</p>
<p>Maria pulls up an example:</p>
<p><strong>Simpson’s Paradox Scenario:</strong></p>
<p>“Imagine Social Media appears to have the highest conversion rate overall. But when you stratify by product type:”</p>
<p><strong>Premium Products</strong> (naturally high conversion):</p>
<ul>
<li>Email: 30% conversion<br>
</li>
<li>Social Media: 28% conversion</li>
</ul>
<p><strong>Budget Products</strong> (naturally low conversion):</p>
<ul>
<li>Email: 15% conversion<br>
</li>
<li>Social Media: 13% conversion</li>
</ul>
<p>“Email is better for both product types individually, but Social Media appears better overall because it’s used more heavily for premium products. The apparent channel advantage is actually product mix.”</p>
<p>“This is Simpson’s Paradox—an association that reverses when you account for confounding variables. Chi-square can’t detect this. You need to think about the data-generating process.”</p>
</section>
<section id="common-pitfalls-in-categorical-data-analysis" class="level3">
<h3 class="anchored" data-anchor-id="common-pitfalls-in-categorical-data-analysis">Common Pitfalls in Categorical Data Analysis</h3>
<p><strong>Pitfall 1: Confusing Association with Causation</strong></p>
<p>“PixelPerfect’s original report said: ‘χ² = 42.87 proves channel choice causes conversion differences,’” David recalls. “We had to explain: Chi-square establishes association in observational data. Causation requires randomization or strong causal identification strategy.”</p>
<p><strong>The Correction:</strong><br>
“χ² = 42.87 provides strong evidence that channel and conversion are statistically associated. However, observational marketing data cannot establish causation. Apparent channel effects may reflect confounding variables such as product type, customer demographics, or seasonal patterns.”</p>
<p>Maria adds a cautionary example: “We also discovered what statisticians call ‘spurious correlations’—associations that exist in the data but have no meaningful causal connection.”</p>
<p>She projects a striking example:</p>
<p><strong>Spurious Correlation in Marketing Data:</strong></p>
<p>“In PixelPerfect’s Q3 data, we found a statistically significant association between customer zip code digit sum and conversion rate. Customers whose zip code digits summed to an even number converted at 22%, while odd-sum zip codes converted at 17%. Chi-square test: p = 0.008.”</p>
<p>“This was statistically significant. Should PixelPerfect target even-sum zip codes?”</p>
<p>The class laughs, but Maria stays serious. “This actually happened. And without thinking critically, someone could have built a targeting strategy around it. The association is real in the data—it’s just meaningless. Pure coincidence arising from multiple testing and pattern-seeking in large datasets.”</p>
<p>“The lesson: Statistical significance doesn’t validate causal mechanisms. Just because you can find an association doesn’t mean it’s meaningful. Always ask: ‘What’s the causal story? Does this make business sense?’”</p>
<p><strong>Pitfall 2: Overconfident Interpretation of P-Values</strong></p>
<p>“They said: ‘p &lt; 0.001 means we can be 99.9% confident in reallocating the budget,’” Maria notes. “That’s not what p-values mean. A small p-value tells you the association is unlikely due to chance, not that your recommended action is correct.”</p>
<p><strong>Pitfall 3: Ignoring Effect Size</strong></p>
<p>“They reported χ² = 42.87 but not Cramér’s V,” David adds. “Cramér’s V = 0.095—a small to moderate association. Statistically significant? Yes. Practically large enough to justify $150,000 reallocation? Questionable.”</p>
<p>“Statistical significance ≠ practical significance. Always report and interpret effect sizes, not just p-values.”</p>
</section>
<section id="the-recommended-approach-pilot-study" class="level3">
<h3 class="anchored" data-anchor-id="the-recommended-approach-pilot-study">The Recommended Approach: Pilot Study</h3>
<p>Carlos asks, “So what did you actually recommend to PixelPerfect?”</p>
<p>Maria pulls up their revised recommendation:</p>
<p><strong>Phase 1: Pilot Test ($20,000)</strong></p>
<ul>
<li>Randomly assign customers to channels (true randomization)<br>
</li>
<li>Control for product type, demographics, time period<br>
</li>
<li>Measure channel effects under controlled conditions<br>
</li>
<li>This establishes causation</li>
</ul>
<p><strong>Phase 2: If Pilot Succeeds</strong></p>
<ul>
<li>Scale up with confidence<br>
</li>
<li>Continue monitoring for changes in effectiveness</li>
</ul>
<p>“We recommended spending $20,000 to test causation before reallocating $150,000 based on potentially spurious associations. That’s evidence-based decision-making.”</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Categorical Data Analysis Quick Reference
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Chi-Square Test of Independence:</strong></p>
<ul>
<li>Tests whether two categorical variables are associated<br>
</li>
<li>χ² = Σ[(Observed - Expected)² / Expected]<br>
</li>
<li><strong>Interpretation</strong>: “Variables are statistically associated”<br>
</li>
<li><strong>NOT</strong>: “X causes Y”</li>
</ul>
<p><strong>Association vs.&nbsp;Causation:</strong></p>
<ul>
<li>Chi-square establishes association in observational data<br>
</li>
<li>Causation requires: (1) randomization, (2) temporal precedence, (3) controlling confounders, (4) ruling out alternative explanations<br>
</li>
<li>In observational studies: Always suspect confounding</li>
</ul>
<p><strong>Effect Size Matters:</strong></p>
<ul>
<li>Cramér’s V measures strength of association (0 to 1)<br>
</li>
<li>V &lt; 0.1: small, 0.1-0.3: moderate, &gt;0.3: large<br>
</li>
<li>Statistical significance ≠ practical significance</li>
</ul>
<p><strong>Simpson’s Paradox:</strong></p>
<ul>
<li>Association can reverse when stratifying by confounders<br>
</li>
<li>Always check whether associations hold within subgroups<br>
</li>
<li>Aggregated data can be misleading</li>
</ul>
<p><strong>Recommendations:</strong></p>
<ul>
<li>Observational data: Report associations, not causal claims<br>
</li>
<li>If making budget decisions: Pilot test with randomization<br>
</li>
<li>Monitor for changes (today’s association may not persist)</li>
</ul>
</div>
</div>
<hr>
</section>
</section>
<section id="the-mistakes-we-almost-made-a-candid-reflection" class="level2" data-number="7.8">
<h2 data-number="7.8" class="anchored" data-anchor-id="the-mistakes-we-almost-made-a-candid-reflection"><span class="header-section-number">7.8</span> The Mistakes We Almost Made: A Candid Reflection</h2>
<p>The presentation has covered the technical content. Now comes the hard part.</p>
<p>“Before we talk about what’s next,” Maria says, “we want to share the mistakes we almost made. Because knowing the formulas isn’t enough—you need to develop statistical judgment.”</p>
<section id="mistake-1-treating-calculations-as-understanding" class="level3">
<h3 class="anchored" data-anchor-id="mistake-1-treating-calculations-as-understanding">Mistake #1: Treating Calculations as Understanding</h3>
<p>“We calculated the coefficient of variation for TechFlow,” David admits. “Got CV = 5.3% for monthly revenue and CV = 46.6% for products. We almost just reported those numbers without interpretation.”</p>
<p>“Then Sarah asked: ‘So what?’ And we froze. We’d done the math but hadn’t thought about what it meant.”</p>
<p>“That’s when we learned: Every statistic must answer a business question. If you can’t explain why a number matters, don’t report it.”</p>
</section>
<section id="mistake-2-confusing-correct-with-appropriate" class="level3">
<h3 class="anchored" data-anchor-id="mistake-2-confusing-correct-with-appropriate">Mistake #2: Confusing “Correct” with “Appropriate”</h3>
<p>“For PrecisionCast, we calculated exact probabilities using the binomial distribution,” Maria recalls. “We were proud of our precision. Then Robert asked: ‘Should I invest $2 million?’”</p>
<p>“We’d calculated P(X &gt; 1,200) = 10.2% correctly. But we hadn’t connected it to his decision. The right answer to a question he didn’t ask isn’t helpful.”</p>
<p>“We learned: Statistics serves decisions, not the other way around.”</p>
</section>
<section id="mistake-3-overconfidence-in-our-conclusions" class="level3">
<h3 class="anchored" data-anchor-id="mistake-3-overconfidence-in-our-conclusions">Mistake #3: Overconfidence in Our Conclusions</h3>
<p>“After BorderMed, we wrote: ‘The drug reduces blood pressure by 10.6 to 14.2 mmHg,’” David says. “Our professor circled it in red and wrote: ‘Are you sure?’”</p>
<p>“We’d reported the confidence interval correctly. But we’d stated it like a fact. The drug doesn’t ‘reduce blood pressure by 10.6 to 14.2 mmHg’—that’s the range we estimate based on 85 patients.”</p>
<p>“Better: ‘We estimate the drug reduces blood pressure by 10.6 to 14.2 mmHg (95% CI, n=85).’”</p>
<p>“That subtle difference—acknowledging uncertainty—separates good statisticians from dangerous ones.”</p>
</section>
<section id="mistake-4-accepting-results-that-confirmed-our-priors" class="level3">
<h3 class="anchored" data-anchor-id="mistake-4-accepting-results-that-confirmed-our-priors">Mistake #4: Accepting Results That Confirmed Our Priors</h3>
<p>“DesertVine’s original report said all properties performed equivalently,” Maria notes. “We wanted to believe it—it was the ‘good news’ story. We almost didn’t dig deeper.”</p>
<p>“Then David noticed: ‘Wait, Albuquerque only has 47 guests. How can they be confident about equivalence?’ We reran the analysis and found significant property differences (F = 4.89, p = 0.003).”</p>
<p>“We learned: Be extra skeptical of results that tell you what you want to hear.”</p>
</section>
<section id="mistake-5-confusing-statistical-significance-with-importance" class="level3">
<h3 class="anchored" data-anchor-id="mistake-5-confusing-statistical-significance-with-importance">Mistake #5: Confusing Statistical Significance with Importance</h3>
<p>“PixelPerfect’s chi-square test gave p &lt; 0.001,” David recalls. “We almost recommended the full $150,000 reallocation because the result was ‘highly significant.’”</p>
<p>“Then we calculated Cramér’s V = 0.095—a small effect size. Statistical significance with n=2,400 doesn’t automatically mean large practical importance.”</p>
<p>“We learned: Always report effect sizes alongside p-values. And always ask: ‘Is this large enough to matter for the decision at hand?’”</p>
</section>
</section>
<section id="looking-forward-preparing-for-econometrics" class="level2" data-number="7.9">
<h2 data-number="7.9" class="anchored" data-anchor-id="looking-forward-preparing-for-econometrics"><span class="header-section-number">7.9</span> Looking Forward: Preparing for Econometrics</h2>
<p>The professor stands. “Thank you, David and Maria. Your journey illustrates something crucial: Statistics isn’t just formulas and calculations. It’s a way of thinking about uncertainty, evidence, and decisions.”</p>
<p>“You’ve mastered the foundations: description, probability, inference, comparison, and association. But notice what’s missing from your toolkit?”</p>
<p>A student named Alex raises his hand tentatively. “Prediction? You’ve described relationships, but you haven’t modeled them mathematically.”</p>
<p>“Exactly,” the professor nods. “You’ve answered questions like:”</p>
<ul>
<li>‘What happened?’ (Descriptive statistics)<br>
</li>
<li>‘What will happen?’ (Probability)<br>
</li>
<li>‘What can we conclude?’ (Inference)<br>
</li>
<li>‘Which groups differ?’ (ANOVA)<br>
</li>
<li>‘What’s associated with what?’ (Chi-square)</li>
</ul>
<p>“But you haven’t answered:”</p>
<ul>
<li>‘How much does X affect Y?’ (Regression)<br>
</li>
<li>‘Which variables matter most?’ (Multiple regression)<br>
</li>
<li>‘Can we predict outcomes from predictors?’ (Econometric modeling)</li>
</ul>
<section id="the-bridge-to-econometrics" class="level3">
<h3 class="anchored" data-anchor-id="the-bridge-to-econometrics">The Bridge to Econometrics</h3>
<p>David projects one final slide:</p>
<p><strong>The Natural Progression:</strong></p>
<p><strong>Lecture 1: Descriptive Statistics</strong><br>
→ Measured relationships (correlation: r = -0.68 between response time and satisfaction)</p>
<p><strong>Lecture 5: Categorical Data Analysis</strong><br>
→ Tested associations (chi-square: channel and conversion are associated)</p>
<p><strong>Lecture 6 (Next): Regression Analysis</strong><br>
→ Model relationships mathematically<br>
→ Quantify effects: “Each 1-hour increase in response time decreases satisfaction by 0.08 points”<br>
→ Predict outcomes: “Given these customer characteristics and service attributes, predicted satisfaction = 7.2”<br>
→ Control for confounders: “After controlling for product type, Social Media increases conversion by 3.2 percentage points”</p>
<p>“You’ve been seeing relationships in data all semester,” Maria observes. “TechFlow’s correlation between response times and satisfaction. DesertVine’s property differences. PixelPerfect’s channel associations. But you’ve only described them, not modeled them.”</p>
<p>“Regression gives you the mathematical framework to model those relationships. To quantify exactly how much one variable affects another. To predict outcomes. To control for confounding. To test causal mechanisms.”</p>
<p>“Everything you’ve learned builds to this,” David concludes. “Descriptive statistics taught you about variability—regression models that variability. Probability taught you about distributions—regression uses those distributions. Inference taught you about uncertainty—regression quantifies it with standard errors and confidence intervals. ANOVA taught you about group comparisons—regression generalizes that to continuous predictors. Chi-square taught you about associations—regression models those associations mathematically.”</p>
</section>
<section id="what-makes-econometrics-different" class="level3">
<h3 class="anchored" data-anchor-id="what-makes-econometrics-different">What Makes Econometrics Different?</h3>
<p>The professor adds, “Econometrics extends regression by taking seriously the causal questions you’ve been wrestling with all semester.”</p>
<p>“When PixelPerfect asked ‘Does Social Media cause higher conversions?’, you correctly said: ‘We can’t tell from observational data.’ Econometrics gives you tools to address causation: instrumental variables, difference-in-differences, regression discontinuity, fixed effects.”</p>
<p>“When BorderMed worried about Type I and Type II errors, you calculated them for single hypothesis tests. Econometrics extends this to complex models with multiple predictors, teaching you about specification error, omitted variable bias, and model selection.”</p>
<p>“When DesertVine had unequal sample sizes across properties, you noted the precision differences but couldn’t formally model them. Econometrics gives you weighted regression, hierarchical models, and robust standard errors.”</p>
<p>“The foundations you’ve built—understanding variability, probability, inference, multiple comparisons, and the difference between association and causation—those are essential. But now we layer on the modeling framework that lets you answer ‘how much?’ and ‘what if?’”</p>
</section>
<section id="a-final-question-from-the-cohort" class="level3">
<h3 class="anchored" data-anchor-id="a-final-question-from-the-cohort">A Final Question from the Cohort</h3>
<p>Miguel raises his hand one last time. “After everything you’ve learned, if you could give one piece of advice to someone just starting their statistical journey, what would it be?”</p>
<p>David and Maria exchange glances. They’d anticipated this question.</p>
<p>Maria speaks first: “Statistical methods are tools, not magic. They can’t fix bad data, biased samples, or flawed study designs. We learned that with PixelPerfect—no amount of sophisticated analysis can turn observational data into causal conclusions.”</p>
<p>David adds: “Always ask three questions before running any analysis: (1) What business question am I answering? (2) What assumptions am I making? (3) What could I be wrong about? If you can’t answer all three, you’re not ready to interpret results.”</p>
<p>“But most importantly,” Maria concludes, “statistical significance is not the same as practical importance, and p-values are not proof. Every number you report should make a decision clearer, not just make you look smart.”</p>
</section>
</section>
<section id="chapter-summary-the-statistical-toolkit-in-review" class="level2" data-number="7.10">
<h2 data-number="7.10" class="anchored" data-anchor-id="chapter-summary-the-statistical-toolkit-in-review"><span class="header-section-number">7.10</span> Chapter Summary: The Statistical Toolkit in Review</h2>
<p>The professor concludes the session: “You’ve just witnessed the progression from description to decision. Let me synthesize what David and Maria have shown you.”</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>The Complete Statistical Framework
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Stage 1: Descriptive Statistics</strong> (What happened?)</p>
<ul>
<li>Measures of location: mean, median, percentiles<br>
</li>
<li>Measures of variability: SD, CV, IQR<br>
</li>
<li>Distribution characteristics: skewness, outliers, z-scores<br>
</li>
<li>Association: correlation<br>
</li>
<li><strong>Key lesson</strong>: Precision replaces vagueness</li>
</ul>
<p><strong>Stage 2: Probability</strong> (What will happen?)</p>
<ul>
<li>Basic probability: P(Event)<br>
</li>
<li>Conditional probability: P(A|B)<br>
</li>
<li>Bayes’ Theorem: Reversing conditional probabilities<br>
</li>
<li>Expected value: E(X)<br>
</li>
<li>Distributions: Binomial, Normal<br>
</li>
<li><strong>Key lesson</strong>: Quantify uncertainty for decisions</li>
</ul>
<p><strong>Stage 3: Statistical Inference</strong> (What can we conclude?)</p>
<ul>
<li>Confidence intervals: Quantify uncertainty in estimates<br>
</li>
<li>Hypothesis testing: Evaluate evidence against null<br>
</li>
<li>P-values: Probability of data given H₀<br>
</li>
<li>Type I and Type II errors<br>
</li>
<li>Sample size and power<br>
</li>
<li><strong>Key lesson</strong>: Acknowledge what you don’t know</li>
</ul>
<p><strong>Stage 4: ANOVA</strong> (Which groups differ?)</p>
<ul>
<li>F-test: Omnibus test for group differences<br>
</li>
<li>Post-hoc testing: Specific pairwise comparisons<br>
</li>
<li>Multiple testing adjustments: Bonferroni, Tukey<br>
</li>
<li>Effect sizes: Practical vs.&nbsp;statistical significance<br>
</li>
<li><strong>Key lesson</strong>: Control error rates in multiple comparisons</li>
</ul>
<p><strong>Stage 5: Categorical Data Analysis</strong> (What relates to what?)</p>
<ul>
<li>Chi-square test: Association between categorical variables<br>
</li>
<li>Effect size: Cramér’s V<br>
</li>
<li>Confidence intervals for proportions<br>
</li>
<li>Association vs.&nbsp;causation<br>
</li>
<li>Simpson’s Paradox<br>
</li>
<li><strong>Key lesson</strong>: Association ≠ causation</li>
</ul>
<p><strong>Stage 6: Regression &amp; Econometrics</strong> (How much? What if?)</p>
<ul>
<li>Model relationships mathematically<br>
</li>
<li>Quantify effects<br>
</li>
<li>Predict outcomes<br>
</li>
<li>Control for confounding<br>
</li>
<li>Causal inference methods<br>
</li>
<li><strong>Key lesson</strong>: Coming next…</li>
</ul>
</div>
</div>
<section id="the-common-thread-statistical-thinking" class="level3">
<h3 class="anchored" data-anchor-id="the-common-thread-statistical-thinking">The Common Thread: Statistical Thinking</h3>
<p>“Notice what connects all five lectures,” the professor points out. “It’s not the formulas. It’s the mindset.”</p>
<p><strong>Statistical thinking means:</strong></p>
<ol type="1">
<li><strong>Distinguish data from populations</strong>: Samples estimate, they don’t define<br>
</li>
<li><strong>Quantify uncertainty</strong>: Every estimate has a margin of error<br>
</li>
<li><strong>Avoid overconfidence</strong>: ‘Significant’ doesn’t mean ‘large’ or ‘certain’<br>
</li>
<li><strong>Question assumptions</strong>: What could make my conclusions wrong?<br>
</li>
<li><strong>Serve decisions</strong>: Statistics inform action, not replace judgment<br>
</li>
<li><strong>Think causally</strong>: Association is not causation without proper identification<br>
</li>
<li><strong>Report honestly</strong>: Acknowledge limitations, not just strengths</li>
</ol>
<p>“These principles don’t change whether you’re calculating a mean or running a regression. They’re the foundation of rigorous quantitative analysis.”</p>
</section>
</section>
<section id="closing-thoughts-the-journey-continues" class="level2" data-number="7.11">
<h2 data-number="7.11" class="anchored" data-anchor-id="closing-thoughts-the-journey-continues"><span class="header-section-number">7.11</span> Closing Thoughts: The Journey Continues</h2>
<p>As students pack up their laptops, several cluster around David and Maria with follow-up questions. The professor watches, satisfied.</p>
<p>“You’re ready,” he says when the room finally clears. “You’ve built the foundation. You understand variability, probability, inference, comparison, and association. You’ve learned to distinguish statistical significance from practical importance. You’ve internalized that correlation isn’t causation.”</p>
<p>“Next lecture, we layer regression and econometrics on top of this foundation. You’ll learn to model the relationships you’ve been describing. To quantify the effects you’ve been observing. To predict the outcomes you’ve been analyzing.”</p>
<p>“But remember: Regression is powerful, but it’s not magic. It can’t fix bad data, substitute for causal reasoning, or replace business judgment. The same principles you learned from TechFlow, PrecisionCast, BorderMed, DesertVine, and PixelPerfect still apply.”</p>
<p>“The journey from vague descriptions to precise statistics to informed decisions—that continues. The only thing changing is the sophistication of the tools.”</p>
<p>David and Maria walk out of the lecture hall into the November sunshine, already thinking about regression analysis. Five companies down. One statistical framework built. And the most powerful tool—econometric modeling—still ahead.</p>
<p>But they’re ready. Because they understand that statistics isn’t about memorizing formulas. It’s about developing the judgment to use those formulas wisely, interpret results honestly, and serve the decision-makers who depend on their analysis.</p>
<p>The journey continues.</p>
<hr>
</section>
<section id="practice-questions-for-review" class="level2" data-number="7.12">
<h2 data-number="7.12" class="anchored" data-anchor-id="practice-questions-for-review"><span class="header-section-number">7.12</span> Practice Questions for Review</h2>
<p>To consolidate your understanding of Lectures 1-5, work through these integrative questions that require connecting multiple concepts:</p>
<section id="question-1-connecting-descriptive-statistics-and-inference" class="level3">
<h3 class="anchored" data-anchor-id="question-1-connecting-descriptive-statistics-and-inference">Question 1: Connecting Descriptive Statistics and Inference</h3>
<p>A company collects customer satisfaction scores from 200 customers and finds:</p>
<ul>
<li>Mean = 7.8<br>
</li>
<li>Median = 8.2<br>
</li>
<li>SD = 2.1<br>
</li>
<li>Skewness = -0.85</li>
</ul>
<p><strong>Answer these questions:</strong></p>
<ol type="a">
<li>Based on skewness, is the distribution symmetric? If not, which direction is it skewed?<br>
</li>
<li>Should the company report mean or median in their marketing materials? Why?<br>
</li>
<li>Calculate the 95% confidence interval for the population mean satisfaction.<br>
</li>
<li>The company claims “Our average satisfaction exceeds 7.5.” Test this claim at α = 0.05.<br>
</li>
<li>Explain why reporting only the point estimate (7.8) without a confidence interval would be inadequate.</li>
</ol>
</section>
<section id="question-2-connecting-probability-and-inference" class="level3">
<h3 class="anchored" data-anchor-id="question-2-connecting-probability-and-inference">Question 2: Connecting Probability and Inference</h3>
<p>A quality control system has 98% sensitivity (detects 98% of defects) and 97% specificity (correctly passes 97% of good items). The true defect rate is 3%.</p>
<p><strong>Answer these questions:</strong></p>
<ol type="a">
<li>If a part tests positive, what’s the probability it’s actually defective? (Use Bayes’ Theorem)<br>
</li>
<li>If you test 1,000 parts, what’s the expected number of false positives?<br>
</li>
<li>You observe 45 defects in a sample of 1,000 parts. Calculate the 95% confidence interval for the true defect rate.<br>
</li>
<li>Test whether the observed defect rate differs significantly from the claimed 3% rate.<br>
</li>
<li>Explain how the concepts of probability (parts a-b) and inference (parts c-d) complement each other.</li>
</ol>
</section>
<section id="question-3-connecting-anova-and-multiple-testing" class="level3">
<h3 class="anchored" data-anchor-id="question-3-connecting-anova-and-multiple-testing">Question 3: Connecting ANOVA and Multiple Testing</h3>
<p>A retail chain tests three store layouts (A, B, C) with the following daily sales (in thousands):</p>
<ul>
<li>Layout A (n=30): Mean = $45.2, SD = $6.1<br>
</li>
<li>Layout B (n=30): Mean = $48.7, SD = $5.8<br>
</li>
<li>Layout C (n=30): Mean = $43.5, SD = $6.3</li>
</ul>
<p>ANOVA results: F = 6.42, p = 0.003</p>
<p><strong>Answer these questions:</strong></p>
<ol type="a">
<li>What does F = 6.42 tell you about between-group vs.&nbsp;within-group variation?<br>
</li>
<li>Based on the ANOVA result, what can you conclude about the three layouts?<br>
</li>
<li>If you want to compare all pairwise combinations (A vs.&nbsp;B, A vs.&nbsp;C, B vs.&nbsp;C), what should your adjusted α be using Bonferroni correction?<br>
</li>
<li>Layout B has the highest mean. Can you conclude “Layout B is superior”? What additional analysis is needed?<br>
</li>
<li>What would be the problem with running three separate t-tests instead of ANOVA?</li>
</ol>
</section>
<section id="question-4-connecting-categorical-analysis-and-causation" class="level3">
<h3 class="anchored" data-anchor-id="question-4-connecting-categorical-analysis-and-causation">Question 4: Connecting Categorical Analysis and Causation</h3>
<p>A marketing study finds that customers who receive email promotions have 22% conversion rate, while customers who don’t receive emails have 15% conversion rate. Chi-square test: χ² = 18.4, p &lt; 0.001, n = 800.</p>
<p><strong>Answer these questions:</strong></p>
<ol type="a">
<li>What does the chi-square test tell you about the relationship between emails and conversion?<br>
</li>
<li>Can you conclude “Email promotions cause higher conversion rates”? Why or why not?<br>
</li>
<li>Describe a confounding variable that might explain the association.<br>
</li>
<li>How would you design a study to test whether emails cause higher conversions?<br>
</li>
<li>Even if the association is causal, calculate the 95% confidence interval for the conversion rate difference. What does this tell you about the precision of the effect estimate?</li>
</ol>
</section>
<section id="question-5-integrative-case-study" class="level3">
<h3 class="anchored" data-anchor-id="question-5-integrative-case-study">Question 5: Integrative Case Study</h3>
<p>You’re analyzing employee productivity across four departments with the following data:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Department</th>
<th style="text-align: left;">n</th>
<th style="text-align: left;">Mean Productivity</th>
<th style="text-align: left;">SD</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Sales</td>
<td style="text-align: left;">45</td>
<td style="text-align: left;">87.2</td>
<td style="text-align: left;">12.3</td>
</tr>
<tr class="even">
<td style="text-align: left;">Marketing</td>
<td style="text-align: left;">38</td>
<td style="text-align: left;">92.5</td>
<td style="text-align: left;">10.8</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Operations</td>
<td style="text-align: left;">52</td>
<td style="text-align: left;">85.1</td>
<td style="text-align: left;">14.1</td>
</tr>
<tr class="even">
<td style="text-align: left;">Finance</td>
<td style="text-align: left;">30</td>
<td style="text-align: left;">88.9</td>
<td style="text-align: left;">11.7</td>
</tr>
</tbody>
</table>
<p>Additional information: Productivity is measured on a 0-100 scale. Company average across all employees is 87.8.</p>
<p><strong>Answer these questions:</strong></p>
<ol type="a">
<li><strong>Descriptive</strong>: Calculate the coefficient of variation for each department. Which department has the most consistent productivity?<br>
</li>
<li><strong>Inference</strong>: Calculate the 95% confidence interval for Marketing’s mean productivity. Can you conclude Marketing exceeds the company average of 87.8?<br>
</li>
<li><strong>ANOVA</strong>: If ANOVA gives F = 4.12, p = 0.008, what can you conclude? What would be your next statistical step?<br>
</li>
<li><strong>Interpretation</strong>: If Finance has the smallest sample size (n=30), how does this affect the reliability of conclusions about Finance compared to other departments?<br>
</li>
<li><strong>Decision</strong>: The CEO wants to implement Marketing’s practices company-wide because they have the highest mean productivity. What statistical and practical concerns would you raise?</li>
</ol>
<hr>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Final Thoughts: Statistical Maturity
</div>
</div>
<div class="callout-body-container callout-body">
<p>You’ve now completed the foundational sequence. You understand:</p>
<ul>
<li>How to describe data precisely (Lecture 1)<br>
</li>
<li>How to quantify uncertainty (Lecture 2)<br>
</li>
<li>How to make inferences from samples (Lecture 3)<br>
</li>
<li>How to compare multiple groups (Lecture 4)<br>
</li>
<li>How to analyze categorical relationships (Lecture 5)</li>
</ul>
<p>But more importantly, you’ve developed statistical judgment:</p>
<ul>
<li>You know when to use mean vs.&nbsp;median<br>
</li>
<li>You understand what p-values do and don’t tell you<br>
</li>
<li>You recognize that “fail to reject” ≠ “accept”<br>
</li>
<li>You appreciate the difference between statistical and practical significance<br>
</li>
<li>You understand that association ≠ causation</li>
</ul>
<p>This judgment—knowing not just how to calculate but when to calculate and how to interpret—is what distinguishes competent analysts from dangerous ones.</p>
<p>As you move into regression and econometrics, these principles remain constant. The math gets more sophisticated, but the thinking stays the same: Be precise about what you know, honest about what you don’t, and always serve the decision at hand.</p>
<p>Welcome to the next stage of your statistical journey.</p>
</div>
</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/ncachanosky\.github\.io\/XQMB-5311");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./chapter_05.html" class="pagination-link" aria-label="Categorical Data Analysis">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Categorical Data Analysis</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./chapter_07.html" class="pagination-link" aria-label="Regression Analysis: Introduction to Econometrics">
        <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Regression Analysis: Introduction to Econometrics</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© Nicolas Cachanosky, The University of Texas at El Paso, Center for Free Enterprise</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/ncachanosky/XQMB-5311/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link active" href="https://github.com/ncachanosky/XQMB-5311" aria-current="page">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/ncachanosky">
      <i class="bi bi-linkedin" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com/n_cachanosky">
      <i class="bi bi-twitter-x" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




<script src="site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>